### PR TITLE
[WIP] Initial port of ipython tests from nose to pytest.

### PR DESCRIPTION
**Pull request by mcepl**
Relates to https://github.com/ipython/ipython_genutils/issues/17

I am a maintainer of Python packages in openSUSE, and I am on my crusade of eliminating nose1 from our distribution. When I look at its repository on https://github.com/nose-devs/nose, the last release 1.3.7 was on 2 Jun 2015, and even the last commit on the master branch was on 4 Mar 2016.

This is my effort towards eliminating dependency on nose, which has been unnecessary for a long time. Resulting test suite depends on pytest, which is currently perfectly developed and maintained.

Currently I am able to run and pass whole test suite using pytest (without doctests) and everything passes, except of in the end I get nasty error message:
```
[   40s] Error in atexit._run_exitfuncs:
[   40s] Traceback (most recent call last):
[   40s]   File "/home/abuild/rpmbuild/BUILD/ipython-7.21.0/IPython/core/history.py", line 576, in end_session
[   40s]     self.db.execute("""UPDATE sessions SET end=?, num_cmds=? WHERE
[   40s] sqlite3.OperationalError: attempt to write a readonly database
[   40s] Error in atexit._run_exitfuncs:
[   40s] Traceback (most recent call last):
[   40s]   File "/home/abuild/rpmbuild/BUILD/ipython-7.21.0/IPython/core/history.py", line 576, in end_session
[   40s]     self.db.execute("""UPDATE sessions SET end=?, num_cmds=? WHERE
[   40s] sqlite3.OperationalError: attempt to write a readonly database
[   40s] Error in atexit._run_exitfuncs:
[   40s] Traceback (most recent call last):
[   40s]   File "/home/abuild/rpmbuild/BUILD/ipython-7.21.0/IPython/core/history.py", line 576, in end_session
[   40s]     self.db.execute("""UPDATE sessions SET end=?, num_cmds=? WHERE
[   40s] sqlite3.OperationalError: attempt to write a readonly database
[   40s] Error in atexit._run_exitfuncs:
[   40s] Traceback (most recent call last):
[   40s]   File "/home/abuild/rpmbuild/BUILD/ipython-7.21.0/IPython/core/history.py", line 576, in end_session
[   40s]     self.db.execute("""UPDATE sessions SET end=?, num_cmds=? WHERE
[   40s] sqlite3.OperationalError: attempt to write a readonly database
```
[Complete build log with all details](https://github.com/ipython/ipython/files/6070683/_log.txt).

@Carreau would you be able to help me here?

### CODE REVIEW

**Comment by bollwyvl** [comment]
Amazing work! Will investigate soon, would very much like to see this land.
I wish you well in your crusade!

**Comment by Carreau** [comment]
Thanks that is great ! I think the the Sql errors are unrelated, I've seen them before.
We likely need to set some configuration option somewhere to `":memory:"` to not write to disk during tests.

**Comment by Carreau** [comment]
(I'm also curious how easy this patch can be applied to master).

**Comment by mcepl** [comment]
@Carreau ping? What's the status of this patch now?

**Comment by Carreau** [comment]
Sorry, I need to port it to the `master` branch; as it is likely the one that will remove all nose usage. I need to find the time to do it. 

I'll likely use what you did here and give you proper credit. I just need to find the time.

**Comment by Kojoley** [comment]
Thanks for your effort, this was redone for 8.0 branch in #13115 + #13206 + #13252.

**Pull request closed without merging**
