### PR TITLE
ci: Simplify CI maintenance by combining Ubuntu and macOS workflows

### PR DESCRIPTION
**Pull request by matthewfeickert**
Hi. :wave: On the way to addressing Issue #9874 I realized that the GitHub Actions CI workflows could be simplified quite a bit by combining the `ubuntu-latest` and `macos-latest` workflows by using the `include` option for the testing matrix. So in short, this PR:

* Adds testing as a weekly CRON job on Mondays at 1:23 UTC
* Adds testing on demand through GitHub Actions's worfklow dispatch (gives you a button to press to launch a workflow)
* Tests against CPython 3.7, 3.8, 3.9 on `ubuntu-latest` and on CPython 3.7 and CPython 3.9 on `macos-latest`
* Removes the now redundant `test-osx` workflow

### CODE REVIEW

**Comment by matthewfeickert** [comment]
@meeseeksdev tag testing, osx

**Comment by matthewfeickert** [comment]
@Carreau, @minrk, @takluyver this is ready for review and is passing CI on my fork (I'm a first time contributor and so the GHA won't run until it gets approved here).

passing_ci


Let me know if you have any questions or concerns here. :+1:

**Review by MrMino — APPROVED** [review]
LGTM, but I'd like someone else to look at it too, as I don't have the time to fix the potential fallout (not that I expect any).

**Review by minrk — APPROVED** [review]

**Comment by Carreau** [comment]
Thanks !

**Comment by matthewfeickert** [comment]
Huh. Seems things are failing when merged onto `master`, which is confusing.

oh_noes

I should probably try to help unbreak that first.

**Pull request merged**
