### PR TITLE
Fix undefined labels in docs #2

### PR DESCRIPTION
**Pull request by klonuo**
Fixes for:

```
../ipython/docs/source/interactive/python-ipython-diff.rst:179: WARNING: undefined label: ipython slist (if the link has no caption the label must precede a section header)
../ipython/docs/source/overview.rst:21: WARNING: undefined label: htmlnotebook (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version0.12.rst:101: WARNING: undefined label: htmlnotebook (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version0.12.rst:175: WARNING: undefined label: ssh_tunnels (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version1.0.rst:169: WARNING: undefined label: nbconvert (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version2.0.rst:152: WARNING: undefined label: notebook_security (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version2.0.rst:156: WARNING: undefined label: signing_notebooks (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version3.rst:281: WARNING: undefined label: nbformat (if the link has no caption the label must precede a section header)
```

by simply removing non-existing reference labels.

### CODE REVIEW

**Comment by Carreau** [comment]
@willingc this is documentation again. I'll let you pick this up.

**Comment by takluyver** [comment]
Thanks! Keeping old release notes in every version of the docs does get a bit annoying with cross-references to pages that are moved or removed.

**Comment by willingc** [comment]
@klonuo Thanks for finding and correcting these references. :cake:

@takluyver @Carreau Can one of you merge this PR since I don't have privileges on this repo? Thanks!

**Comment by Carreau** [comment]
Thanks @willingc !

**Pull request merged**
