### PR TITLE
Pin Jedi dependency.

### PR DESCRIPTION
**Pull request by yurzo**
Pins Jedi for the 7.x branch since master its fixed already.
Addresses #12740 and #12745

### CODE REVIEW

**Comment by NeilGirdhar** [comment]
What's the point of this?  Isn't the master ipython already compatible with the newest jedi?

**Comment by yan12125** [comment]
> Isn't the master ipython already compatible with the newest jedi?

Yep, so the author of this pull request targets 7.x branch instead of master. Compatibility with Jedi 0.18 (dcd9dc90aee7e4c5c52ce44c18e7518934790612) is not backported to 7.x branch - the latter still uses a parameter removed from the latest Jedi API: https://github.com/ipython/ipython/blob/7.x/IPython/core/completer.py#L1374

**Comment by NeilGirdhar** [comment]
Oh, got it, didn't notice the target branch!

**Comment by bollwyvl** [comment]
@yurzo thank you! I know it's an annoying thing, but could you re-format the lines that just change the single quotes to double quotes? I'm sure we'll get around to `black`ening the codebase at some point, but until then, it's a lot easier to see changes when a one-line fix is a one-line change.

@Carreau this is starting to cause lots of ripples, and is getting patched in other places... we've pinned on conda-forge, but it can have other consequences. Can you take a look at getting this, or equivalent change in!

**Comment by yurzo** [comment]
@bollwyvl I'd be happy to remove all the quotes.

My original commit was against master, mostly out of ignorance of this project's governance, and it was a minimal Jedi pin (no double quotes).
However, it failed the `darker` checks. I did not know darker but I'm a fan of black so I excitedly acknowledged darker's suggestions.
This morning, prompted by your request, i diffed master vs 7.x and I estimate that darker is enabled on both, so if I do remove the double quotes, checks will fail.

If per project governance I can make this PR as you ask and it can be merged despite failing checks, please let me know and I'll go push a new patch.

**Comment by bollwyvl** [comment]
Yeah, I haven't been tracking to what the state of automation is... :heavy_check_mark: is good!

**Comment by Carreau** [comment]
Sorry I've been a bit overwhelmed. I can't have a look this week end but will try next week.

**Comment by bollwyvl** [comment]
Understandable, a lot of things are overwhelming right now. Take care of yourself, for sure!

**Comment by Carreau** [comment]
Thanks ! I'll try to make a release soon. Will try to get some of the recent PRs in, and do release notes. This week is a bit packed.

**Comment by h-vetinari** [comment]
Thanks! :)

May I just ask though - is there a reason why https://github.com/ipython/ipython/commit/dcd9dc90aee7e4c5c52ce44c18e7518934790612 shouldn't be backported to `7.x` (possibly with a version-guard to keep compatibility with old jedi-versions)? I ask because [8.0](https://github.com/ipython/ipython/issues/11816) still seems a while off.

**Comment by davidhalter** [comment]
It's not a problem - Jedi 0.18.0 fixes only minor issues for IPython. The release gets rid of Python 2, which was its major goal (and which does not matter for IPython).

**Comment by h-vetinari** [comment]
> It's not a problem - Jedi 0.18.0 fixes only minor issues for IPython. The release gets rid of Python 2, which was its major goal (and which does not matter for IPython).

Respectfully, I disagree. If Jedi 0.18.0 breaks ipython 7.x (the very reason for this PR) and 8.x is not happening in the next ~2 months, then - if possible without crazy complexity - IMO 7.x should stay compatible with the newest jedi.

**Comment by SamuelMS** [comment]
> Thanks ! I'll try to make a release soon. Will try to get some of the recent PRs in, and do release notes. This week is a bit packed.

@Carreau Just adding my voice to the clamor here – this is a pretty frustrating issue, as all of our dependent tools (Jupyter, ipdb, Django's shell_plus extensions, etc) break both locally and in production environments. Can you please cut a release to 7.x that pins the version? It can be based on `7.9` with no other changes from `master` – that'd be plenty.

**Pull request merged**
