### PR TITLE
Tagging

### PR DESCRIPTION
**Pull request by jdfreder**
With the addition of cell tags to nbformat v4, it's probably a good time to discuss adding a GUI for tagging and filtering cells.  This PR adds a cell toolbar that uses the Bootstrap-Tags library to enable tagging of cells.  It also adds a filter GUI to the main toolbar that allows you to quickly filter cells by tag.

Ping @jasongrout and @sylvaincorlay who requested this, and @ellisonbg who took a look in person and gave me some suggestions.

### CODE REVIEW

**Comment by stevengj** [comment]
:+1: for porting this to Jupyter.

**Comment by stevengj** [comment]
Any chance of reviving this PR?

**Comment by Carreau** [comment]
Yes, this week is our dev meeting, this is one of the subject we are discussing.

**Comment by stevengj** [comment]
Bump; it would still be great to have this ported.

**Pull request closed without merging**
