### PR TITLE
Calculate indentation based on tokens, not regexes

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-2913
Closes gh-10268

### CODE REVIEW

**Comment by Carreau** [comment]
Wooo, big PR ! I'm reviewing.

**Comment by Carreau** [comment]
Sidenote, I know that jedi have also it's own tokenizer/parser which can handle incomplete code. We'll have to see if we can improve/use it.

**Comment by Carreau** [comment]
Sent you failing test cases https://github.com/takluyver/ipython/pull/18
```
class Bar:
    def foo():
        pass<enter>
```

Will return 0 instead of 4 (on master)

**Comment by Carreau** [comment]
Updated linked PR to fix the failing case as well. 

Once the patch I sent you is in, +1 to merge.

**Comment by Carreau** [comment]
Green Yeah !

**Comment by Carreau** [comment]
Thanks !

**Comment by minrk** [comment]
Very nice

**Pull request merged**
