### PR TITLE
Skip unicode test in C locale

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-10780

### CODE REVIEW

**Comment by takluyver** [comment]
@meeseeksdev backport

**Comment by Carreau** [comment]
I'm playing with the bot's code. Don't worry if it submit a second backport.

**Comment by takluyver** [comment]
OK, thanks for the heads up

**Comment by Carreau** [comment]
> Can't Dooooo.... It seem like this is already backported (commit is empty).I won't do anything. MrMeeseeks out.

Ok, now I believe if a PR against master tagged `5.whatever` is merged. MrMeeseeks should automatically backport.

**Pull request merged**
