### PR TITLE
css spinner

### PR DESCRIPTION
**Pull request by Carreau**
@gibiansky said: 

> [...] Another user played around with the notebook, then accidentally set off a very long-running computation. He then was very confused as to why no more cells were evaluated – In[_] turns out to be a mediocre way to signal "I'm busy", and he just thought that everything had broken and he had to restart the application and that it was buggy. I think that at least might be easily fixed by letting cells have some sort of spinner indicating business instead of In[_], people are more used to that.

This is my attempt at fixing it with pure css : 

capture d ecran 2014-12-24 a 14 06 38

Smooth fade in/out and height change, rotate while the cell as the `.running` class.

technically I would prefer something like [that](http://css-spinners.com/#/spinner/throbber/) but it require to inject a placeholder for the spinner.

Design is of course to be discussed.

### CODE REVIEW

**Comment by damianavila** [comment]
>I can do that. Though it is using box-shadow, so it is not super CPU friendly.
>We should consider using not-pure css. 

I think we need to maintain all the icon styling congruent... so although you did a nice job with the pure css animation I think we need to go the font-awesome ones...

**Comment by Carreau** [comment]
Something is wrong even with fa-spinner. Th CPU climb by 5-10% usage as soon as you have a few cells with spinner. (and increase with number of 'running cells'):
capture d ecran 2015-01-08 a 11 06 28

is ~2% on iddle. 

Figured it out because my laptop fan noise.

**Comment by damianavila** [comment]
mmm... that's too much... not nice, I agree...

**Comment by ellisonbg** [comment]
So what are our options that are CPU friendly? None at all?

On Thu, Jan 8, 2015 at 7:19 AM, Damián Avila <notifications@github.com>
wrote:

> mmm... that's too much... not nice, I agree...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7306#issuecomment-69193327>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
css spinner should be CPU friendly from my understanding. 
They seem not to be, but I don't know why. Gif are an alternative. 
I found https://github.com/FortAwesome/Font-Awesome/issues/701 but they say "Chrome Bug".

Or actually js rotation with a fixed fps framerate.

**Comment by Carreau** [comment]
http://stackoverflow.com/questions/13176746/css-keyframe-animation-cpu-usage-is-high-should-it-be-this-way is a bit old, but we can try;

**Comment by damianavila** [comment]
I guess the gif could be a better alternative... there is still high CPU activity with the link you posted above...

**Comment by ellisonbg** [comment]
Added to the dev meeting agenda for next Tuesday 9:30 am PST.

**Comment by jdfreder** [comment]
@Carreau CPU issues aside, I really like your prompt spinner! :)

**Comment by Carreau** [comment]
> @Carreau CPU issues aside, I really like your prompt spinner! :)

Thanks !

**Comment by Carreau** [comment]
closing in favor of issue #7577 !

**Pull request closed without merging**
