### PR TITLE
Fix widget view persistence.

### LINKED ISSUE #7679: Widget persistence bug
When reloading a notebook that has multiple widget states saved in the browser's local storage, the last widget instantiated is rendered all the widget output areas. 

This should probably be solved before 3.0

### PR DESCRIPTION
**Pull request by jdfreder**
Corrects a variable's scope.

closes #7679

@sylvaincorlay

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Checked out the branch and it does fix the issue.
(One needs to re-execute the cells once first, because whatever was in the local storage before your fix was probably wrong. )

**Comment by minrk** [comment]
@jdfreder thanks for the fix, @SylvainCorlay thanks for the report and confirmation of the fix.

@jdfreder is this something that can be reasonably tested?

**Comment by SylvainCorlay** [comment]
`phantomjs` apparently supports local storage.

**Comment by jdfreder** [comment]
@minrk last commit adds a test.

**Comment by minrk** [comment]
It wasn't possible to test the return value of `get_state` directly? That wasn't incorrect?

**Comment by SylvainCorlay** [comment]
In general, now that you are using the local storage for the widgets, Phantomjs' local storage should probably be cleared before running any test suite.
http://stackoverflow.com/questions/18408868/disabling-localstorage-on-phantomjs-for-clean-testing

**Comment by jasongrout** [comment]
for what it's worth, @jdfreder's analysis and fix of the problem seems appropriate.

**Comment by SylvainCorlay** [comment]
Yeah, :+1:  on this.

**Comment by jdfreder** [comment]
@minrk yeah, the `get_state` call is what was returning an incorrect value.  I implemented the test the way I did so it tests the entire feature.

**Comment by minrk** [comment]
Makes sense, you just said it was ugly, and I thought there might be a way for it to be less so. Thanks!

**Pull request merged**
