### PR TITLE
latex_to_png: avoid deprecated matplotlib functions

### LINKED ISSUE #12882: latex_to_mpl_png relies on deprectated functionality in matplotlib 3.4
Short repro:
```
In [1]: from IPython.lib import latextools                                                                                                                                           

In [2]: png = latextools.latex_to_png_mpl('f(x) = y', True)                                
/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap class was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
```

Deprecation info: https://matplotlib.org/stable/api/api_changes.html#mathtextparser-bitmap-is-deprecated

`math_to_image` has been around since the beginning, so it hopefully has no version compatibility issues: https://github.com/matplotlib/matplotlib/blame/e904fa3b1e5455cf741017268dae7c94b6caa5d6/lib/matplotlib/mathtext.py#L587

### PR DESCRIPTION
**Pull request by jakevdp**
Fixes #12882

The replacement function recommended by matplotlib, `mathtext.math_to_image`, does not provide sufficient control over the output (e.g. text color, transparent background, dpi), so this PR adds code that creates the image manually following the approach in that function.

### CODE REVIEW

**Review by MrMino — COMMENTED** [review]
Quick feedback - I don't feel qualified enough for approving this, but I hope it will help @Carreau with merging / reviewing it further:

Using the snippet provided in the original issue I created two PNGs, one from `ipython:master` and one from `jakevdp:mathtext`

- I can confirm that this PR does indeed get rid of the deprecation messages
- The two files I get differ in the image size: `master` gives me 74x23, the code from this PR - 71x21. Not sure if it's important, might be something to look into.

**Comment by jakevdp** [comment]
Thanks for checking on this – I've seen this difference in image size as well. I suspect that's the difference between the `"path"` parser and the `"bitmap"` parser, and it causes problems for some formula (e.g. `"\int_0^\infty f(x)dx"` ends up slightly cut-off at the top).

I'm going to mark this as a draft for now and see if I can improve on that.

**Comment by Carreau** [comment]
Thanks  @jakevdp and @MrMino. 

The test failures are unrelated, are are regular on those tests; so feel free to ignore those, I'll probably end up marking them as knowfail.

@jakevdp if you are a regular user of this feature and are happy with the result; we can trust you. Let us know if it should be backported on 7.x.

**Comment by jakevdp** [comment]
Thanks! I'm not yet happy with the result, but I'm hoping to dig-in again shortly :grin:

**Comment by jakevdp** [comment]
OK - I adjusted the dpi in the width/height calculation and I think this is ready to go.

**Comment by Carreau** [comment]
Thanks Jake, 

I've maker this as 8.0, if it become which I hope we can start to push forward and release in a coupl eof month, if this becomes too annoying we can still backport later. 

Thanks.

**Comment by jondo** [comment]
My students and I are working with Sympy and are severely influenced by this and similar warnings, see the following example screenshot:
image

and the contained warnings:
<details>
```
/home/robert/projects/teaching/MMech_Exercises_Robert/env/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_png function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/home/robert/projects/teaching/MMech_Exercises_Robert/env/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_rgba function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/home/robert/projects/teaching/MMech_Exercises_Robert/env/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The to_mask function was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)
/home/robert/projects/teaching/MMech_Exercises_Robert/env/lib/python3.8/site-packages/IPython/lib/latextools.py:126: MatplotlibDeprecationWarning: 
The MathtextBackendBitmap class was deprecated in Matplotlib 3.4 and will be removed two minor releases later. Use mathtext.math_to_image instead.
  mt.to_png(f, s, fontsize=12, dpi=dpi, color=color)```
</details>

Would it please be possible to get this into an earlier release? 
Are all of these warnings fixed by this change?

**Comment by jondo** [comment]
Temporary workaround (via https://github.com/computationalmodelling/nbval/issues/167):
```python
import warnings
from matplotlib import MatplotlibDeprecationWarning
warnings.filterwarnings('ignore', category=MatplotlibDeprecationWarning)
```

**Pull request merged**
