### PR TITLE
fix Radio margin

### PR DESCRIPTION
**Pull request by dongweiming**
after:

### CODE REVIEW

**Comment by Carreau** [comment]
Screenshot seem legit. Any reason for 26px, or eyeballed ?

@jdfreder thought ? 

Side question: What's "Expand" thing ?

**Comment by jdfreder** [comment]
I can verify that something has gone awry, I'm trying to figure out why this is happening.  It looks like the specificity got screwed up somehow.

**Comment by jdfreder** [comment]
It may be related to the Bootstrap 3.3 upgrade- https://github.com/ipython/ipython-components/commit/39d3b273c7c16012f46bc3310e85d92d6d00788f#diff-724cc5a431bf2e1a8da1d19c22d21d2dL207 .

**Comment by dongweiming** [comment]
@Carreau
` .widget-area .widget-subarea`'s `margin-left` is 6px;
but, `.radio input[type="radio"]`'s `margin-left` is -20px;

so this need 26px

**Comment by dongweiming** [comment]
@Carreau 'Expand' is a custom extension in my [IPython-notebook-extensions](https://github.com/dongweiming/IPython-notebook-extensions/blob/add_toggle_full_textarea/usability/toggle_full_textarea/main.js)

**Comment by minrk** [comment]
I'm not sure why the subarea's 6px should be taken into account, since this element is already inside the subarea. Shouldn't it just be 20px, then, to reverse the left-shift of the radio button? That seems to align better with other elements.

**Comment by dongweiming** [comment]
@minrk yes. you are right

**Comment by dongweiming** [comment]
@minrk how about this? if i only reverse the left-shift of the radio button. the content in `input[type="radio"]` will be overwritten

**Comment by minrk** [comment]
@dongweiming thanks!

**Comment by SylvainCorlay** [comment]
Shouln't there be the generated css committed with the less?

**Comment by minrk** [comment]
@SylvainCorlay yes, crap. Should have noticed that. Fixed in master.

**Pull request merged**
