### PR TITLE
Adds Julia-style latex->unicode tab completion

### PR DESCRIPTION
**Pull request by ellisonbg**
This makes it much easier to use unicode identifiers in Python 3. This is achieved by converting latex symbols, such as `\alpha` to its unicode equivalent. This works without any modifications to the frontend. All I have done is a bit of new completer logic to the Python kernel.

Questions:
- Where should I put the notebook that autogenerates the map between latex-> unicode?

To do:
- [x] Tests
- [x] Add logic to give a list of possible latex symbols

### CODE REVIEW

**Comment by stevengj** [comment]
@takluyver, that's because Python performs NFKC normalization of the identifiers internally.

**Comment by stevengj** [comment]
Note that this does not seem to be documented anywhere in the IPython manual, or am I missing something?

**Comment by Carreau** [comment]
> Note that this does not seem to be documented anywhere in the IPython manual, or am I missing something?

No you are right this does not seem to be documented..

**Comment by stevengj** [comment]
PS. We are putting together a proposal to the Unicode Consortium to request that they add more subscript and superscript characters for mathematical programming applications (it's crazy that they only have a random subset of Latin and Greek letters).  I already pinged @fperez on this — it would be great to be able to get Jupyter/PSF and other languages/organizations involved, if only as endorsers, to make sure we get the Consortium's attention.  Let me know if there is someone else we should be talking too.

**Comment by stevengj** [comment]
(And if you know an interested person who works on font rendering for Apple/MS/Pango/... that would be extremely helpful.)

**Comment by Carreau** [comment]
> We are putting together a proposal to the Unicode Consortium to request that they add more subscript and superscript characters for mathematical programming applications

@stevengj Is there a thread somewhere ? I can try to ping some people from BIDS / R. We might have some connections.

@jasongrout ; @williamstein ; @SylvainCorlay  will likely care for Sage/Jupyter

@michaelpacer you are font expert, aren't you ?

> it's crazy that they only have a random subset of Latin and Greek letters

That's not [the only thing](https://modelviewculture.com/pieces/i-can-text-you-a-pile-of-poo-but-i-cant-write-my-name) which is [a bit astonishing](http://emojipedia.org/ninja-cat/) from the Unicode consortium ; but my guess is that they lack the diversity to understand the need, or even be aware of the existance of some symbols.

**Comment by willingc** [comment]
FYI @michaelpacer

**Comment by stevengj** [comment]
Right now it is just a Google doc that a few of us are editing, but I'm thinking that I can move it to a github repo so that I can invite broader participation.   LaTeX, I guess?

**Comment by asmeurer** [comment]
@stevengj I am also very interested in this. We use subscript and superscript characters to do math formatting for SymPy in the terminal, but the lack of certain letters limits what we can use. I would love to see full uppercase/lowercase Latin + Greek alphabet for superscript and subscript.

**Comment by Carreau** [comment]
I'm wondering if we know anyone from the Mathjax/KaTeX crowd.

**Comment by stevengj** [comment]
I've created a github repository to work on the proposal for new subscripts/superscripts: https://github.com/stevengj/subsuper-proposal

One of the reasons we need font experts is stevengj/subsuper-proposal#1 … the most general solution would be new combining characters, but I'm not sure how technically difficult this is.

**Comment by jasongrout** [comment]
> PS. We are putting together a proposal to the Unicode Consortium to request that they add more subscript and superscript characters for mathematical programming applications (it's frustrating that they only have a random subset of Latin and Greek letters). I already pinged @fperez on this — it would be great to be able to get Jupyter/PSF and other languages/organizations involved, if only as endorsers, to make sure we get the Consortium's attention. Let me know if there is someone else we should be talking to.

CC @dpvc @pkra 

(see also https://github.com/ipython/ipython/pull/6380#issuecomment-242890960 above)

**Comment by pkra** [comment]
Thanks, @jasongrout. @fperez had already pinged us at https://github.com/stevengj/subsuper-proposal/issues/3.

**Comment by jasongrout** [comment]
I just realized that looking through the issues there - sorry for the noise (I'm just catching up on notifications and pings...)

**Comment by pkra** [comment]
No problem at all. Let us know if you need anything else from us.

**Comment by ShivnarenSrinivasan** [comment]
> Here is a simple example of this types of things that this PR makes really easy if you know latex:
> 
> I honestly think this will convert me to Python 3 :)
> 
> screen shot 2014-08-29 at 7 25 28 am

My apologies for reopening a long dead post—very grateful for this feature.

Most of the completion works great, but was unable to figure out the **vector notation**, or a reference to it anywhere.
In latex, it would be `\vec{\beta}` (𝛽⃗), I suppose? Would be awesome to indicate a variable is a vector with standard notation.

**Comment by Carreau** [comment]
Yes it does not render correctly but that’s a browser bug, that tries to
render the vec on the next instead of previous components.

**Comment by stevengj** [comment]
The box with the question mark is a "missing glyph" symbol — it means that your font doesn't have a rendering of the `\vec` combining character [U+20D7](https://www.fileformat.info/info/unicode/char/20d7/index.htm).  You might need to install a monospace font that supports this symbol, e.g. [JuliaMono](https://juliamono.netlify.app/) has good math-oriented Unicode coverage, and [change the notebook font](https://stackoverflow.com/questions/22386359/how-to-change-font-in-ipython-notebook) to use it.

**Comment by stevengj** [comment]
PS. Julia has updated its tab-completion unicode tables over the years.  You might want to check out our latest tables [here](https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/latex_symbols.jl) and [here](https://github.com/JuliaLang/julia/blob/master/stdlib/REPL/src/emoji_symbols.jl) and consider sync'ing.

**Comment by Carreau** [comment]
Ah thanks Steven, chrome use to show the same glyph when it had the bug.

Btw congrats on all the new Julia features and recent news, and we’ve been
updating our tables by borrowing yours every now and then.

**Pull request merged**
