### PR TITLE
Fix double formatting.

### LINKED ISSUE #9607: mangled ASCII color codes(?) in __init__ signatures
IPython 5.0b3, PTK master, empty `ipython_config.py`.
```
In [6]: class C:
   ...:     def __init__(self): pass
   ...: 
   ...: 

In [7]: C??
Init signature:
[0mC[0m[1;33m([0m[1;33m)[0m[1;33m[0m[0m

*** ERROR: EOF in multi-line statement


Type:
type
```

### PR DESCRIPTION
**Pull request by Carreau**
closes #9607

### CODE REVIEW

**Comment by takluyver** [comment]
Tests are failing!

**Comment by Carreau** [comment]
Travis is happy. Buuuuut: we have to many newlines in the terminal:

4.2.0:

```
In[2]: nbformat?
Type:         module
String form:  <module 'nbformat' from '/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/nbformat/__init__.py'>
File:         /Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/nbformat/__init__.py
Docstring:
````

vs now 
```
 nbformat?
Type:
module
String form:
<module 'nbformat' from '/Users/bussonniermatthias/anaconda/lib/python3.5/site-packages/nbformat/__init__.py'>
File:
~/anaconda/lib/python3.5/site-packages/nbformat/__init__.py
Docstring:
```

**Comment by Carreau** [comment]
I've reworked the patch to fix the appearance in the terminal. 
I'm unhappy because some things have disapeared:

```
in[1]: list?
Init signature: list(self, /, *args, **kwargs)
Docstring:
list() -> new empty list
list(iterable) -> new list initialized from iterable's items
Type:           type
```

`Init signature` is gone on master.

**Comment by minrk** [comment]
Merging to fix #9607, since #9616 is open to track the remaining issue.

**Pull request merged**
