### PR TITLE
Typescript experiment

### PR DESCRIPTION
**Pull request by jdfreder**
## Do not merge

Using the last commit (573c661) you can compile with `tsc config.ts -t 'ES5' -m amd`.
a00c0fc shows what the file would look like in a complete adoption.

### CODE REVIEW

**Comment by jdfreder** [comment]
@takluyver @minrk @ellisonbg @Carreau

**Comment by jasongrout** [comment]
**Hurray** for the deleted `that`s!

You can also use the standard .d.ts files for jquery and Promises: https://github.com/borisyankov/DefinitelyTyped/tree/master/jquery, https://github.com/borisyankov/DefinitelyTyped/tree/master/es6-promise.  See http://definitelytyped.org/.  Alternatively, you could use tsd like we do: https://www.npmjs.com/package/tsd

**Comment by Carreau** [comment]
For the future, we can use `tsd reinstall -so`, on travis it will need a personal token not to be rate limited by github. We probably want to wrap all the generation in a gulp-watch task also.

**Comment by jdfreder** [comment]
Closing this, since it was just an experiment.

**Pull request closed without merging**
