### PR TITLE
Big Split: nbconvert -> jupyter_nbconvert

### PR DESCRIPTION
**Pull request by minrk**
pending decision on #7595

### CODE REVIEW

**Comment by takluyver** [comment]
Looks fine to me.

**Comment by Carreau** [comment]
+1

**Comment by Carreau** [comment]
Should we open issues fro commented stuff ?

**Comment by takluyver** [comment]
I wouldn't bother - I think it's just part of what we need to do when splitting the repos.

**Comment by Carreau** [comment]
Travis seem happy...

**Comment by Carreau** [comment]
Need rebase.

**Comment by minrk** [comment]
rebased

**Comment by Carreau** [comment]
Merging once travis is happy.

**Pull request merged**
