### PR TITLE
Updates instructions for simple wrapper kernel

### PR DESCRIPTION
**Pull request by bsubei**
I found the instructions lacking in detail (what files to create, where to place them, how to invoke the kernel, etc.). I added changes that I found from the [mailing list](http://mail.scipy.org/pipermail/ipython-dev/2014-July/014453.html).

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! This content has actually moved to the [jupyter/jupyter-client](https://github.com/jupyter/jupyter_client) repo - can you submit a PR there?

The path to put it in has also changed, I'll dig up the docs on where it goes now.

**Comment by basheersubei** [comment]
created pull request in `jupyter-client` repo. Closing this one.

**Comment by takluyver** [comment]
Thanks :)

**Comment by basheersubei** [comment]
my pleasure (this project rocks) :)

**Pull request closed without merging**
