### PR TITLE
Edit mode style

### PR DESCRIPTION
**Pull request by Carreau**
Based on #7382 and adapted as we said, I find it ugly. Alternative is to still keep the strong green border.

capture d ecran 2015-02-05 a 14 40 03
capture d ecran 2015-02-05 a 14 40 08

### CODE REVIEW

**Comment by Carreau** [comment]
Which would like that in edit mode.

capture d ecran 2015-02-05 a 14 42 45

**Comment by minrk** [comment]
@ellisonbg @fperez did we come to a conclusion on this one? It doesn't quite seem like it, so I'm somewhat inclined to leave the style as-is for 3.0.

**Comment by fperez** [comment]
In-person, @Carreau said he truly, positively hated it.

I just tried it, and I don't quite hate it as much, but aesthetically, I don't like it much. I do have to say, it does feel *useful* in terms of really helping you pin down where you're editing. But it's kind of ugly...

With one very negative reaction (@Carreau) and one mildly negative one (me), and being so close to release time, I'm inclined to suggest that we just leave things be where they are now...

**Comment by takluyver** [comment]
Though if we can come up with a style we like, I think it would be fine to backport it to 3.1. Milestoning accordingly.

**Comment by fperez** [comment]
Totally agreed @takluyver

On Tue, Feb 10, 2015 at 4:52 PM, Thomas Kluyver <notifications@github.com>
wrote:

> Though if we can come up with a style we like, I think it would be fine to
> backport it to 3.1. Milestoning accordingly.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7696#issuecomment-73816481>.
>



-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by ellisonbg** [comment]
I think we should just wait.

**Comment by fperez** [comment]
Ok, easy enough then. We all agree, let's wait on this one. Thanks for the
retargetting, Thomas.

On Tue, Feb 10, 2015 at 4:53 PM, Brian E. Granger <notifications@github.com>
wrote:

> I think we should just wait.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7696#issuecomment-73816610>.
>



-- 
Fernando Perez (@fperez_org; http://fperez.org)
fperez.net-at-gmail: mailing lists only (I ignore this when swamped!)
fernando.perez-at-berkeley: contact me here for any direct mail

**Comment by jdfreder** [comment]
I think the inverse would make more sense.  I spend much more time editing a notebook than I do manipulating it in command mode.  Maybe a light gray background with a darker grey border?

**Comment by ellisonbg** [comment]
I am still meh on this. While I think we may want to think more about the design of cells, there is nothing here that feels like it is a clear step forward. Are we OK closing this and thinking on it more?

**Comment by fperez** [comment]
Yup, I'm ok letting it sit for a while. Might as well close for now, I'm sure with more UI/X staffing, we can revisit this with fresh eyes.

In light of the Big Split (TM), +1 to closing.

**Pull request closed without merging**
