### PR TITLE
Better support for KeyboardInterrupt during prompt (continued)

### PR DESCRIPTION
**Pull request by takluyver**
Continuation of #9867, incorporating Jonathan's suggestion to use a finally block.

### CODE REVIEW

**Comment by Carreau** [comment]
I think you can push on PR branch when allow edits from maintainers is checked :-) 

+1, merging once AppVeyor goes green.

**Comment by takluyver** [comment]
I know, but there doesn't seem to be any easy way to see if it's checked on someone else's PR, and this seemed easier than trying to work that out.

**Comment by takluyver** [comment]
Also #9867 was targetting 5.x, which interferes with our system.

**Comment by Carreau** [comment]
Both are good points.
Merging and backporting soon !

**Comment by Carreau** [comment]
@meeseeksdev backport to 5.x

**Pull request merged**
