### PR TITLE
Python 3.10 compatibility

### LINKED ISSUE #13079: Breaking change in Python 3.10rc1
Hello.

There seems to be one more incompatibility in Python 3.10rc1. The problem is in this function: https://github.com/ipython/ipython/blob/770024afeaa5bd66910cf89b9667c4967b65004e/IPython/core/oinspect.py#L287-L319

The call of `inspect.getabsfile(obj.__class__)` on line 313 raises an OSError instead of the expected TypeError. The change in the CPython is here: https://github.com/python/cpython/pull/27495/files

Small reproducer derived from `test_debugger.test_ipdb_magics` is:
```
Python 3.10.0rc1 (default, Aug  3 2021, 00:00:00) [GCC 11.2.1 20210728 (Red Hat 11.2.1-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from IPython.core import debugger
>>> class ExampleClass(object):
...     """Docstring for ExampleClass."""
...     def __init__(self):
...         """Docstring for ExampleClass.__init__"""
...         pass
...     def __str__(self):
...         return "ExampleClass()"
... 
>>> a = ExampleClass()
>>> debugger.Pdb().set_trace()
--Return--
None
> <stdin>(1)<module>()

ipdb> pinfo a
Traceback (most recent call last):
  File "/home/lbalhar/Software/ipython/IPython/core/oinspect.py", line 307, in find_file
    fname = inspect.getabsfile(obj)
  File "/usr/lib64/python3.10/inspect.py", line 844, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/lib64/python3.10/inspect.py", line 817, in getsourcefile
    filename = getfile(object)
  File "/usr/lib64/python3.10/inspect.py", line 797, in getfile
    raise TypeError('module, class, method, function, traceback, frame, or '
TypeError: module, class, method, function, traceback, frame, or code object was expected, got ExampleClass

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib64/python3.10/bdb.py", line 94, in trace_dispatch
    return self.dispatch_return(frame, arg)
  File "/usr/lib64/python3.10/bdb.py", line 153, in dispatch_return
    self.user_return(frame, arg)
  File "/usr/lib64/python3.10/pdb.py", line 294, in user_return
    self.interaction(frame, None)
  File "/home/lbalhar/Software/ipython/IPython/core/debugger.py", line 356, in interaction
    OldPdb.interaction(self, frame, traceback)
  File "/usr/lib64/python3.10/pdb.py", line 357, in interaction
    self._cmdloop()
  File "/usr/lib64/python3.10/pdb.py", line 322, in _cmdloop
    self.cmdloop()
  File "/usr/lib64/python3.10/cmd.py", line 138, in cmdloop
    stop = self.onecmd(line)
  File "/usr/lib64/python3.10/pdb.py", line 422, in onecmd
    return cmd.Cmd.onecmd(self, line)
  File "/usr/lib64/python3.10/cmd.py", line 217, in onecmd
    return func(arg)
  File "/home/lbalhar/Software/ipython/IPython/core/debugger.py", line 778, in do_pinfo
    self.shell.find_line_magic("pinfo")(arg, namespaces=namespaces)
  File "/home/lbalhar/.virtualenvs/ipython/lib/python3.10/site-packages/decorator.py", line 232, in fun
    return caller(func, *(extras + args), **kw)
  File "/home/lbalhar/Software/ipython/IPython/core/magic.py", line 187, in <lambda>
    call = lambda f, *a, **k: f(*a, **k)
  File "/home/lbalhar/Software/ipython/IPython/core/magics/namespace.py", line 58, in pinfo
    self.shell._inspect('pinfo', oname, detail_level=detail_level,
  File "/home/lbalhar/Software/ipython/IPython/core/interactiveshell.py", line 1779, in _inspect
    pmethod(
  File "/home/lbalhar/Software/ipython/IPython/core/oinspect.py", line 680, in pinfo
    info = self._get_info(obj, oname, formatter, info, detail_level)
  File "/home/lbalhar/Software/ipython/IPython/core/oinspect.py", line 586, in _get_info
    info = self._info(obj, oname=oname, info=info, detail_level=detail_level)
  File "/home/lbalhar/Software/ipython/IPython/core/oinspect.py", line 785, in _info
    fname = find_file(obj)
  File "/home/lbalhar/Software/ipython/IPython/core/oinspect.py", line 313, in find_file
    fname = inspect.getabsfile(obj.__class__)
  File "/usr/lib64/python3.10/inspect.py", line 844, in getabsfile
    _filename = getsourcefile(object) or getfile(object)
  File "/usr/lib64/python3.10/inspect.py", line 817, in getsourcefile
    filename = getfile(object)
  File "/usr/lib64/python3.10/inspect.py", line 785, in getfile
    raise OSError('source code not available')
OSError: source code not available
```

I can confirm that the reproducer does not raise the error with Python 3.10b4. An easy fix might be to expect also OSError from the mentioned function. This workaround seems to work for me so I'm gonna open a PR with it.

### PR DESCRIPTION
**Pull request by frenzymadness**
Fixes https://github.com/ipython/ipython/issues/13079

Let's see whether it fixes all the problems or not.

### CODE REVIEW

**Comment by frenzymadness** [comment]
CI is green but I've realized that we don't have Py 3.10 in CI yet so I'm gonna run the tests with the release candidate locally.

**Comment by frenzymadness** [comment]
I'm afraid that there is more than one test failing and it seems that the other failures have something to do with jedi which is not compatible with Python 3.10 yet. Will have to investigate it more.

**Comment by frenzymadness** [comment]
This PR now solves all problems with Python 3.10 I know about. All tests are passing in my local environment with Python 3.10rc1. Also, the full compatibility depends on the similar fix for jedi: https://github.com/davidhalter/jedi/pull/1795

**Comment by bollwyvl** [comment]
Thank you so much, @frenzymadness ! Can you also add a `3.10.0rc1` excursion to [CI](https://github.com/ipython/ipython/blob/master/.github/workflows/test.yml#L10)? It _appears_ these are [now available](https://github.com/actions/python-versions/releases).

**Comment by frenzymadness** [comment]
It seems that the nose is not compatible with Python 3.10. and it's abandoned for quite some time so I don't expect anything. Is there any plan to drop it? We might run pytest first and then iptest/nose. Also, the tests will fail until jedi is fixed.

**Comment by Carreau** [comment]
> It seems that the nose is not compatible with Python 3.10. and it's abandoned for quite some time so I don't expect anything. Is there any plan to drop it?

Yes, I'm currently trying to get some funding from NF to hire someone to do the bulk of the work.

Some modification to ipykernel will be needed too as it import things from IPython that rely on nose.

**Comment by frenzymadness** [comment]
> Some modification to ipykernel will be needed too as it import things from IPython that rely on nose.

I might be able to help with that effort. Could you please tell me more? The ultimate goal is to get rid of the nose entirely and port all the tests to pytest, correct? What is nose used for in runtime?

**Comment by Carreau** [comment]
Most of nose use-case are `nt.assert_equal`, `nt.assert_in` and similar, there are bout 900 of those in the codebase:

```
$ rg -tpy ' nt\.assert_' | wc -l
     926
```

That's the easy part, there are a bunch of utils, like `@skipif(....)`, that are relatively straightforward to migrate to pytest, 
and finally there is all the mess that is in `IPython/testing/iptest.py` and `IPython/testing/` in general that run some IPython specific code (as IPython is itself an interpreter there are some hacks to do).

It's likely portable to pytest, but need some time to actually focus on that.

Good news is the test suite is old (20 years or so), and therefore I think that many of the test are not useful anymore, so if some tests can't be ported and need to be removed, it's ok. Also most of the functionality in iptest can be nuked as it pre-date having CI and was dealing with parallelizing the test and stuff like that. 

I'll open a more specific issue and list all the tasks that need to be done for removing nose a a dependency.

**Comment by Kojoley** [comment]
Thanks for the PR, I incorporated your work in #13282 which got merged.

**Pull request closed without merging**
