### PR TITLE
create new notebook with same kernel

### PR DESCRIPTION
**Pull request by mathieu1**
Here's a quick implementation of the alternative behavior proposed [here](https://github.com/ipython/ipython/issues/7399) : starting with an existing notebook, creating a new notebook will have the _same kernel_ as the existing notebook.

### CODE REVIEW

**Comment by Carreau** [comment]
What about new being a submenu that list the kernels availlable ?
(potentially sorting the current kernel as the first of the submenu))

**Comment by mathieu1** [comment]
There we go. I haven't yet put the current kernel at the top (see technical issue below)
Anyhow, does this look like the way to go? Here's what it looks like : 
newnotebook
-------
Technical issue for putting current kernel at the top of the list : at the moment the menu is created `notebook.kernel` is still `null`, so 
* either the menu has to be created at another moment
* or menu entries have to be rearranged after the kernel is set up
* or maybe there's another way to get the kernel name which i've overlooked

**Comment by dsblank** [comment]
+1 Good idea; this will be useful, regardless of details.

**Comment by mathieu1** [comment]
Ok, I went for the second solution. So the current kernel is at the top of the list.
newnotebook
There's only an embryonic attempt at catching errors (non-existing kernel?), should this be delved into further?

**Comment by Carreau** [comment]
Me se only one thing: Scala and spark kernel.

Error handling would be nice, but I guess we can assume kernel exist if they are listed.

**Comment by mathieu1** [comment]
Fine, I'll leave it like that, there are other things to worry about with missing kernels at the moment anyway.

**Comment by ellisonbg** [comment]
I am +1 on this idea and putting the current kernel at the top of the list.

**Comment by ellisonbg** [comment]
The code looks good and I have tested it. As @Carreau brought up we may have to improve the error handling later, but let's merge this and see how it goes.

**Pull request merged**
