### PR TITLE
Try to fix some of current failures.

### PR DESCRIPTION
**Pull request by Carreau**
See error found in CI below. Hopefully this fixes it.

    ======================================================================
    ERROR: IPython.core.tests.test_magic.test_script_out
    ----------------------------------------------------------------------
    Traceback (most recent call last):
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/nose/case.py", line 198, in runTest
        self.test(*self.arg)
      File "/home/runner/work/ipython/ipython/IPython/testing/decorators.py", line 223, in skipper_func
        return f(*args, **kwargs)
      File "/home/runner/work/ipython/ipython/IPython/core/tests/test_magic.py", line 953, in test_script_out
        ip.run_cell_magic("script", "--out output sh", "echo 'hi'")
      File "/home/runner/work/ipython/ipython/IPython/core/interactiveshell.py", line 2417, in run_cell_magic
        result = fn(*args, **kwargs)
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/site-packages/decorator.py", line 232, in fun
        return caller(func, *(extras + args), **kw)
      File "/home/runner/work/ipython/ipython/IPython/core/magic.py", line 187, in <lambda>
        call = lambda f, *a, **k: f(*a, **k)
      File "/home/runner/work/ipython/ipython/IPython/core/magics/script.py", line 216, in shebang
        stdin=asyncio.subprocess.PIPE,
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 587, in run_until_complete
        return future.result()
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/subprocess.py", line 217, in create_subprocess_exec
        stderr=stderr, **kwds)
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/base_events.py", line 1544, in subprocess_exec
        bufsize, **kwargs)
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/unix_events.py", line 193, in _make_subprocess_transport
        self._child_watcher_callback, transp)
      File "/opt/hostedtoolcache/Python/3.7.12/x64/lib/python3.7/asyncio/unix_events.py", line 941, in add_child_handler
        "Cannot add child handler, "
    RuntimeError: Cannot add child handler, the child watcher does not have a loop attached

### CODE REVIEW

**Comment by takluyver** [comment]
Seems like appveyor failed on some network issue, and then other tests got cancelled. Closing/reopening to try again.

**Comment by takluyver** [comment]
Ah, no, I follow. The appveyor failure was unrelated, and the Github actions jobs were cancelled because they timed out. I'll try adding the `-v` flag, which should help narrow down which test is getting stuck.

**Comment by takluyver** [comment]
It passes `test_script_out` in `test_magic.py`, so it's hanging either on `test_script_err` or between the two tests. :confused: This is one of the tests you added the `skip_iptest_but_not_pytest` decorator to.

**Comment by Carreau** [comment]
Thanks, I've done a complete rework, by making sure the childwatcher are stopped and removed from the current loop, and thus that the loop should not be running at the end of the magic. That seem to work locally, if that does i'll rebase to cleanup the code.

**Comment by Carreau** [comment]
Ok, all good.

**Comment by Carreau** [comment]
Windows seem un hapy with the order of skip decorators.

**Pull request merged**
