### PR TITLE
Don't catch failure to import Jedi

### PR DESCRIPTION
**Pull request by takluyver**
Jedi is a dependency now - if it isn't installed, we should fail clearly rather than silently skipping completions.

### CODE REVIEW

**Comment by takluyver** [comment]
I also discarded the `use_jedi_completions` configurable - I think previously this was used to switch between jedi completions and our built in completions. But now it switches between jedi completions and nothing, which doesn't seem very useful.

**Comment by Carreau** [comment]
I'm thinking of reverting the jedi stuff, there are many completions that are wrong now.

**Comment by takluyver** [comment]
I'll try to spend some time figuring out what's going wrong. Working out that I didn't have Jedi installed on this machine was a first step. ;-)

**Comment by Carreau** [comment]
Ok, fair enough, I think the real need is to update IPython's completion API. Which I don't want to do for 5.0. I would prefer to revert jedi for 2 month, get 5.0 out, and work on 6.0.  A change of API is too risky for a LTS.

**Pull request merged**
