### PR TITLE
remove profiles from IPython.config

### PR DESCRIPTION
**Pull request by minrk**
in preparation for The Big Split™

profile-aware bits are moved to IPython subclasses.

In addtion, the default profiles in `IPython.config.profile` are removed, and `get_config` is made obsolete (but left as-is) by injecting `c` into the config file namespace.

### CODE REVIEW

**Comment by Carreau** [comment]
> Running setup.py install for ipython
>    /home/travis/virtualenv/python3.4.2/lib/python3.4/site-packages/setuptools/dist.py:283: UserWarning: >The version specified requires normalization, consider using '4.0.0.dev0' instead of '4.0.0-dev'.

Should we ?

On py2

```
ipython/setupbase.py", line 219, in check_package_data
        assert len(glob(path)) > 0, "No files match pattern %s" % path
    AssertionError: No files match pattern IPython/qt/console/resources/icon/*.svg
```

**Comment by minrk** [comment]
@Carreau the warning is gone in current setuptools

**Comment by Carreau** [comment]
+1

**Comment by Carreau** [comment]
Let's break all the things. Merging.

**Pull request merged**
