### PR TITLE
adding snake case auto complete for #9420

### PR DESCRIPTION
**Pull request by sagnak**
see #9420

### CODE REVIEW

**Comment by Carreau** [comment]
Hi @sagnak , your git config email seem to not match your github set email, so you won't get the attributions for this commit. 

Do you want to append the author ? 

Also you can reference issues only be there numbers, and if you put them in the core of the commit message (that is not the first or second line) they will auto link on GitHub. Do you want to try to ammend your commit to fix this ?

**Comment by sagnak** [comment]
Hey, I fixed the commit history to reflect the username and email, but I do not follow where the core is, and what I should note there.

**Comment by takluyver** [comment]
Links in the pull request title don't work,  but you can easily link to an issue in the main description of a pull request by writing a number like this: #9420.

**Comment by Carreau** [comment]
Thanks ! Perfect !

**Pull request merged**
