### PR TITLE
fix input_splitter error after KeyboardInterrupt with in --simple-prompt mode (issue #11475)

### PR DESCRIPTION
**Pull request by liushapku**
addresses [issue 11475](https://github.com/ipython/ipython/issues/11475)

### CODE REVIEW

**Comment by liushapku** [comment]
have no idea why the integration for python 3.3 failed.

**Comment by Carreau** [comment]
The failure  on Python 3 is unrelated. It's just that the new version of Pip is incompatible with Python 3.

I'm happy to get that in, but there will likely not be any further release of IPython 6.x. Do you have any specific reason to want to fix 6.x ?

**Comment by liushapku** [comment]
It is just because our team uses a specific `conda` environment which stick to 6.x. It might take time to migrate to 7. Is there any compatibility issue between 6 and 7? What is the major difference between 6 and 7?

**Comment by liushapku** [comment]
If there is no further release, how can you get it in? Should we just ignore all these and use 7?

**Comment by Carreau** [comment]
For all the difference between 6.x and 7.x see [the what's new](https://ipython.readthedocs.io/en/stable/whatsnew/version7.html). 

There is no major compatibility issue if you don't use custom extensions. 

I'm happy to get the fix in the 6.x branch, but it's likely never going to end up on PyPI or Conda. 
You can still install source from a specific commit if that helps. (That is unless there is interest for someone to maintain 6.x, but the current core dev are doing that on their free time and already plenty to do).

But in general yes as an open source project we only support the latest branch (in this case 7.x) and use the latest unless you you really need to stick to an old one. If you need support for an old version you can also discuss support with Anaconda Inc.

**Comment by liushapku** [comment]
That's fairly reasonable. Thanks for having created such a superb software that having benefitted the whole community.

**Comment by Carreau** [comment]
Many thanks for your contribution. I'm going to close this as it is likely to never be released. Still looking forward to more PR coming from you.

**Pull request closed without merging**
