### PR TITLE
Enable autosuggestion from history

### PR DESCRIPTION
**Pull request by mskar**
Autosuggestion is a very useful feature available in fish, zsh, and prompt-toolkit.
Ptpython allows users to enable this feature in [`ptpython/config.py`](https://github.com/prompt-toolkit/ptpython/blob/master/examples/ptpython_config/config.py#L90).

This feature allows users to accept autosuggestions with ctrl e, ctrl f, or right arrow as described below.

1. Start ipython
image
2. Run `print("hello")`
image
3. Press p to see the autosuggestion
image
4. Press ctrl f, or ctrl e, or right arrow to accept the suggestion
image

You can also complete word by word:
1. Run `def say_hello(): print("hello")`
image
2. Press d to see the autosuggestion
image
3. Press alt f to accept to accept the first word of the suggestion
image

This feature does not interfere with tab completion:
1. After running `def say_hello(): print("hello")`, press d
image
2. Press Tab to start tab completion 
image
3A. Press Tab again to select the first option 
image
3B. Press alt f to accept to accept the first word of the suggestion
image
3C. Press ctrl f or ctrl e to accept the entire suggestion
image

To install a version of ipython with autosuggestions enabled, run:

`pip install git+https://github.com/mskar/ipython@auto_suggest`

Autosuggestions only work in the emacs or vi insert editing modes.
To use autosuggestions in vi insert mode, I created some [custom keybindings](https://github.com/mskar/setup/commit/2892fcee46f9f80ef7788f0749edc99daccc52f4/).

### CODE REVIEW

**Comment by Carreau** [comment]
Oh, that is nice.
Do you want to add some of this description into `docs/source/pr/afilename` ? That will get included in the release notes on next release.

**Comment by mskar** [comment]
@Carreau, that sounds great, but I couldn't find `docs/source/pr/`.
Do you mean [`docs/source/whatsnew/pr`](https://github.com/ipython/ipython/tree/master/docs/source/whatsnew/pr)?
I see a few rst files there that I can use as examples.
Is that the right place? If so, I will add `docs/source/whatsnew/pr/auto_suggest.rst` to the pull request.

**Comment by Carreau** [comment]
Yes, that's the place, you are right. Sorry for misleading you with the wrong location.

**Comment by mskar** [comment]
@Carreau, I added [`docs/source/whatsnew/pr`](https://github.com/mskar/ipython/tree/auto_suggest/docs/source/whatsnew/pr) with markdown and rst files.
I think you only need the rst file:  [`docs/source/whatsnew/pr/auto_suggest.rst`](https://github.com/mskar/ipython/tree/auto_suggest/docs/source/whatsnew/pr), but created the rst from the md file using pandoc, so I decided to add the markdown file as well.

**Comment by Carreau** [comment]
It's perfect. 

I'll do some tweaking later (need some reformatign for test to pass), and will edit most of those files at release time to consolidate them.

**Comment by mskar** [comment]
Great, thanks so much, @Carreau!
If there's anything I can do to help, please let me know!

**Comment by Carreau** [comment]
I made the image part of the repository not to have to deal with external resources as some people build the docs on internal air-gapped network, and fix some typo. 

If seem like the image for step 2 and 3 are the same, image for 3 is likely incorrect ? 

Once test pass (docs making sure it build and all resources are in the repo) I can merge, and we can refine.

**Comment by zimmermann6** [comment]
Hi, I really love that feature! A HUGE thank you for adding it in Sage. It saves me a LOT of time.

**Pull request merged**
