### PR TITLE
Upgrade to python 3.5+ syntax, add autoformat

### PR DESCRIPTION
**Pull request by alok**
Addresses #11749. If autoformat (done with `black`) is not desired, I can remove
that.

If it *is* desired, then I still need to add it to Travis to enforce that people
use it. One issue is that it requires 3.6+ to run.

### CODE REVIEW

**Comment by LucianaMarques** [comment]
Hi @alok ! My latest PR changed the optestcontroller.py file, so you probably need to rebase your local repository.

**Comment by Carreau** [comment]
Thanks ! I'll try to have a look when I can !

> I can remove that.

Well we'd love to enforce black, but we don't want to modify all the files at once as it would break some things like `git blame`; see among other [this discussion](https://github.com/python/black/issues/830) and [this thread on twitter](https://twitter.com/F_Vaggi/status/1133425252992557056); if you don't mind removing/rebasing that would be great.

**Comment by alok** [comment]
@Carreau I rebased. Though if you wouldn't mind updating the tests, that would be nice since I have no idea what the mini-language for test case formatting is.

**Comment by Carreau** [comment]
> since I have no idea what the mini-language for test case formatting is.

Not quite sure what mini language you are referring to. 
Also in #11749 I was referring to actuall checking of Python version like [here](https://github.com/ipython/ipython/blob/a9a72474c49d9c0a90ace5ee332ddd9d490b1a98/IPython/core/interactiveshell.py#L2261), [here](https://github.com/ipython/ipython/blob/a9a72474c49d9c0a90ace5ee332ddd9d490b1a98/IPython/core/interactiveshell.py#L2261) ,

Ss this touch ~150 files, I might end up integrating it in multiple step. Did you use a script or changed all by hand ?

**Comment by alok** [comment]
Nevermind, it was an issue that came up with `black`.

I just ran `pyupgrade --py3-plus **.py`. That was it.

**Comment by drunkwcodes** [comment]
This PR may really break python2.7 compatibility in `master` such as string prefix u deletion.
Would you like to add a warning for python2 users pinning the version to 5?

And it is better to remain [PEP461](https://www.python.org/dev/peps/pep-0461/) string formatting unchanged for the target python version is 3.5.

**Comment by alok** [comment]
@drunkwcodes I'm not going to do any of that. 2.7 support has been dropped since 6.0, which came out 2 years ago.

**Comment by drunkwcodes** [comment]
@alok Fine. But [PEP461 formatting?](https://www.python.org/dev/peps/pep-0461/)

**Comment by alok** [comment]
What is that

**Comment by drunkwcodes** [comment]
@alok That is the proof of unnecessity about the change of string formatting.
Reverting those changes and `u` prefix deletion makes this PR less possible to be rejected.

**Pull request closed without merging**
