### PR TITLE
corrected split with rsplit

### PR DESCRIPTION
**Pull request by ghost**
sir, @Carreau i changed the split with rsplit, i did it because with split only the first that is splitted from the string is taken, but with rsplit the last string is taken, which is what we want. please verify sir.

### CODE REVIEW

**Comment by Carreau** [comment]
Great !
That seem to be a good fix !

I'll let some time to other dev to have a look. 

A few comments on how to make your contribution even better for subsequent fixes.

It's not easy here, but sometime we try to come up with a unit-test to make sure it does not break later.
One way we could do that here, is to refactor the following:

```
          if breakpoint:
             (filename, bp_line) = breakpoint.rsplit(':', 1)
              bp_line = int(bp_line)
          else:
              (filename, bp_line) = (None, None)
```

into a function, for example `_get_filename_and_line`, use it, and test it. 
Up to you if you like to try do that. 

Here it's a pretty some simple fix so there is no need to but you can also add an `rst` file into `docs/source/whatsnew/pr/` folder that will end-up in the what's new notes. 

 That was some tips to make your code even better and how we could have done it. 

A GitHub tip as well. 

When you make your message commit you can use the phrase `Fixes #9932` for example. 
That will automatically link your pull request with the target issue, and when your fix is merged the issue will be automatically closed !

And last improvement you can try next time when writing your commit message, 

Try to describe _why_ you do some changes instead of which changes you are doing. This is extremely useful when trying to understand code or why a bug appear in some line a few month or years later. In particular here with the diff it is pretty easy to see you changed `split` to `rsplit`, a better commit message might be:

> Fix breakpoint linenumber detection on Windows.
>  
> Change `split` to `rsplit` as windows paths can contain `:` when including drive letters. 

This should close  #9932, @jlumpe you reported the issue would that suit you ?

Thanks !

**Comment by jlumpe** [comment]
Looks like this should fix it!

**Comment by thesageinpilani** [comment]
@Carreau , sir i will remember this points and apply them when contributing.

**Comment by Carreau** [comment]
> i will remember this points and apply them when contributing.

Thanks;  those are advice; it often takes years to completely internalize these, and apply them. 
You can see it mostly as guidelines. 

Thanks a lot for your contributions, it is really important for you to like contributing and enjoy participating.

**Comment by thesageinpilani** [comment]
sir, i really do enjoy participating and contributing and i am learning a lot contributing, I am very grateful for your support and for your guidance all this time.

**Comment by Carreau** [comment]
Thanks ! Merged.

**Pull request merged**
