### PR TITLE
Get more information if issue setting color scheme

### PR DESCRIPTION
**Pull request by Carreau**
Mainly for debugging purpose, use for rebase/rework of pr 8966

### CODE REVIEW

**Comment by takluyver** [comment]
Doesn't exception chaining show you the earlier traceback automatically?

**Comment by Carreau** [comment]
> Doesn't exception chaining show you the earlier traceback automatically?

Is that a question to ask if I'm ok dropping Python 2 ? (you know the answer), Or is there a simple way to re-raise in Legacy Python that I don't remember ?

**Comment by takluyver** [comment]
Generally I'd put debugging code in temporarily and not make a pull request with it. Especially so when it's only needed on Legacy Python. So I'm a bit confused about what this PR is for!

**Comment by Carreau** [comment]
Ok, I'll close that and only use it locally.

**Pull request closed without merging**
