### PR TITLE
Quick hack to make tb highlighting configurable.

### PR DESCRIPTION
**Pull request by Carreau**
For example put

    from IPython.core.ultratb import VerboseTB
    VerboseTB._tb_highlight = "bg:#039dfc"

In your ipython_config.py

Mitigate #13446 and #13486

### CODE REVIEW

**Comment by Carreau** [comment]
Note that this is only. A stop-gap as Python 3.11 is introducing traceback annotations, and also now annotate nodes (but underline them), so the code that does all this may need to be re-written. 

Python exception now also have exception groups, and annotations, so it might be quite a bit of work, and I'd love for someone to find the time to do so, it is jus likely not going to be me.

**Comment by Carreau** [comment]
@meeseeksdev tag "help wanted"

**Comment by simon-ging** [comment]
Note that the variable was renamed from `_tb_highlight` to `tb_highlight`, so the fix now must update the new variable, e.g.:

`from IPython.core import ultratb;ultratb.VerboseTB.tb_highlight = 'bg:ansired';`

**Comment by ili3p** [comment]
The file is in:
` ~/.ipython/profile_default/startup/ipython_config.py`

**Pull request merged**
