### PR TITLE
Fix read-only file test causing errors on Windows

### PR DESCRIPTION
**Pull request by takluyver**
Will run Windows tests against this.

### CODE REVIEW

**Comment by takluyver** [comment]
No, that didn't seem to fix it.

**Comment by minrk** [comment]
Oh, crazy, that's definitely not the commit I meant to push.

**Comment by minrk** [comment]
wait, this isn't my PR, duh. I just skipped the test in #7906.

**Comment by minrk** [comment]
Also for the record, the test passes just fine on my Windows 7 VM, so it might be something related to the Windows Server VM on Jenkins running as admin.

**Comment by takluyver** [comment]
It's like that paradox about whether an omnipotent deity can create a weight that he cannot lift...

Closing in favour of #7906

**Pull request closed without merging**
