### PR TITLE
Small fix: Bang should be after the assignment operator

### PR DESCRIPTION
**Pull request by erenhalici**

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! We normally put it after the space as well, `= !ls` so it's clear that it's separate from the equals sign.

**Comment by erenhalici** [comment]
You're welcome. Makes sense. If you want I can update the documentation accordingly.

**Comment by takluyver** [comment]
Yup, go ahead and update that line, and any other examples you spot.

**Comment by erenhalici** [comment]
Done :)

**Comment by takluyver** [comment]
Thanks!

@meeseeksdev backport

**Pull request merged**
