### PR TITLE
Confirm save if notebook changed

### LINKED ISSUE #6750: Confirm before overwriting notebook file when on-disk file has changed
Currently, it seems that when a save is requested by the notebook, it blindly overwrites the current version on disk, which can cause all sorts of pain if the notebook happens to be open by two different browser tabs or windows.

@minrk suggested that the notebook be aware of the last modified time of the file, and before saving, the notebook asks what the last modified time on the file is.  If the file has been modified since we knew about it, confirm with the user that we really do want to overwrite the file.  +1 to Min's suggestion.

### PR DESCRIPTION
**Pull request by minrk**
This is one commit on top of #7575, adding a check for whether the file has changed since last saved. It does so by performing an extra GET with `content=False`, only fetching metadata about the file, to see if last_modified has changed since we last saved. If it has, you see this dialog, asking to confirm the overwrite:

screen shot 2015-01-24 at 13 13 46

closes #6750

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, using google drive, we wouldn't use `last_modified` but a `revisionId`, would there be a way to delegate that to a methods of `contents.js` ?

**Comment by minrk** [comment]
I was thinking about that, but I couldn't see a good way to do it with the dialog. last_modified is a required part of the model, does Drive not provide that?

**Comment by Carreau** [comment]
just make the `last_modified > that.last_modified` a call `content.has_changed` or alike ? I'll have a look.

**Comment by Carreau** [comment]
Technically we do need that also in the editor, where things could have changed. 
So I would be for an abstract methods in contents.js that return an arbitrary `version` blob (or whatever) 
and has an abstract methods `has_changed_since(blob)` that return a boolean. 

@kestertong did that on [jupyterdrive](https://github.com/jupyter/jupyter-drive/blob/master/jupyterdrive/gdrive/drive-contents.js#L39-L51) without leaving contents manager and it works (except for some drive bug).

So +1 on behavior, -1 on location/abstraction.

**Comment by minrk** [comment]
Does Drive have no dates available for anything? I don't like the idea of adding a black-box revision to the contents service.

**Comment by minrk** [comment]
Looking at the [jupyter-drive code](https://github.com/jupyter/jupyter-drive/blob/bedd83900b61b38239b90710f5cf6b6c62c7643e/jupyterdrive/gdrive/drive-contents.js#L85), last_modified is populated, so it seems like this should work correctly on Drive without any changes.

**Comment by minrk** [comment]
I'm also totally fine holding this until after 3.0, if there's more implementation discussion to be had. But since last_modified is a non-optional part of the contents model, I think it should work without adding unnecessary abstraction.

**Comment by KesterTong** [comment]
Yes, ```last_modified``` would also work.  Right now we are suffering from a recent change in Drive behavior (probably fair to call it a bug) where the values we get back after saving don't reflect the save that was just done.  So we aren't actually populating ```last_modified``` correctly.  But we also aren't getting correct values for ```revisionId``` either.  I will file a bug about this with the Drive team and hopefully at least find out what is going on.

**Comment by Carreau** [comment]
Let's try with date then, and refactor later if needed.

**Comment by ebenolson** [comment]
Combined with the autosave behaviour, if you leave a window open with this warning for a few hours, you come back to a black page from dozens of overlaid modal dialogs.

**Pull request merged**
