### PR TITLE
Support multiline input in --simple-prompt 

### LINKED ISSUE #9816: Add multiline coding in ipython 5 with --simple-prompt
As emacs user I often use emacs repl with **ipython**, but after update to **ipython 5** I need to use `--simple-prompt` flag for my work. But when I try to create new def or class I get this error message

``` python
In [1]: def new():
  File "<ipython-input-1-ce93a60072ff>", line 1
    def new():
              ^
SyntaxError: unexpected EOF while parsing
```

### PR DESCRIPTION
**Pull request by infinity0**
fixes: #9816

### CODE REVIEW

**Comment by infinity0** [comment]
Actually, ideally I would take the prompt_text and prompt_continuation from the underlying application config - if I change them to `sage: ` and `....: ` respectively, then the cantor sage backend *does* work with sage 7.6 / ipython 5.

**Comment by infinity0** [comment]
Some help fixing the tests would be appreciated, but at least my own cantor-sage-backend works now with this patch applied to IPython (plus a corresponding patch in sagemath to force `simple_prompt` when called by Cantor).

**Comment by Carreau** [comment]
Have you tried to use [rlipython](https://github.com/ipython/rlipython) ? This allow IPython to reuse readline as a frontend, and should and you will not need to wait for a new release of IPython.

**Comment by Carreau** [comment]
So it seem you miss-committed, as the only missing thing was an import of cast_unicode_py2. Which is unnecessary as IPython 6 is Python 3 only, but that will make backport easier.

**Comment by infinity0** [comment]
Oh right, thanks! Yes I had been testing this against 5.1.0 from Debian, and didn't notice the import had been removed from git master.

I'll let the Sage developers know about rlipython. It would be good to have this patch in IPython as well though, so that multiline input works even if not using rlipython. And it's easier for me to backport stuff to Debian after it's been accepted upstream, rather than waiting for Sage to add a new feature.

**Comment by Carreau** [comment]
ok, let's get that one in and backport.

**Comment by Carreau** [comment]
@meeseeksdev backport

**Comment by infinity0** [comment]
Hm, unfortunately this breaks a lot of doctests in Sage. I'll investigate and try to fix...

**Comment by infinity0** [comment]
That is because sage expects the prompt to be "In [0]" but I changed it with this commit... should be quite simple to fix.

**Comment by infinity0** [comment]
OK, confirmed I can un-break the Sage doctests with a 1-line fix, there is no need to further patch IPython.

**Pull request merged**
