### PR TITLE
fix the pager and tooltip locations

### PR DESCRIPTION
**Pull request by minrk**
- pager was confused, pull it outside `#site`
- tooltip's position is preserved during scroll

ping @jdfreder (again, sorry for ruining everything)

### CODE REVIEW

**Comment by Carreau** [comment]
Tooltip was not scolling with page, so nothing you ruinned: -)

**Comment by Carreau** [comment]
+1

**Comment by takluyver** [comment]
@jhamrick and I are still seeing tooltip positioning issues with this branch. @minrk is working on a fix.

**Comment by minrk** [comment]
tooltip location should be better behaved, now.

**Comment by jdfreder** [comment]
Reviewing...

**Comment by jhamrick** [comment]
Seems to be working for me now!

**Comment by jdfreder** [comment]
Code looks good too, and works for me also.

**Comment by takluyver** [comment]
Working for me too. Will merge once Travis finishes..oh, it just did.

**Pull request merged**
