### PR TITLE
Try to fix Pytest error on Python 3.13

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Review by ivanov — APPROVED** [review]
ZOMG! it passes! :cake:

**Comment by Carreau** [comment]
Thanks @ivanov , you should feel free to merge, I belive you still have commit rights ! ❤️

**Comment by ivanov** [comment]
@Carreau indeed I do, but I forget if we're a self-merge kind of project here, or not.

**Comment by Carreau** [comment]
> @Carreau indeed I do, but I forget if we're a self-merge kind of project here, or not.

We we are not supposed to be a self-merge, but as in practice I appear to be the last active maintainer left, I end up self-merging.

**Pull request merged**
