### PR TITLE
Fix signature for IPython.core.display:Pretty #10595

### PR DESCRIPTION
**Pull request by rtilk89**
See #10595

### CODE REVIEW

**Comment by kr1m** [comment]
Sorry for the spam - made a tiny git mistake :)

**Comment by Carreau** [comment]
Sweet, thanks ! You did indeed messed up the git history a bit (likely rebasing ?) do you want to attempt to fix that ? Otherwise I can do it.

**Comment by kr1m** [comment]
@Carreau I think I messed the history up even more. Would you mind cleaning it up in the merge?
I will be more careful with my rebase next time!

**Comment by Carreau** [comment]
Ok, I think I got the rebase right, and you should appear as the Author and Committer  of the last commit.

**Comment by kr1m** [comment]
Yeah I think that worked. Sorry about the churn!

**Comment by takluyver** [comment]
This appears to be changing what the `Pretty` object does. Generally, I think the idea with these core display objects is to act as wrappers for pre-formatted content, so you can load some data from a file or something and display it. I think we should keep the core object not manipulating its data at all, and add a new object if we want to do the text wrapping thing.

**Comment by kr1m** [comment]
@takluyver - how can I test what the Pretty object is doing? 

I was playing around with it in the following way: 
`from IPython.core.display import Pretty

p = Pretty(<Some long string>)
`
Should it have a simple print function like the documentation at the top of IPython.lib.pretty?

**Comment by Carreau** [comment]
Hum, I missed that but @takluyver is right, None of the object in `display.py` are trying to be smart.

But, if Pretty is just a pass-through, I also don't really see the benefit of the PrettyObject,as it would not be much different from a plain object with a `__repr__`

Wrapping text is a nice default, though I would use `textwrap.textwrap` that have a slighly better implementation  (yours seem to keep leading spaces:-) )

```
In [3]: lorem ="""Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printe
   ...: r took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unch
   ...: anged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker inclu
   ...: ding versions of Lorem Ipsum"""

In [4]: lorem
Out[4]: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum"

In [5]: Pretty(lorem)
Out[5]:
Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem
 Ipsum has been the industry's standard dummy text ever since the 1500s, when an
 unknown printer took a galley of type and scrambled it to make a type specimen
 book. It has survived not only five centuries, but also the leap into
 electronic typesetting, remaining essentially unchanged. It was popularised in
 the 1960s with the release of Letraset sheets containing Lorem Ipsum passages,
 and more recently with desktop publishing software like Aldus PageMaker
 including versions of Lorem Ipsum

In [7]: import textwrap

In [9]: print('\n'.join(textwrap.wrap(lorem)))
Lorem Ipsum is simply dummy text of the printing and typesetting
industry. Lorem Ipsum has been the industry's standard dummy text ever
since the 1500s, when an unknown printer took a galley of type and
scrambled it to make a type specimen book. It has survived not only
five centuries, but also the leap into electronic typesetting,
remaining essentially unchanged. It was popularised in the 1960s with
the release of Letraset sheets containing Lorem Ipsum passages, and
more recently with desktop publishing software like Aldus PageMaker
including versions of Lorem Ipsum
```

**Comment by takluyver** [comment]
@kr1m I would do that and then call `IPython.display.display(p)`. But I don't think it's meant to be doing anything clever.

@Carreau 
> But, if Pretty is just a pass-through, I also don't really see the benefit of the PrettyObject

It still has the functionality for loading data from a file or a URL, and it's there for parity with the other raw display objects, like `HTML()` or `Markdown()`.

**Pull request closed without merging**
