### PR TITLE
Use prompt_toolkit.application.create_app_session for debugger prompt

### LINKED ISSUE #12192: Infinite loop when using ipdb on ipython 7.13+
I use pytest with appium and when I use ipdb.set_trace() I'm stuck in a loop:

```
Exception in thread Thread-21249:
Traceback (most recent call last):
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 926, in _bootstrap_inner
    self.run()
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/Users/vverdeil/workspace/venv/testenv/lib/python3.7/site-packages/IPython/terminal/debugger.py", line 102, in in_thread
    line = self.pt_app.prompt()
  File "/Users/vverdeil/workspace/venv/testenv/lib/python3.7/site-packages/prompt_toolkit/shortcuts/prompt.py", line 986, in prompt
    return self.app.run()
  File "/Users/vverdeil/workspace/venv/testenv/lib/python3.7/site-packages/prompt_toolkit/application/application.py", line 788, in run
    return get_event_loop().run_until_complete(self.run_async(pre_run=pre_run))
  File "/usr/local/Cellar/python/3.7.6_1/Frameworks/Python.framework/Versions/3.7/lib/python3.7/asyncio/events.py", line 644, in get_event_loop
    % threading.current_thread().name)
RuntimeError: There is no current event loop in thread 'Thread-21249'.
```

As you can see I reached thread 21249 before managing to kill the process.

With the same code it works as expected on ipython 7.12, so I guess is it linked to https://github.com/ipython/ipython/pull/12141/

Am I the only one having this bug?

### PR DESCRIPTION
**Pull request by kmaork**
Running the debugger prompt in the default `prompt_toolkit` session causes issues when more than one prompt_toolkit app is running simultaneously. I'm encountering this while trying to debug multiple threads using [madbg](https://github.com/kmaork/madbg). The errors look exactly like those mentioned in #12192. This commit solves this by using the dedicated API from prompt_toolkit.

BTW, this PR combined with #13311 should be enough to close #12192.

### CODE REVIEW

**Comment by Carreau** [comment]
Thanks, would it be worth it to also create on in `IPython/terminal/interactiveshell.py`?
And, does it make sens to keep the session around and reuse it in cmdloop?

**Comment by kmaork** [comment]
> would it be worth it to also create on in `IPython/terminal/interactiveshell.py`?

If we want to allow multiple IPython instances to run concurrently in threads, then yes. When researching this bug, I remember finding some old issues with `IPython` being run in threads inside `scrapy`, but can find it now so maybe it was unrelated.

> does it make sens to keep the session around and reuse it in cmdloop?

It is not necessary functionality-wise. Performance-wise, looking at the [source code](https://github.com/prompt-toolkit/python-prompt-toolkit/blob/master/src/prompt_toolkit/application/current.py#L143), creating the session is very lightweight, and applying it uses the "private" `_current_app_session`, so I wouldn't do something like that anyway.

**Comment by kmaork** [comment]
Hey @Carreau, can you please rereview?

**Comment by Carreau** [comment]
Apologies for the delay. Let's try it.

**Pull request merged**
