### PR TITLE
update to component (CodeMirror 4.13)

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by Carreau** [comment]
Tested a bit. don't see any bug.

**Comment by minrk** [comment]
4.0?

**Comment by Carreau** [comment]
50/50. 

I don't see any reason to make it 3.1 nor any reason not to make it 3.1

**Comment by minrk** [comment]
Are there known bugs fixed by this? I think updating codemirror in 3.x is fine, but since it's been known to introduce regressions in the past, I'd only backport it if we know it fixes bugs that affect IPython users.

**Comment by Carreau** [comment]
Had a quicklook at changes, and none seem noticible. Maybe a few Scroll issues, but not sure they affect us. Marking 4.0

**Pull request merged**
