### PR TITLE
Enable webagg in %matplotlib magic

### LINKED ISSUE #13777: Enable webagg in %matplotlib magic
It seems somehow `%matplotlib webagg` no longer works. 

```
File ipy/lib/python3.10/site-packages/IPython/core/pylabtools.py:321, in find_gui_and_backend(gui, gui_select)
    317 import matplotlib
    319 if gui and gui != 'auto':
    320     # select backend based on requested gui
--> 321     backend = backends[gui]
    322     if gui == 'agg':
    323         gui = None

KeyError: 'webagg'
```

Could we add webagg backend for selection? It needs just adding the key to the dictionary `backends` in `pylabtools.py`.

### PR DESCRIPTION
**Pull request by ghost**
This PR enables `%matplotlib webagg` magic in IPython console. After these two simple changes webagg will be supported.

Fixes #13777

### CODE REVIEW

**Comment by zhizheng1** [comment]
Fixes #13777

**Comment by zhizheng1** [comment]
Could someone please take a look at this PR? It's quite straightforward.

**Comment by Carreau** [comment]
I've approved the test suite, and will mereg once it passes.

**Comment by zhizheng1** [comment]
I accidentally updated the branch by merging the main into it; could you approve the test again.. I noticed some formatting failures in the previous run. Would it matter?

**Comment by zhizheng1** [comment]
Did a cosmetic fix for formatting checks. Could someone please take a look or approve the tests?

**Comment by zhizheng1** [comment]
> Thanks for your patience, some is usually me, and the last 3/4 weeks have been a bit complicated.

Thanks for taking care of this, are you able to approve this too? It's needed in an ipykernel:
https://github.com/ipython/ipykernel/pull/1012

**Pull request merged**
