### PR TITLE
Remove always skipped test.

### LINKED ISSUE #13219: Remove always skipped test.
in #13206 there is a test that seem to always be skipped. Once merged we could delete it.

_Originally posted by @Carreau in https://github.com/ipython/ipython/pull/13206#r733237961_

### PR DESCRIPTION
**Pull request by GalBr**
This pull request closes #13219.

This is my first ever open source pull request, so let me know if I missed something I needed to do.

### CODE REVIEW

**Comment by Carreau** [comment]
Hello ! Thanks for your pull request, you did great !

There was another conflicting pull-request merged since you submitted your, so it was conflicting but I fixed it. 

I'm going to merge this, but just before I want to make sure of one thing: the email you use in the commits is not the same as the one you use for github, so github does not see the commits as "yours". If you want the commit to be properly associated with you you need to :

 - Either rewrite your commit to use another email 
 - Ok (more likely), list the mail you used in your github settings so it can associate with you.

Let me know and I can help you with 1), or that you have updated your emails and I'll merge.

**Comment by GalBr** [comment]
Hey, thank you!
I created a new email for GitHub commits to avoid getting my main one scrapped. Forgot to add it to my emails list. Took care of it just now!
Thanks for the heads-up!

**Comment by Carreau** [comment]
> I created a new email for GitHub commits to avoid getting my main one scrapped.

That's what I figured reading the mail :-) , it's important to have proper contributions ! Congrats on your first successful contribution ! Looking forward to get more from you. 

This will only be part of the the IPython 8.0 release that is coming likely in Dec/January, but you can celebrate now. 
Let us know if you have any question with respect to how to use git/github or anything else

**Comment by GalBr** [comment]
@Carreau Thank you so much!
I'm quite good with git but I don't have a lot of experience with GitHub. We use Jira + bitbucket at work, at the workflow seems to be a bit different here.
My only question for now is what is the best way to get into the IPython codebase? There's a lot of stuff going on here.

**Comment by Carreau** [comment]
> I'm quite good with git but I don't have a lot of experience with GitHub. We use Jira + bitbucket at work, at the workflow seems to be a bit different here.

We're not too strict about the workflow, so feel free to suggest changes, or make things easier for you, but if you use Jira/BB it should be easy to become familiar with GitHub.

> My only question for now is what is the best way to get into the IPython codebase? There's a lot of stuff going on here.

Yes, it is a pretty aging codebase.

There is the [good first issue](https://github.com/ipython/ipython/issues?q=is%3Aopen+is%3Aissue+label%3A%22good+first+issue%22) label, but some of those are already in progress, and mostly we need more reviewers for recent PRs.

I've also [started a bunch of Pull-requests](https://github.com/ipython/ipython/pulls/Carreau), that are just ideas and need to be finished.  

You can also look at the two pinned issues #13108 and #11816 which are the current work we're trying to get done to make an 8.0 release, and begin to stop maintaining a 7.x branch.

**Pull request merged**
