### PR TITLE
fixed typo in overview.rst

### PR DESCRIPTION
**Pull request by jentjr**

### CODE REVIEW

**Review by willingc — APPROVED** [review]
Thanks @jentjr for taking the time to correct the typo. :cake:

**Comment by Carreau** [comment]
@meeseeksbot backport to 5.x

**Comment by Carreau** [comment]
@meeseeksdev backport to 5.x

**Comment by willingc** [comment]
Hey @Carreau. What happens when we say thank you to @meeseeksdev? :cake:

**Comment by Carreau** [comment]
```
2017-02-23T19:48:58.648010+00:00 app[web.1]: Got a comment Hey @Carreau. What happens when we say thank you to @meeseeksdev? :cake:
2017-02-23T19:48:59.054739+00:00 heroku[router]: at=info method=POST path="/webhook" host=meeseeksbot.herokuapp.com request_id=157aeacb-0b73-4813-9ee7-b51037072857 fwd="192.30.252.45" dyno=web.1 connect=0ms service=411ms status=200 bytes=144
2017-02-23T19:48:59.057137+00:00 app[web.1]: found permission admin for user  willingc on  ipython ipython
2017-02-23T19:48:59.057306+00:00 app[web.1]:     :: treating ? :cake:
2017-02-23T19:48:59.057327+00:00 app[web.1]: unnknown command ?
```

**Pull request merged**
