### PR TITLE
move eventful to widgets

### PR DESCRIPTION
**Pull request by minrk**

### CODE REVIEW

**Comment by takluyver** [comment]
Min and I had originally thought of moving eventful, and the trait types that use it (EventfulDict, EventfulList), into widgets. They are generic, but they were added for widgets and that remains the only place we use them. I don't have strong feelings about where these belong, but I'd like to make it clear so other people have a chance to consider it.

**Comment by minrk** [comment]
Right. I'm about 50/50. In some sense, this is how I think container traits should always work, which is part of why I lean slightly towards leaving them in traitlets.

**Comment by jdfreder** [comment]
From the meeting, move this into widgets.

**Comment by minrk** [comment]
Moved to widgets

**Comment by Carreau** [comment]
+1

**Pull request merged**
