### PR TITLE
Fix documentation for changing configuration dynamically

### PR DESCRIPTION
**Pull request by 2DSharp**
Documented the configuration changing process dynamically in the shell and making it live,
pointed out in https://github.com/ipython/ipython/issues/11329.

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, the think in #11329 is a hacks, and you should'n re-call `init-ptk-app()`.

You most likely want to dynamically set `ip.pt_app.editing_mode` via a magic that does the right checks., and/or add listeners to `ip.editing_mode` that propagate the value to `ip.pt_app.editing_mode`.

**Comment by 2DSharp** [comment]
Sorry, but even if I set the magic config, it doesn't work unless I call `ip.init_prompt_toolkit_cli()` atleast in my version. Am I missing something?

**Comment by Carreau** [comment]
I think that something like #11390 would be better suited to avoid having to poke at internals.

Then you just have to `ip.editing_mode` to switch, or use `%config TerminalInteractiveShell.editing_mode = 'vi'` which now works (and prepend `[ins]`/`[nav]`/`[...]` to the prompt. 

We just don't have that many vim user, so of course we don't fix bugs.

**Comment by 2DSharp** [comment]
@Carreau I don't think setting the configuration using magics is the problem. The last time I have been trying to get that working in a sprint, had me require to use `init_prompt_toolkit_cli()` to actually make the changes work.

**Comment by Carreau** [comment]
Please re-read the rest of the comments and #11390.

I does work here locally if you update the right attributes of the right class instance..
 
You should not call `init_prompt_toolkit_cli()` many time, that will make internal IPython state inconsistent.

**Comment by Carreau** [comment]
closing, fixed by #11390 feel free to ask if this need to be reopened.

**Pull request closed without merging**
