### PR TITLE
prompt_toolkit compatible prompt machinery

### PR DESCRIPTION
**Pull request by takluyver**
Fixes gh-9331 (roughly)

The input prompts are now displayed through prompt_toolkit, so this code doesn't know the width it's trying to match.

@jonathanslenders I don't suppose there's a public API for us to get the width of the prompt area from the last run of the prompt_toolkit `CommandLineInterface`?

### CODE REVIEW

**Comment by Carreau** [comment]
Failure seem real, but I guess we just need remove the test.

**Comment by jonathanslenders** [comment]
@takluyver Sorry, no there's no public API for that. (Right now, not sure how I would ever expose this.)

**Comment by takluyver** [comment]
OK, thanks - I knew it was a long shot. It should be easier to do this on our side, since we no longer have the ANSI colouring stuff embedded in a string.

**Comment by takluyver** [comment]
This grew a bit: it now removes the `PromptManager` machinery, and adds a new `Prompts` class in the terminal package. Prompts are no longer configurable as template strings (I already broke it for input prompts when switching to prompt_toolkit, but this removes that config system entirely). My idea is that if you want to customise prompts, you should subclass the new `Prompts` class and redefine the prompt generation methods, and then set:

```python
shell.prompts = MyPrompts(shell)
```

This allows more flexibility, while eliminating all the predefined prompt elements we had for string templating.

**Comment by Carreau** [comment]
> This grew a bit: it now removes the PromptManager machinery, and adds a new Prompts class in the terminal package. Prompts are no longer configurable as template strings (I already broke it for input prompts when switching to prompt_toolkit, but this removes that config system entirely). My idea is that if you want to customise prompts, you should subclass the new Prompts class and redefine the prompt generation methods, and then set:
> 
> shell.prompts = MyPrompts(shell)
> This allows more flexibility, while eliminating all the predefined prompt elements we had for string templating.

No objections with this change. @asmeurer  you are a custom-prompt user right ? I think your input might be welcomed.

**Comment by asmeurer** [comment]
Is this related to https://github.com/ipython/ipython/issues/8724?

**Comment by asmeurer** [comment]
I don't have time to look at this in-depth. This is the code I use to customize my prompt (among other things) https://github.com/asmeurer/iterm2-tools/blob/master/iterm2_tools/ipython.py. Can you indicate how that code would change with this? That file also has some comments with some various issues I found with IPython, if that helps any.

**Comment by asmeurer** [comment]
Specifically the issue of #8724:

> The more advanced fix (taking into consideration that a dynamic prompt might have a different number invisible characters each time it is displayed) is awkward with the existing API, which implicitly assumes that the number invisible characters is the same for any given template. 

Does this address that?

**Comment by takluyver** [comment]
This should address that, in that prompts are now generated as a list of token tuples, with a style and a piece of text, rather than as a single string containing ANSI escapes. So we no longer need to deal with 'invisible characters'.

Custom prompt stuff will need to be totally rewritten for IPython 5; I don't see any way round that with the switch to prompt_toolkit. See this section of the diff for the new Prompts class API that you'd have to supply: https://github.com/ipython/ipython/pull/9471/files#diff-9c5b89476acdb54178398f461c809c26R9

**Comment by asmeurer** [comment]
So I should implement the invisible iTerm2 control sequences as tokens, with empty text?

**Comment by jonathanslenders** [comment]
@asmeurer Not sure, but I think if this is an escape-sequence, and passed into prompt-toolkit, then it will probably be escaped and displayed as something like ``^[``. (It expects plain text.)
We are talking about this, right?: https://github.com/asmeurer/iterm2-tools/blob/master/iterm2_tools/shell_integration.py#L101

If so, I think we need a way in IPython to send these sequences before and after calling the prompt function.

**Comment by takluyver** [comment]
There is already a configurable `InteractiveShell.separate_in` which is a string printed before starting the prompt. There's nothing equivalent for after the prompt, but you could use the `pre_run_cell` [event](http://ipython.readthedocs.io/en/stable/config/callbacks.html).

**Comment by asmeurer** [comment]
I specifically need to send a sequence after the prompt but before the user-entered code. I also need to do a separate sequence after the user-entered code but before the output, for which I use [pre_execute](https://github.com/asmeurer/iterm2-tools/blob/06198b46b0ccc6502b2c12e3f08c8310dc6d4ced/iterm2_tools/ipython.py#L117).

**Comment by takluyver** [comment]
I'm not sure how 'after the prompt but before user entered code' works with prompt_toolkit - my understanding is that it can update the multiline prompt area and user input area as you're typing.

**Comment by jonathanslenders** [comment]
Honestly, right now there is no way to do this. Any VT escape sequence will be escaped, there is no way to insert this in the output.

There is this issue: https://github.com/jonathanslenders/python-prompt-toolkit/issues/148
But it didn't make it on my list because of not much interest and only working on iTerm2.

However, one workaround that could possibly work is printing literally everything before the IPython prompt, just like this: ``'\033]133;A\aIn[1]:\033]133;B\a\r'.
So print BEFORE_PROMPT, followed by the actual prompt (but not through prompt-toolkit), then print AFTER_PROMPT, then print carriage return. prompt-toolkit should then overwrite this prompt, but Iterm2 should now  know about these positions.

**Comment by asmeurer** [comment]
If you're talking about "continuation" prompts or any additional prompt that is shown after you start typing, those aren't supported. Basically, it should do

{before_prompt}prompt >{after prompt} \<user code here\>

and if additional "prompts" are generated after the user starts typing code, those will just be considered to be part of the user input.

**Comment by Carreau** [comment]
We should test this branch (that needs rebase) with https://github.com/jonathanslenders/python-prompt-toolkit/pull/299

**Comment by Carreau** [comment]
Figured things out and sent a fix to PTK. 
I'll try to write up documentation for that later and send it to you @takluyver 
Monday is holidays here in the US, so might be a slow day.

**Comment by Carreau** [comment]
Sent a PR to improve/remove & docs :  https://github.com/takluyver/ipython/issues/17

**Comment by takluyver** [comment]
Merged @Carreau's doc changes and rebased. Then merged @Carreau's doc changes again, because I rebased without pulling ;-)

**Comment by Carreau** [comment]
> Merged @Carreau's doc changes and rebased. Then merged @Carreau's doc changes again, because I rebased without pulling ;-)

Nobody's perfect. 

I think I'm +1 one that, with #9515 merged, we might be able to send a fix to @asmeurer iterm2-tools to not break (though it will still need ptk to get a new release for al to work).

**Comment by Carreau** [comment]
Ok, merging this and refining on master if necessary.

**Pull request merged**
