### PR TITLE
remove superfluous event.preventDefault

### PR DESCRIPTION
**Pull request by minrk**
from #7416

only one of the additions from that PR was necessary to address the issue

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, indeed, I should have seen that.

**Comment by Carreau** [comment]
Need rebase. Sorry.

**Comment by minrk** [comment]
No problem. I only found out that some of these were unnecessary by accident. I was a bit surprised, and don't fully understand, but I'm happy about it.

**Comment by minrk** [comment]
Rebased. If you can double-check to confirm that the issue is still fixed after this change, I would appreciate it. I'm never confident with event changes like this.

**Comment by Carreau** [comment]
Can you be confident with js ?

**Comment by Carreau** [comment]
I tried most of edit, view, insert, quickhelp, file download as... all seem fine. 

Merging.

**Pull request merged**
