### PR TITLE
DEV: Add preprocessor for sanitizing NBConvert outputs.

### PR DESCRIPTION
**Pull request by ssanderson**
Addresses https://github.com/ipython/ipython/issues/7488

### CODE REVIEW

**Comment by ssanderson** [comment]
@minrk @Carreau this is my proposal for a sanitizing preprocessor for NBConvert.  Credit to @TimShawver for the initial concept and implementation.

**Comment by minrk** [comment]
Thanks, I think this makes sense. We can investigate it further once we get 3.0 out the door.

**Comment by Carreau** [comment]
Make sens also. 
Travis need to be updated to install bleach, and setup.py also. 
Or we make it a optional dependency.

**Comment by takluyver** [comment]
@ssanderson are you still interested in this?

**Comment by ssanderson** [comment]
@takluyver sure.  We're already running an implementation of this internally at quantopian, so I guess the question is whether it makes more sense to have this in the main repository (which would require taking on bleach as a dependency) or whether it should live in our repo, in which case the work here is probably just a link or two in the docs somewhere.

**Comment by takluyver** [comment]
We do want to ensure nbconvert is easily extensible to add things like this, so if you're willing to be guinea pigs for that, +1 to leaving it in your repository.

**Comment by minrk** [comment]
This is the only PR touching nbconvert. Are we going to give this a try as an example of custom behavior, rather than inside nbconvert?

**Comment by Carreau** [comment]
+1 as standalone example/lib. Could even I guess be it's own package.

**Comment by ssanderson** [comment]
I probably won't have time to prep our repo to be open sourced for at least a week or so.  As long as that's fine with you all I think having this as an external lib is reasonable.

**Comment by Carreau** [comment]
We can also have a jupyter-contrib package which is throw in for many one time/one file scripts/extensions. We have that for for notebook extensions....

**Comment by minrk** [comment]
@ssanderson thanks, and no rush. This PR can serve as an example if anyone needs it in the time between now and when you get the chance to set it up as a plugin.

**Pull request closed without merging**
