### PR TITLE
Columinsed iterables

### LINKED ISSUE #8741: Nicer printing of long lists
Currently, a list prints horizontally if the result would be less than 80 columns (not sure if this is settable):

```{python}
In [57]: ['a']*15
Out[57]: ['a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a', 'a']
```
and vertically if it would be more than 80 columns
```{python}
In [59]: ['a']*16
Out[59]: 
['a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a',
 'a']
```

Often this is a big waste of space, and for things like `dir()`, it can make things hard to read.

Would it be possible to have a multi-column output, where the column width is `max([len(s) for s in list])`? Something like:

```
In [59]: dir('a')
Out[60]:
[__add__',        '__class__',        '__contains__', '__delattr__',
 '__dir__',       '__doc__',          '__eq__',       '__format__',
 '__ge__',        '__getattribute__', '__getitem__',  '__getnewargs__',
 '__gt__',        '__hash__',         '__init__',     '__iter__',
 '__le__',        '__len__',          '__lt__',       '__mod__',
 '__mul__',       '__ne__',           '__new__',      '__reduce__',
 '__reduce_ex__', '__repr__',         '__rmod__',     '__rmul__',
 '__setattr__',   '__sizeof__',       '__str__',      '__subclasshook__',
 'capitalize',    'casefold',         'center',       'count',
 'encode',        'endswith',         'expandtabs',   'find',
 'format',        'format_map',       'index',        'isalnum',
 'isalpha',       'isdecimal',        'isdigit',      'isidentifier',
 'islower',       'isnumeric',        'isprintable',  'isspace',
 'istitle',       'isupper',          'join',         'ljust',
 'lower',         'lstrip',           'maketrans',    'partition',
 'replace',       'rfind',            'rindex',       'rjust',
 'rpartition',    'rsplit',           'rstrip',       'split',
 'splitlines',    'startswith',       'strip',        'swapcase',
 'title',         'translate',        'upper',        'zfill]
 ```

### PR DESCRIPTION
**Pull request by naught101**
fixes #8741 - columnised printing of lists, tuples, dicts, sets, and seqs.

This code doesn't yet have updated tests. pull request is WIP.

I'm currently having trouble running tests locally, so pull-requesting to see which tests need addressing.

### CODE REVIEW

**Comment by Carreau** [comment]
I think we might still want to keep some of the "breakable" with `...` behavior, otherwise some long iterable with just make terminal or notebook crash.

**Comment by naught101** [comment]
It does use breakables, but only one per line. For long iterables, this will produce the same number of lines in total, but will usually display more elements. How big is the `...` behaviour by default? I mean, is it pushing the any kind of memory limits? Because if not, I think the current behaviour in this PR is ok (assuming it's working how I think it is).

**Comment by naught101** [comment]
I'm not sure... how should the `max_seq_length` argument should work when the sequence is to be columnised. Do we want to split in the middle of a row, even if

I don't really understand how `max_seq_length` works in general. Why do you send the whole list to the pretty printer if you're going to remove most of it at a breakable later? Doesn't that require a whole lot more unnecessary work in the inner pretty printer loop?

**Comment by Carreau** [comment]
> How big is the ... behaviour by default? I mean, is it pushing the any kind of memory limits? Because if not, I think the current behaviour in this PR is ok (assuming it's working how I think it is).

Beyond a few hundereds of line it will crash the notebook. 
I think the shortness was due to terminal usage where you usually want a pretty repr to fit on your screen. 
We have to refer to older devs than me to know why. 


> I don't really understand how max_seq_length works in general. Why do you send the whole list to the pretty printer if you're going to remove most of it at a breakable later? Doesn't that require a whole lot more unnecessary work in the inner pretty printer loop?

Maybe i'm not sure, I haven't looked at the code.  you can try to git blame to see the age of the code, but I would expect a lot of legacy behavior/compatibility that might not make sens anymore. 

I think we start to enter area where only @fperez know how/when this was design (discreetly pinging him see if he can pitch in to say how much of lib pretty is historical behavior)

**Comment by fperez** [comment]
Actually, the person to ping here is @rkern, who was the one who brought `lib/pretty.py` to IPython.  When I added pretty printing by default, I was only using the stdlib `pprint` module, which `pretty` is meant to replace, and Robert was the one who made those enhancements.

**Comment by takluyver** [comment]
I don't think this is quite right - `IPython.lib.pretty` goes to considerable lengths to do sensible printing of nested data structures, and it looks like this will only do nice formatting on one level of lists.

I think the real fix is to make the 'breakable' functionality smarter so we don't get newlines between every list element. I'm trying to work out how to do that in the code, but it's somewhat complicated.

**Comment by Carreau** [comment]
I'm going to close this as it lost some momentum, and we want to investigate better way of replacing lib. pretty. 

I'm tagging as "Closed PR" to remind us to reopen if someone is ready to start the work again, and will close to keep le list of PR shorter and easier to navigate. Feel free to ask if you need this to be reopen. 

Thanks !

**Pull request closed without merging**
