### PR TITLE
Docs overhall.

### PR DESCRIPTION
**Pull request by Carreau**
Remove many unnecessary section or inaccurate, build locally using RTD
theme to simplify testing locally.

Decrease the depth of some section. And do not duplicate table of
content which anyway is always on the sidebar.

---

Ping @willingc

### CODE REVIEW

**Comment by willingc** [comment]
@Carreau Cool! I'll review this weekend and push any corrections to your branch :-)

**Comment by Carreau** [comment]
You are allowed to take a break on WE.

**Comment by willingc** [comment]
@Carreau I made edits to the text. There are a number of warnings when building locally that should be fixed at some point though it could be in a later PR.

**Comment by Carreau** [comment]
You seemed to have cherry-picked `8c2dc6e` from `#9660` which seem like a mistake. I'll rebase to remove it.

**Comment by Carreau** [comment]
Actually you picked up a bunch of commits that had nothing to do with the edits you made. That should be fixed now.

**Comment by Carreau** [comment]
And yes, I am aware of the warnings, they are not docs related. Some of them are just wrong warnings, and other will be fixed with time.

**Comment by Carreau** [comment]
Travis is happy, merging.

**Comment by willingc** [comment]
Thanks @Carreau. Sorry about the extra commits.

**Pull request merged**
