### PR TITLE
Allow to pass a pygments class to highlighting_style.

### PR DESCRIPTION
**Pull request by memeplex**
Fixes https://github.com/ipython/ipython/issues/9749.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks. This looks OK to me.

**Comment by takluyver** [comment]
Not merging yet, because we're trying to get 5.1 out, and this is a new feature. I've milestoned it for 5.2.

**Comment by Carreau** [comment]
@takluyver do you feel comfortable starting to merge the 5.2's ? @memeplex do you want to add a line  in docs/source/whatsnew ?

**Comment by takluyver** [comment]
I think it's fine to start merging 5.2 things. Yes, @memeplex please do drop a file in docs/source/whatsnew/pr about the change.

**Comment by Carreau** [comment]
Added #9901 to remind us to drop a note in what's new. 

I'm also tempted to bump that as 6.0.

**Comment by memeplex** [comment]
Sorry I forgot about the note. I'm submitting a PR tomorrow.

**Comment by takluyver** [comment]
This feels like something that can be in a 5.x release.

**Comment by memeplex** [comment]
I have converted my prompt toolkit theme into a template and generated all base16 themes from it. I'm now in the process of registering my repo as an "official" base16 source.

https://github.com/memeplex/base16-prompt-toolkit

So now there is the full base16 suite to choose from! Do you want me to add an entry to the wiki or an example to the docs?

**Comment by takluyver** [comment]
Cool, thanks! I think it would slot into the docs neatly as a subheading in this section:
http://ipython.readthedocs.io/en/stable/config/details.html#terminal-colors

**Comment by Carreau** [comment]
@memeplex did you published in on PyPI ?

**Comment by memeplex** [comment]
No, I didn't. I will try to do it during the next few days.

**Comment by Carreau** [comment]
> No, I didn't. I will try to do it during the next few days.

Sweet, once you do it we can add a recipe to the docs !

**Pull request merged**
