### PR TITLE
Don't reload __mp_main__

### LINKED ISSUE #10522: autoreload of __mp_main__ failed when running script
This is a continuation of #8564.  After modifying a script, re-running it produces the following error:
```python
In [2]: run foo
[autoreload of __mp_main__ failed: Traceback (most recent call last):
  File "/home/luke/software/python/miniconda/envs/nsp2/lib/python3.6/site-packages/IPython/extensions/autoreload.py", line 247, in check
    superreload(m, reload, self.old_objects)
AttributeError: module has no attribute '__name__'
]
```
This occurs when using both `%autoreload 2` and `c.InteractiveShell.deep_reload = True`.

The merged fix, #8568, hasn't improved the issue for me.  I've had a local workaround for a while:  see my comment [here](https://github.com/ipython/ipython/issues/8564#issuecomment-150321942).  I'll submit a pull request shortly.

System information:
```
python -c "import IPython; print(IPython.sys_info())"

{'commit_hash': '5a894b9',
 'commit_source': 'installation',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/luke/software/python/miniconda/envs/nsp2/lib/python3.6/site-packages/IPython',
 'ipython_version': '5.3.0',
 'os_name': 'posix',
 'platform': 'Linux-4.8.0-34-generic-x86_64-with-debian-stretch-sid',
 'sys_executable': '/home/luke/software/python/miniconda/envs/nsp2/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, '
                '12:22:00) \n'
                '[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)]'}
```

### PR DESCRIPTION
**Pull request by lukepfister**
Fixes #10522.

### CODE REVIEW

**Comment by takluyver** [comment]
I don't particularly understand why the previous attempt at a fix (#8568) didn't fix this, but this seems reasonable to me.

**Comment by Carreau** [comment]
I don't think we really understand why, so I'm incline to merge as is. 

5.x ?

**Comment by takluyver** [comment]
Yep, backporting to 5.x sounds reasonable.

**Comment by takluyver** [comment]
Wrong button...

**Comment by takluyver** [comment]
@meeseeksdev backport

**Pull request merged**
