### PR TITLE
Generate fontweight enum values without an extraneous variable from a comprehension

### PR DESCRIPTION
**Pull request by jasongrout**
In python 2, the comprehension will create a new class attribute, i.  Using map will not create the extra local variable.

Before this, every DOMWidget class (and descendant) had an `i` attribute that was set to 8.

ping @jdfreder

### CODE REVIEW

**Comment by takluyver** [comment]
I think that will now fail in Python 3, because concatenating lists and map objects is not allowed. May need to be `list(map(...))`

**Comment by jasongrout** [comment]
Good call.  Thanks!

**Comment by jasongrout** [comment]
(FYI, I fixed the python3 problem @takluyver pointed out)

**Comment by Carreau** [comment]
+1

**Comment by ellisonbg** [comment]
This looks good. Merging.

**Pull request merged**
