### PR TITLE
Escape the quote in a filename even if text starts with a quote

### LINKED ISSUE #10069: Filename completion with quotes in filename does not escape the quotes
When completing filenames containing quotes those are completed verbatim, closing the string.
The user has to go back in the string to escape the quotes manually.

```
$ touch /tmp/foo\'bar
$ ipython
In [1]: open('/tmp/foo<TAB>
# actual
In [1]: open('/tmp/foo'bar
# Expected:
In [1]: open('/tmp/foo\'bar
```

```python
{'commit_hash': '3a3686a',
 'commit_source': 'repository',
 'default_encoding': 'UTF-8',
 'ipython_path': '/home/t-8ch/Projekte/ipython/IPython',
 'ipython_version': '6.0.0.dev',
 'os_name': 'posix',
 'platform': 'Linux-4.8.10-1-ARCH-x86_64-with-arch',
 'sys_executable': '/home/t-8ch/.local/share/virtualenvs/ipython/bin/python',
 'sys_platform': 'linux',
 'sys_version': '3.5.2 (default, Nov  7 2016, 11:31:36) \n[GCC 6.2.1 20160830]'}
```

### PR DESCRIPTION
**Pull request by chrisaycock**
Fixes #10069

### CODE REVIEW

**Comment by Carreau** [comment]
Testing on windows/Appveyor seem to fail.

**Comment by chrisaycock** [comment]
@Carreau Yeah, Windows escapes by wrapping a string with double quotes. I'm going to post on the original issue to get clarification about what that means for this issue.

**Comment by Carreau** [comment]
> @Carreau Yeah, Windows escapes by wrapping a string with double quotes. I'm going to post on the original issue to get clarification about what that means for this issue.

We can also punt on that and `protect` only on non-windows.

**Comment by chrisaycock** [comment]
@Carreau I'll try that and see what happens.

**Comment by chrisaycock** [comment]
@Carreau That worked. Thanks for the suggestion.

**Comment by Carreau** [comment]
Sweet ! Feel free to drop a file in `docs/source/whatsnew/pr` to describe improvements like this one, (you can even add `contributed by <...>` ) We'll consolidate these in the release notes !

**Comment by chrisaycock** [comment]
@Carreau Understood.

**Comment by Carreau** [comment]
Thanks ! Perfect !

**Pull request merged**
