### PR TITLE
Use stdlib inspect.signature if available.

### PR DESCRIPTION
**Pull request by anntzer**
cf #8822.

### CODE REVIEW

**Comment by Carreau** [comment]
hum, I think I would prefer a `signature.py` -> `_signature.py` and `signature.py` being:

```
try:
+    # If stdlib provides this functionality, use it instead as it is more up to
+    # date.
+    from inspect import BoundArguments, Parameter, Signature, signature
+except ImportError:
+    from ._signature import BoundArguments, Parameter, Signature, signature
```

Or it will be easy to miss the conditional import. 

Thoughts ?

**Comment by anntzer** [comment]
I am using the same pattern as for stdlib modules which have both a Python and a C version, e.g. `operator.py`.  Perhaps I can add just a note in the initial docstring?
Or I can switch to your approach, I don't really care but I don't feel like we should overengineer this either.

**Comment by Carreau** [comment]
Let's wait for a third opinion then.

**Comment by minrk** [comment]
I like @Carreau's `_signature` proposal.

**Comment by Carreau** [comment]
Awesome, thanks ! Don't hesitate to write a comment when you push a new commit as we dont' get notified !

Merging !

**Pull request merged**
