### PR TITLE
Patch stdout in interactive shell

### PR DESCRIPTION
**Pull request by ngg**
If a background thread prints text while the prompt is active then the text would overlap with the prompt which makes it kind of unusable. `patch_stdout_context` solves this issue, all texts are now printed above the prompt and completers remain perfectly usable. Unfortunately this does not solve issue #10406.

### CODE REVIEW

**Comment by jonathanslenders** [comment]
Hi @ngg,

would it be possible for you to try this branch: https://github.com/jonathanslenders/python-prompt-toolkit/pull/520
patch_stdout is not required and can be disabled, but this should make sure that line wrapping is not disabled for background threads.

**Comment by ngg** [comment]
@jonathanslenders: I've tried your branch jonathanslenders/python-prompt-toolkit#520, and it seems to solve the linewrap issue for me (#10406).
Without `patch_stdout_context` the background prints are wrapped correctly, but they screw up the prompt and completers.
With both our patches, it seems to work perfectly, the lines are wrapped correctly, and the prompt remains intact.

**Comment by jonathanslenders** [comment]
Even with readline (like before), the prompt will be screwed up.
Patching stdout could potentially break other libraries (I'm not sure). What if a certain library has a ``if sys.__stdout__ == sys.stdout`` test? I'm not sure it's worth doing it. It's a risk. Just press Control-L if a background thread printed to stdout. But I leave this up to the IPython developers to decide.

**Comment by ngg** [comment]
I think this can be a really useful feature, but it might have side-effects. If you think it doesn't worth it, then probably we can hide this behind an optional flag. Or probably checking if stdout is modified can work too.

**Comment by ngg** [comment]
https://github.com/jonathanslenders/python-prompt-toolkit/issues/507 is kind of a blocker issue. Its fix was already merged but not yet released.

**Comment by ngg** [comment]
Actually this has lots of unwanted sideeffects I do not reallly understand, for example when there are lots of background prints then `self.pt_cli.run()` sometimes returns with None and whole ipython dies. Something like this would be really good to have, but not solution.

**Pull request closed without merging**
