### PR TITLE
Warn about IPython extension dir

### PR DESCRIPTION
**Pull request by Carreau**
See #9514. 

I'm not happy with this approach, I would like to warn only if extensions are actually being loaded from this folder, so I might need to inspect he loaded module if it is loaded. 

cc @takluyver as this touch `install_ext` mechanism, I would like to have this to give useful information to people that might still be affected by older extensions. 

I'm also unsure if warnings are the best tool as it is not technically deprecated, but is simply not really advised.

### CODE REVIEW

**Comment by takluyver** [comment]
I also think we should inspect modules to see if they're loaded from the extensions directory. It shouldn't be hard to use `mod.__file__`.

**Comment by Carreau** [comment]
How about the following ?

**Comment by takluyver** [comment]
That looks like a lot of text to throw at users for something that's (IMO) rather gently deprecated. I don't think there's any hurry to get rid of the extensions dir.

**Comment by Carreau** [comment]
You want to bump to 7.0, or have a shot at a shorter text ?

**Comment by takluyver** [comment]
I'll have a go at a shorter text. Let's see if I can push to your branch.

**Comment by takluyver** [comment]
How's that?

**Comment by Carreau** [comment]
> How's that?

Sorry I missed your comment !

Thanks !

Self-but-not-really-self-as-you-pushed-changes merging.

**Pull request merged**
