### PR TITLE
include positional arguments in completions

### PR DESCRIPTION
**Pull request by ivanov**
Sounds like this is the sort of thing that would address #10013.

### CODE REVIEW

**Comment by takluyver** [comment]
Test failure:

```
FAIL: IPython.core.tests.test_completer.test_default_arguments_from_docstring
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.5.2/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/home/travis/build/ipython/ipython/IPython/core/tests/test_completer.py", line 377, in test_default_arguments_from_docstring
    nt.assert_equal(kwd, ['ncall', 'resume', 'nsplit'])
AssertionError: Lists differ: ['self', 'int', 'resume', 'int'] != ['ncall', 'resume', 'nsplit']
```

**Comment by ivanov** [comment]
Before I go and start trying to fix the remaining test, do we even want to do this? I can see it either way. I think the bigger issue is that our completion needs an overhaul to be more useful, as Thomas pointed out in [this comment](https://github.com/ipython/ipython/issues/10013#issuecomment-255536301)

How do others feel?

**Comment by takluyver** [comment]
@Carreau I forget the details of what was going wrong with jedi. Should we be re-enabling that as the first step in overhauling completion?

**Comment by Carreau** [comment]
Yes we can. Jedi had unicode-side-effects and the wrappers had bugs on
splittokens.

**Comment by Carreau** [comment]
Jedi does not do that. We'll have to provide that ourselves or submit a patch jedi.

**Comment by Carreau** [comment]
Closing as this has stalled for a long time. Tagged appropriately so it's easy to find and reopen when needed.

**Pull request closed without merging**
