### PR TITLE
Proposal: remove dependencies from IPython.external

### LINKED ISSUE #3994: Revisit importing dependencies from `IPython.external`
```python3 -c "import IPython; print(IPython.sys_info())"```

fails if executed in a directory which contains a subdirectory named "path":

``` Traceback (most recent call last):  
 File "<string>", line 1, in <module>
  File "/home/gert/.virtualenvs/ipython/lib/python3.3/site-packages/IPython/__init__.py", line 43, in <module>
    from .config.loader import Config
  File "/home/gert/.virtualenvs/ipython/lib/python3.3/site-packages/IPython/config/__init__.py", line 16, in <module>
    from .application import *
  File "/home/gert/.virtualenvs/ipython/lib/python3.3/site-packages/IPython/config/application.py", line 31, in <module>
    from IPython.config.configurable import SingletonConfigurable
  File "/home/gert/.virtualenvs/ipython/lib/python3.3/site-packages/IPython/config/configurable.py", line 33, in <module>
    from IPython.utils.text import indent, wrap_paragraphs
  File "/home/gert/.virtualenvs/ipython/lib/python3.3/site-packages/IPython/utils/text.py", line 27, in <module>
    from IPython.external.path import path
ImportError: cannot import name path```

### PR DESCRIPTION
**Pull request by minrk**
This removes IPython dependencies from IPython.external, and expresses them as regular dependencies.

The one we can't remove is pickleshare, which currently doesn't install on Python 3. It's a trivial fix, but the package doesn't seem to be maintained.

closes #3994

### CODE REVIEW

**Comment by Carreau** [comment]
Need rebase.

**Comment by minrk** [comment]
Rebased. This now removes pickleshare, which means that #7991 is effectively reverted until there is another release of pickleshare. We could also wait one more cycle before removing pickleshare.

**Comment by Carreau** [comment]
Should ask for right on pushing new version of pickleshare on PyPi ourselves ?

**Comment by minrk** [comment]
Ah, there still hasn't been a working release of upstream pickleshare for Python 3. Can't remove it, yet.

Sure, we could ask @vivainio if he wants us to make pickleshare releases.

**Comment by Carreau** [comment]
He does not seem to merge PR often either.

**Comment by vivainio** [comment]
Guilty as charged :). I just don't have bandwidth to deal with the module
maintenance. What do you sugges?

**Comment by minrk** [comment]
@vivainio we'd be happy to pick it up, if that would help you.

**Comment by Carreau** [comment]
Move i to org to get  to get more people reviewing ?

**Comment by Carreau** [comment]
And no issues on not having bandwidth.

**Comment by takluyver** [comment]
If you do want us to help move it forwards, the most important thing is to
give one of us access on pypi to make new releases.

**Comment by vivainio** [comment]
Thanks for the help offers :). So,

- What org should I add the github access to?
- Who should I add PyPI upload role to (pypi user name)?

**Comment by takluyver** [comment]
On Github, you can either:

- Add some of us individually as collaborators
- Transfer it to the `ipython` org - I think we'll need to do some set up to give you permission if that's what you want to do.
- Create a new `pickleshare` org, add us to that and transfer the repo there.

On PyPI: my username is `takowl`

**Comment by minrk** [comment]
and I'm `minrk` on PyPI.

**Comment by Carreau** [comment]
I'm mbussonn on PyPi.

**Comment by vivainio** [comment]
I have now added takowl, minrk and mbussonn to PyPi project as maintainer.

I also created a new pickleshare org and moved the repo there:

https://github.com/pickleshare/pickleshare

(also sent github invites for the org)

Apologies for the hassle and delays, hope this sorts it out :).

**Comment by minrk** [comment]
@vivainio terrific, thanks!

**Comment by Carreau** [comment]
Thanks ! No need to apologize for the delay, it was quick !

**Comment by takluyver** [comment]
pickleshare 0.5 is now out, so we should be able to remove our copy and depend on that.

**Comment by takluyver** [comment]
We have dependencies.

**Pull request merged**
