### PR TITLE
minor changes

### PR DESCRIPTION
**Pull request by RaymondDavidson**
dded minor changes and try/except on imports

### CODE REVIEW

**Comment by Carreau** [comment]
Hi, 

Thanks you for the pull requests, though you are using print statements (the current code source is Python 3 only so need parenthesis)  And I'm unsure printing and silencing exception is the right things. 

What is your thought process ? Or are you trying to debug something ? 

Thanks.

**Comment by RaymondDavidson** [comment]
i thought it might be helpful, also, it would keep the script from crashing on a failed import

**Comment by RaymondDavidson** [comment]
i just had an idea, so i suggested it

**Comment by Carreau** [comment]
> i thought it might be helpful, also, it would keep the script from crashing on a failed import
> View changes

Well, if there is a failed import then the script will not work. Preventing the error message at import is just asking for trouble later. Plus all of these are from standard library modules that can't be missing. 
If they are missing then something is deeply wrong with your Python install. 

A better way of having optional modules is to import them in the function using them:

```
def foo():
     import mod
     mod.dostuff()
```

Then `mod` will be imported only if `foo()` if used, so `mod` can be an optional dependency.
I can see this maybe of use for `functools` case for this file, but it's part of the standard lib as well on Py3 so no need to protect or delay it. 

Note that you can do the following to see what modules are already loaded at Python startup:

```
$ python3
Python 3.6.0 |Continuum Analytics, Inc.| (default, Dec 23 2016, 13:19:00)
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import sys
>>> sys.modules['functools']
<module 'functools' from '/Users/bussonniermatthias/anaconda/lib/python3.6/functools.py'>
>>> sys.modules['warnings']
<module 'warnings' from '/Users/bussonniermatthias/anaconda/lib/python3.6/warnings.py'>
>>>
```

You can see that warning, and functools are already available are are thus required for Python to work. 
You can also use `sys.modules.keys()` to see the full list. 

For these catching import error will never trigger at is is a no-op (except binding the name)
If we were to go this route (which we probably won't unless special case), you might want to separate the "ImportError" from "ModuleNotFound" (like package not installed). And a good practice is to reraise, or at least print the current stack (even if you don't reraise) as the stack get the __reason__ for the error.

**Comment by Carreau** [comment]
I doubt we want to get something like that in IPython (we can revisit if other disagree) and we are close enough from 6.0 that I don't want to commit to that so close to release. 

I'm going to close (to keep the PR Queue small), but I look forward to receive more contribution from you. We do have a number of  issue that need work and [should not be too hard](https://github.com/ipython/ipython/issues?q=is%3Aopen+is%3Aissue+label%3A%22Need+Contributor%22).

Thanks !

**Pull request closed without merging**
