### PR TITLE
[NOT FOR MERGING] Timeit output

### PR DESCRIPTION
**Pull request by fperez**
This is just so we can study whether argparse will do the trick for magics in general, or not.

The original intent of this PR, started with @minrk, was to add an output flag to the timeit magics.

I (mistakenly, as it turns out) thought argparse could handle a simple `-o` and `-o NAME` without ambiguity, which getopt definitely can't, so I bit the bullet and rewrote `%timeit` to use argparse.

In the process, it turned out that I couldn't get the argparse-based version to correctly pass the tests, due to some inconsistencies in parsing input with python code in it.  I then ran out of time debugging the problem.

If we can make this work, we can merge this PR, and then we can use the experience to consider whether we want to unify (at least for new/updated code) on argparse in our magics option handling code.

**Important note:** bugs aside, this PR isn't finished in that, after all, we can NOT have `-o` handle both the no-args and the named-arg case, since a case like `-o pass` would be incorrectly interpreted as assigning to a variable named `pass` (unless we resorted to crazy shenanigans in the parsing code).

So in the end, if we can sort the other bugs, we need to handle the named output with a _separate_ flag, say `-O`. I was going to do that but ran out of time with the parsing bugs.

Pinging @Carreau @takluyver from today's conversation.

### CODE REVIEW

**Comment by takluyver** [comment]
Cross link #8431

**Comment by Carreau** [comment]
Might also be of interest http://click.pocoo.org/4/

**Comment by Carreau** [comment]
BTW, i didn't now but optparse is [deprecated since python 3.2](https://docs.python.org/3.5/library/optparse.html)   apparently...

**Comment by takluyver** [comment]
We're not using optparse anywhere, as far as I know. We use a mixture of getopt and argparse, neither of which are marked as deprecated.

**Comment by Carreau** [comment]
AH, sorry getopt.. last discussion we had I remembered speaking about optparse. my bad.

**Comment by Carreau** [comment]
This need rebase.

**Comment by Carreau** [comment]
I'm going to close as no-one is working on that and this clutter the PR list. 
I'm tagging as "Closed PR" to remind us to look at it at some point. Also there is linked issue already.

**Pull request closed without merging**
