### PR TITLE
Migrate release creation instructions from wiki to docs

### PR DESCRIPTION
**Pull request by willingc**

### CODE REVIEW

**Comment by willingc** [comment]
Addresses #9180 

I've migrated the wiki contents to the docs and split the developer guide into two guides (3rd party development and core IPython development).  cc/@carreau, @minrk, @takluyver

**Comment by Carreau** [comment]
I think `docs/source/coredev/making_release.rst` and `docs/source/coredev/release_process.rst` shoudl be merged and made the same document. 
I'll send you a PR that merge the two together.

**Comment by Carreau** [comment]
various question:

- TAG: do we use `TAG =$VERSION` or `TAG==rel-$VERSION`
- is `6. Get a fresh clone`  necessary if we have `git -xfd`

**Comment by Carreau** [comment]
The wiki is **way** out of dates in many places.

**Pull request merged**
