### PR TITLE
Remove Ctrl-J & Ctrl-K shortcuts

### LINKED ISSUE #7716: Control+J in Notebook on Firefox on Windows
Student report: "I wish the that notebook didn't use Control+J in the notebook on Firefox on Windows to move cells. Firefox uses that for..." something else. 

Just providing feedback on 3.0.0-beta from the classroom.

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-7716

### CODE REVIEW

**Comment by jdfreder** [comment]
The tests corresponding to the move cell keyboard shortcuts need to be removed too.

**Comment by takluyver** [comment]
gah, sorry, git confusion, pushed directly to master. Anyway, I did remove the test in 5b49edb44f9fe993bc6ed16f761717627486e135, so I'll keep an eye on Travis, and if it passes, everything's OK, right?

**Comment by jdfreder** [comment]
Yup

**Comment by takluyver** [comment]
[Tests OK](https://travis-ci.org/ipython/ipython/builds/50269042)

**Comment by rossant** [comment]
For those (like me) who liked this shortcut, add this to your `~/.ipython/profile_default/static/custom/custom.js`:

```javascript
IPython.keyboard_manager.command_shortcuts.add_shortcut('ctrl-k', function (event) {
    IPython.notebook.move_cell_up();
    return false;
});
IPython.keyboard_manager.command_shortcuts.add_shortcut('ctrl-j', function (event) {
    IPython.notebook.move_cell_down();
    return false;
});
```

**Comment by jdfreder** [comment]
Thanks @rossant !

**Comment by alvinwt** [comment]
@rossant I would like to get the "go to left" /" go to right key" edit shortcuts back in IPython3. I would like to bind them to other than home and end which does not appear on my laptop.  Is there anywhere that I can find the right commands to put them in the custom.js file?

**Comment by Carreau** [comment]
Note the following is cleaner as yo don't define a anonymous function. 

```javascript
> IPython.keyboard_manager.command_shortcuts.add_shortcut('Shift-k','ipython.move-selected-cell-up')
< undefined

>IPython.keyboard_manager.command_shortcuts.add_shortcut('Shift-j','ipython.move-selected-cell-down')
< undefined
```

**Comment by excetara2** [comment]
How do we do this in the most recent version of jupyter? Can it be added to the config file in the same way as maybe I put it in the wrong place.

**Comment by Carreau** [comment]
Use the following:

```javascript
$ cat ~/.jupyter/custom/custom.js

define(["base/js/namespace"], function(Jupyter){
    console.info('Binding Ctrl-J/K to move cell up/down');
    Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-k','jupyter-notebook:move-cell-up');
    Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-j','jupyter-notebook:move-cell-down');
});

```

**Comment by excetara2** [comment]
There wasn't a custom.js file or even a custom folder so I created one and added the above but it doesn't seem to be loading this in for any new notebooks. Anyway to check if it is loading the custom.js file?

**Comment by Carreau** [comment]
Os X ? That would be in `~/Library/Jupyter/custom`. You can also run `jupyter --data-dir` to know where these files should be.

**Comment by excetara2** [comment]
Yes Os X. The data directory is shows as `~/Library/Jupyter/` as you have stated but when I move `custom/custom.js` in there still nothing happens when I start up a new notebook.

**Comment by takluyver** [comment]
> That would be in ~/Library/Jupyter/custom

No, looking at the code, custom lives in the config dir (i.e. `~/.jupyter`) not the data dir.

**Comment by Carreau** [comment]
> No, looking at the code, custom lives in the config dir (i.e. ~/.jupyter) not the data dir.

My bad, it's symlinked on my system.  so yes, it should be in `~/.jupyter/custom/custom.js`.

Can you tell us what's in  your JS console of your browser ? (try to force reload the page a few times)

**Comment by excetara2** [comment]
Link to a sceenshot below so it seems to see the custom.js file but must not be loading properly.

[https://www.dropbox.com/s/oeepfgtzyhr8695/Screenshot%202016-03-11%2010.53.24.png?dl=0]

**Comment by matthew-brett** [comment]
I was trying this custom js too, I have the same error (more or less):

```
TypeError: Cannot read property 'command_shortcuts' of undefined(…)check @ require.js?v=6da8be3…:900
default.js:48Default extension for cell metadata editing loaded.
```

I have an up to date `jupyter[notebook]`, running on OSX 10.11.

**Comment by jseabold** [comment]
It looks like you need to wait for these to be bound before you can call them.

```
define([
    "base/js/namespace", 
    "base/js/events" 
], function(Jupyter, events){
    events.on('app_initialized.NotebookApp', function(){
      console.info('Binding Ctrl-J/K to move cell up/down');
      Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-k','jupyter-notebook:move-cell-up');
      Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-j','jupyter-notebook:move-cell-down');
    });
});
```

**Comment by jseabold** [comment]
Might be worth re-opening https://github.com/jupyter/notebook/issues/21 so that we can discuss this in the right organization given that it's still an issue that comes up.

**Comment by d10genes** [comment]
I'm having trouble with your suggestion, @jseabold 

I have the following file


    $ cat ~/.jupyter/custom/custom.js

    console.info('About to try to define...')

    define([
        "base/js/namespace",
        "base/js/events"
    ], function(Jupyter, events){
        events.on('app_initialized.NotebookApp', function(){
          console.info('Binding Ctrl-J/K to move cell up/down');
          Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-k','jupyter-notebook:move-cell-up');
          Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-j','jupyter-notebook:move-cell-down');
        });
    });

but I only see `About to try to define...` printed in the console

**Comment by gojomo** [comment]
Had same problem here as @d10genes – the custom.js was being included, & top-level console message show, but the 'Binding' message and add_shortcut not run. (Using notebook 4.2.2; Chrome/52.)

But, stripping the file down to *not* register-for-later-eventing fixed the problem. That is: 

~~~
$ cat .jupyter/custom/custom.js 
console.info('Binding Ctrl-J/K to move cell up/down');
Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-k','jupyter-notebook:move-cell-up');
Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Ctrl-j','jupyter-notebook:move-cell-down');
~~~

Maybe now `custom.js` now only runs at the right event? 

If so, would be nice for jupyter/notebook#21 to be updated with a working recipe (@Carreau, @jhamrick).

**Comment by Henry-E** [comment]
Did anyone manage to put together a working implementation of a custom.js file to re-instate the keyboard shortcut for moving cells up and down?

Also while trying to figure it out, and running out time, I found the console warning "Notebook.move_cell_down is deprecated as of v4.1 and will be removed in v5.0"
Maybe this is referencing a different function that has been updated but I thought I'd mention it anyway.

**Comment by matthew-brett** [comment]
Yes, I miss this feature horribly.  Losing the shortcuts pushes editing notebooks past the inconvenience barrier to the state where I really need to convert the notebooks to something else to edit them.

**Comment by Carreau** [comment]
There are some bugs in libraries we ship with recent versions of notebook that prevent custom shortcuts  to work correctly (Singletons end up not being singletons). We're trying to figure that out, but we are between a rock and a hard place as fixing this break other things.

**Comment by foice** [comment]
Just to pass the issue of conflict wit browsers shortcuts, would this do the job?

    define(["base/js/namespace"], function(Jupyter){
        console.info('Binding Shift-Ctrl-Alt-J/K to move cell up/down');
        Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Shift-Ctrl-Alt-k','jupyter-notebook:move-cell-up');
        Jupyter.keyboard_manager.command_shortcuts.add_shortcut('Shift-Ctrl-Alt-j','jupyter-notebook:move-cell-down');
    });

I can se in the console that this is loaded, but I do not get any reaction to the shortcut on my cells, maybe I am doing something wrong? I never made a custom keybinding in Jupyter ...

**Comment by GiorgioBalestrieri** [comment]
@Carreau , any update on this?

**Comment by runningopenloop** [comment]
Why not just j and k from command mode?  I use a and b a lot to insert cells above/below.  It would be easier to not have to press any Ctrl/Ctrl+Shift+Alt/etc.

**Comment by pisymbol** [comment]
I'm curious about this as well.

**Comment by xiaolai** [comment]
Jupyterlab, Settings > Keyboard Shortcuts, User Overrides:

{
	"notebook:move-cells-down-down": {
		"command": "notebook:move-cell-down",
		"keys": [
		"Control K"
		],
		"selector": ".jp-Notebook:focus",
		"title": "Move Cells Down",
		"category": "Notebook Cell Operations"
	},
	"notebook:move-cells-down-up": {
		"command": "notebook:move-cell-up",
		"keys": [
		"Control J"
		],
		"selector": ".jp-Notebook:focus",
		"title": "Move Cells Down",
		"category": "Notebook Cell Operations"
	}
}

**Comment by ykalasdm** [comment]
Put this in the advanced settings editor of JupyterLab:

{"shortcuts": [
    {
        "command": "notebook:move-cell-down",
        "keys": [
            "Ctrl K"
        ],
        "selector": ".jp-Notebook:focus",
        "title": "Move Cells Down",
        "category": "Notebook Cell Operations"
    },
    {
        "command": "notebook:move-cell-up",
        "keys": [
            "Ctrl J"
        ],
        "selector": ".jp-Notebook:focus",
        "title": "Move Cells Down",
        "category": "Notebook Cell Operations"
    }
]
}

**Pull request merged**
