### PR TITLE
Remove pre-3.8 codepath in interactiveshell.py

### PR DESCRIPTION
**Pull request by GalBr**
Related to #13316 .
I'll probably do more relevant work in interactiveshell.py in this branch if that's ok. I just want to get feedback on what I do in the process, to make sure I do it correctly.

### CODE REVIEW

**Comment by GalBr** [comment]
`ast_asyncify` is only being called from a `sys.version_info < (3,8)` branch, but there's this if inside this function:
`if sys.version_info >= (3,8):
        return ast.parse(cell)`

This means we never use `_ast_asyncify`. How do we want to handle this? Remove this function completely or keep it and just remove the code inside it that handles the `sys.version_info < (3,8)` case?

**Comment by GalBr** [comment]
`init_deprecation_warnings` is not doing anything because it checks for ` sys.version_info < (3,7)`.
Should it be removed completely or should it be changed to `< (3,8)`?

**Comment by Carreau** [comment]
Yeas, I think that ast_asyncify can be removed, I sent upstream patches to CPython to make it unnecessary.

**Comment by Carreau** [comment]
Same for anything that is uncalled anymore, we should be able to remove them.

**Pull request merged**
