### PR TITLE
Modified markdown rendering to include GFM-style checkboxes

### PR DESCRIPTION
**Pull request by jojoelfe**
Hi,

this is a quick implementation of the task/todo feature of Github flavored markdown as requested in issue #6288. The discussion suggests that his feature should be implemented by marked.js. However, a meaningful implementation should be able to modify the underlying markdown and is therefore out of the scope of marked.js.

For me this would be very helpful as I manage many ongoing experiments with notebooks and having a quick TODO feature is quite nice.

Right now checking a box triggers a complete rerendering of the cell, which might be annoying for long markdown. But I did not want to mess with the set_text function since I don't know if any important events are triggered from there.

Thanks,

Johannes

### CODE REVIEW

**Comment by jdfreder** [comment]
We've considered maintaining an IPython Markdown flavor in the past and decided the costs outweigh the benefits.  My opinion is that if marked.js implements the markdown to html checkboxes, maybe https://github.com/chjj/marked/pull/587, then we can think about implementing the reverse in the notebook.

However I won't close the PR, giving others a chance to weigh in.

**Comment by minrk** [comment]
The point that @jojoelfe makes about clicking the checkbox modifying the markdown source means it can't feasibly be done *solely* in marked. I'm not sure what that means we should do about it.

**Comment by jdfreder** [comment]
My suggestion was to wait for marked to take the first step, and then implement our part (HTML -> MD).

**Comment by minrk** [comment]
@jdfreder I think that makes sense.

**Comment by shorty66** [comment]
Seems like [chjj/marked](https://github.com/chjj/marked/graphs/contributors) is no longer maintained. We should consider switching to one of the maintained forks.

**Pull request closed without merging**
