### PR TITLE
BUG: Fix getargvalues call with nested genexprs.

### LINKED ISSUE #8293: Error in error reporting.
The program to reproduce the error is the following:

```python
# file: ~/tmp/ipython-except.py
def foo(u):
    raise ValueError

# This shows the correct traceback:
# sum(sum(foo(u) for u in [0]) for _ in [0])
sum(sum(foo(u) for _ in [0]) for u in [0])
```

The following error is produced:

```
16:28:05 [5]: %run -i ~/tmp/ipython_except.py
---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
<ipython-input-5-21c031f5aefb> in <module>()
----> 1 get_ipython().magic(u'run -i ~/tmp/ipython_except.py')

/Users/musically_ut/prog/rare/ipython/IPython/core/interactiveshell.py in magic(self, arg_s)
   2306         magic_name, _, magic_arg_s = arg_s.partition(' ')
   2307         magic_name = magic_name.lstrip(prefilter.ESC_MAGIC)
-> 2308         return self.run_line_magic(magic_name, magic_arg_s)
   2309
   2310     #-------------------------------------------------------------------------

/Users/musically_ut/prog/rare/ipython/IPython/core/interactiveshell.py in run_line_magic(self, magic_name, line)
   2227                 kwargs['local_ns'] = sys._getframe(stack_depth).f_locals
   2228             with self.builtin_trap:
-> 2229                 result = fn(*args,**kwargs)
   2230             return result
   2231

/Users/musically_ut/prog/rare/ipython/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)

/Users/musically_ut/prog/rare/ipython/IPython/core/magic.py in <lambda>(f, *a, **k)
    191     # but it's overkill for just that one bit of state.
    192     def magic_deco(arg):
--> 193         call = lambda f, *a, **k: f(*a, **k)
    194
    195         if callable(arg):

/Users/musically_ut/prog/rare/ipython/IPython/core/magics/execution.py in run(self, parameter_s, runner, file_finder)
    736                         else:
    737                             # regular execution
--> 738                             run()
    739
    740                 if 'i' in opts:

/Users/musically_ut/prog/rare/ipython/IPython/core/magics/execution.py in run()
    722                             def run():
    723                                 runner(filename, prog_ns, prog_ns,
--> 724                                        exit_ignore=exit_ignore)
    725
    726                         if 't' in opts:

/Users/musically_ut/prog/rare/ipython/IPython/core/interactiveshell.py in safe_execfile(self, fname, *where, **kw)
   2655                     raise
   2656                 # tb offset is 2 because we wrap execfile
-> 2657                 self.showtraceback(tb_offset=2)
   2658
   2659     def safe_execfile_ipy(self, fname, shell_futures=False):

/Users/musically_ut/prog/rare/ipython/IPython/core/interactiveshell.py in showtraceback(self, exc_tuple, filename, tb_offset, exception_only)
   1850                     except Exception:
   1851                         stb = self.InteractiveTB.structured_traceback(etype,
-> 1852                                             value, tb, tb_offset=tb_offset)
   1853
   1854                     self._showtraceback(etype, value, stb)

/Users/musically_ut/prog/rare/ipython/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1238         self.tb = tb
   1239         return FormattedTB.structured_traceback(
-> 1240             self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1241
   1242

/Users/musically_ut/prog/rare/ipython/IPython/core/ultratb.pyc in structured_traceback(self, etype, value, tb, tb_offset, number_of_lines_of_context)
   1146             # Verbose modes need a full traceback
   1147             return VerboseTB.structured_traceback(
-> 1148                 self, etype, value, tb, tb_offset, number_of_lines_of_context
   1149             )
   1150         else:

/Users/musically_ut/prog/rare/ipython/IPython/core/ultratb.pyc in structured_traceback(self, etype, evalue, etb, tb_offset, number_of_lines_of_context)
    998
    999         formatted_exception = self.format_exception_as_a_whole(etype, evalue, etb, number_of_lines_of_context,
-> 1000                                                                tb_offset)
   1001
   1002         colors = self.Colors  # just a shorthand + quicker name lookup

/Users/musically_ut/prog/rare/ipython/IPython/core/ultratb.pyc in format_exception_as_a_whole(self, etype, evalue, etb, number_of_lines_of_context, tb_offset)
    949         records = self.get_records(etb, number_of_lines_of_context, tb_offset)
    950
--> 951         frames = self.format_records(records)
    952         if records is None:
    953             return ""

/Users/musically_ut/prog/rare/ipython/IPython/core/ultratb.pyc in format_records(self, records)
    745             file = py3compat.cast_unicode(file, util_path.fs_encoding)
    746             link = tpl_link % file
--> 747             args, varargs, varkw, locals = inspect.getargvalues(frame)
    748
    749             if func == '?':

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.pyc in getargvalues(frame)
    827     'varargs' and 'varkw' are the names of the * and ** arguments or None.
    828     'locals' is the locals dictionary of the given frame."""
--> 829     args, varargs, varkw = getargs(frame.f_code)
    830     return ArgInfo(args, varargs, varkw, frame.f_locals)
    831

/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/lib/python2.7/inspect.pyc in getargs(co)
    789                                 remain[-1] = remain[-1] - 1
    790                             if not remain: break
--> 791             args[i] = stack[0]
    792
    793     varargs = None

IndexError: list index out of range
```

Expected output is something along the lines of the following:

```
16:31:07 [11]: %run -i ~/tmp/ipython_except.py
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
/Users/musically_ut/tmp/ipython_except.py in <module>()
      3
      4 # This shows the correct traceback:
----> 5 sum(sum(foo(u) for u in [0]) for _ in [0])
      6 # sum(sum(foo(u) for _ in [0]) for u in [0])

/Users/musically_ut/tmp/ipython_except.py in <genexpr>((_,))
      3
      4 # This shows the correct traceback:
----> 5 sum(sum(foo(u) for u in [0]) for _ in [0])
      6 # sum(sum(foo(u) for _ in [0]) for u in [0])

/Users/musically_ut/tmp/ipython_except.py in <genexpr>((u,))
      3
      4 # This shows the correct traceback:
----> 5 sum(sum(foo(u) for u in [0]) for _ in [0])
      6 # sum(sum(foo(u) for _ in [0]) for u in [0])

/Users/musically_ut/tmp/ipython_except.py in foo(u)
      1 def foo(u):
----> 2     raise ValueError
      3
      4 # This shows the correct traceback:
      5 sum(sum(foo(u) for u in [0]) for _ in [0])

ValueError:
```

Tested against IPython `4.0.0-dev` (current `master`) and Python `2.7.9`:

```
$ python -m IPython
Python 2.7.9 (default, Jan  7 2015, 11:49:12)
Type "copyright", "credits" or "license" for more information.

IPython 4.0.0-dev -- An enhanced Interactive Python.
```

### PR DESCRIPTION
**Pull request by ssanderson**
Fixes #8293 and #8205.

### CODE REVIEW

**Comment by minrk** [comment]
Great! Can you add a regression test?

**Comment by ssanderson** [comment]
@minrk sure.  Is there a place where we already test traceback rendering, or should I just test that the patched `getargvalues` works correctly?

**Comment by minrk** [comment]
I'd test getargvalues directly. Probably simpler, that way.

**Comment by ssanderson** [comment]
ah, I found the ultratb tests before I read this.  Do you have a strong preference one way or the other?  The test here does also enforce that we're patching at the right time.

**Comment by minrk** [comment]
No preference, I just thought it might be simpler. As long as we get the test, +1. Thanks!

**Pull request merged**
