### PR TITLE
Fix test on Python nightly

### PR DESCRIPTION
**Pull request by Carreau**
I'll self merge as soon as test pass, but will still appreciate review.

### CODE REVIEW

**Comment by minrk** [comment]
I'd like to fix the actual behavior, too, because it seems like the test revealed a real bug - either in IPython or Python, which we are now hiding.

**Comment by Carreau** [comment]
> I'd like to fix the actual behavior, too, because it seems like the test revealed a real bug - either in IPython or Python, which we are now hiding.

No. It's a change of behavior of Python that now shows the object id for types:

```
(rootenv)~/eraseme master$ python3.6
Python 3.6.0a1+ (default, Jun  7 2016, 09:29:50)
[GCC 4.2.1 Compatible Apple LLVM 6.1.0 (clang-602.0.53)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class C:pass
...
>>> C
<class '__main__.C' at 0x7fa2f0d07ad8>
>>>
(rootenv)~/eraseme master$ python3.5
Python 3.5.1 |Anaconda 4.0.0 (x86_64)| (default, Dec  7 2015, 11:24:55)
[GCC 4.2.1 (Apple Inc. build 5577)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> class C:pass
...
>>> C
<class '__main__.C'>
>>>
```

**Comment by Carreau** [comment]
Trying to find the relevant issue/commit.

**Comment by Carreau** [comment]
I'm going to say it's https://hg.python.org/cpython/rev/af29d89083b3

**Comment by Carreau** [comment]
And it's confusing because NEW file says change in the REPL,  but patch and issue says REPR. 
Reported upstream, but the change seem on purpose, so yes, the object adress will show on 3.6 and not on <3.5, so not hiding a bug.

**Comment by minrk** [comment]
Thanks for investigating!

**Pull request merged**
