### PR TITLE
Add and use confirm_exit flag in prompt_toolkit shell

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-9359

### CODE REVIEW

**Comment by fperez** [comment]
This fixes the problem, thanks!

But I'm a little worried about the amount of copy/pasted code between `interactiveshell.py` and `ptshell.py`... Shouldn't these two share more code, so we don't have to fix the same issues in two places? I missed the details of the refactoring, so I may be off-base, but it looks to me like a common base class with everything that's common should make more sense than having a `class TerminalInteractiveShell(InteractiveShell)` subclassing in both files...

**Comment by takluyver** [comment]
The old TIS is going to go away before 5.0, so it ultimately won't be
duplicated. However, it couldn't be removed while jupyter_console was still
subclassing it. I just severed that link a few days ago, so removing the
old TIS is in the near future.

This does mean that jupyter_console 4 won't work with IPython 5, but I
think that's an acceptable cost as we decouple those pieces.

**Comment by fperez** [comment]
Got it. But what I am worried about is the breakage for users. It is a
weakness of our config system, but the reality is that we expose to the
public our actual class names. So if the class goes away, every user who
has configured things to, e.g. suppress the exit confirmation, will now get
an error message, and things won't work as expected.

I don't see an easy, clean solution, but I really don't want to keep
breaking the user experience like this... Thoughts?

**Comment by takluyver** [comment]
That's why the new class has the same name as the old, to minimise breakage
:-). Some specific settings are going to stop working where the changes
directly affect them, e.g. prompt customisation, but anything else should
be preserved.

I'll go through the config options on the old class before I get rid of it,
and make sure that as many as possible are copied to the new one.

**Comment by minrk** [comment]
We've deprecated configurable class names in the past for exactly this reason. You can see [InlineBackend](https://github.com/ipython/ipykernel/blob/4.3.0/ipykernel/pylab/config.py#L41) for an example.

**Pull request merged**
