### PR TITLE
Fix error tab completing in the debugger

### PR DESCRIPTION
**Pull request by takluyver**
I think I broke this in 5.2.

Closes gh-10222

### CODE REVIEW

**Comment by minrk** [comment]
Do you want to do a 5.2.1 shortly?

**Comment by takluyver** [comment]
I wouldn't say I want to, but yes, I should.

**Comment by takluyver** [comment]
@meeseeksdev backport to 5.x

**Comment by takluyver** [comment]
It's released, but the upload to archive.ipython.org failed; I think the ssh key for this system isn't authorized on the server.

**Comment by Carreau** [comment]
> It's released, but the upload to archive.ipython.org failed; I think the ssh key for this system isn't authorized on the server.

Uploaded for you.

**Pull request merged**
