### PR TITLE
Fix non-deterministic tests in IPython.core.magics

### PR DESCRIPTION
**Pull request by rtilk89**
See https://github.com/ipython/ipython/issues/8032

### CODE REVIEW

**Comment by Carreau** [comment]
Wow. Nice finding. I'm baffled. 

cc @takluyver, I'd like to figure out why the `@skipdoctest` was triggering that.

**Comment by kr1m** [comment]
Yes - I'm equally as baffled ;)

**Comment by takluyver** [comment]
Weird. I'm totally guessing, but maybe it sometimes gets picked up by our doctest plugin, which looks for the flag set by `@skipdoctest`, and sometimes by the standard nose doctest collector, which might not.

Congratulations on finding it, but I'd like to find a fix that doesn't obscure the distinction between input and output. Maybe we can tweak the code so that it is a valid doctest?

**Comment by kr1m** [comment]
The multiline code block seems to confuse the doctest. 

Doesn't my change follow the pattern above? https://github.com/ipython/ipython/pull/10538/files#diff-6cba74f9bcf04d4fb403e97ebeff3d3aR54

**Comment by kr1m** [comment]
Hi @takluyver - See my latest pull request which contains a working doctest.

**Comment by takluyver** [comment]
Thanks :-)

**Pull request merged**
