### PR TITLE
Create LICENSE

### LINKED ISSUE #10757: Add LICENSE

### PR DESCRIPTION
**Pull request by fm75**
Fixes #10757

### CODE REVIEW

**Comment by jzf2101** [comment]
@fm75 we have `COPYING.rst` can you propose changes relative to that file in a `git mv`

**Comment by fm75** [comment]
I think you want the LICENSE file as proposed. The question in my mind is what to do with the non-license, narrative?

**Comment by Carreau** [comment]
This need to update MANIFEST.in if we add this file, or rename Copying.rst

**Comment by Carreau** [comment]
I've updated the PR with corresponding changes in Manifest.in removed some of the Copying. I've also added test to make sure all existing files are reference in Manifest.in

**Comment by Carreau** [comment]
Rebased to solve conflict. 

@takluyver now that we're targetting 7.0, I guess this can be merged ?

**Review by Carreau — APPROVED** [review]

**Review by takluyver — APPROVED** [review]

**Comment by Carreau** [comment]
Adding `exclude .editorconfig` that should make the test pass.

**Pull request merged**
