### PR TITLE
reshow nbagg figures on display

### LINKED ISSUE #8617: use js version of nbagg figures for display
The display system shows a png of figure objects, even if they are live nbagg figures and can have a live display.

This may require changes on the mpl side as well.

attn @pelson

### PR DESCRIPTION
**Pull request by minrk**
instead of inline images

closes #8617

This isn't quite done, there appears to be something to do about double-display.

### CODE REVIEW

**Comment by takluyver** [comment]
@minrk: tagged as waiting for author because you said there's still something to be done

**Comment by takluyver** [comment]
@minrk This is still tagged waiting-for-author because you said there's something left to do. Can you remember what that was? Does this make sense to do without whatever-it-was?

**Comment by minrk** [comment]
It was a double-display, I think. I'll try to look at it tomorrow.

**Comment by minrk** [comment]
This appears to be working just fine, now.

**Pull request merged**
