### PR TITLE
Added notebook diff

### PR DESCRIPTION
**Pull request by Gruek**
Part 1 of the issue in #7860 

New feature: Visual diffing tool
It can be used to visually compare a notebook to its previous versions in git from the notebook menu or to compare two different notebook files from the tree view.

http://nbviewer.ipython.org/gist/Gruek/8186a0fb7d6492338f78

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks for working on both of these pieces, I expect they'll be really useful!

We're just about to break the single big IPython repository up into a number of smaller repositories. So for both of these pieces, I think we should work out ways to develop and install them separately, rather than making them part of the IPython codebase.

**Comment by ssanderson** [comment]
@takluyver from having worked on UI modules like this for Quantopian's codebase, my guess is that it will be easy to pull the python pieces of this into a relatively stable package, but difficult to make the diff UI a separate package.  Diffing feels like a general enough feature that it might belong in the main project.  Any thoughts on making a diff UI a feature of the HTML notebook (and building a protocol for representing diffs of notebooks and/or text files)?

**Comment by takluyver** [comment]
My take on it is that rich diffing is something where we shouldn't bless one solution by integrating it into the notebook UI at present. I'd rather let people build these tools as separate, standalone things, and work out how best to integrate them once the possible approaches have been better explored.

**Comment by ssanderson** [comment]
> My take on it is that rich diffing is something where we shouldn't bless one solution by integrating it into the notebook UI at present. 

@takluyver the issue with this for UI work is that it's so hard to make a stable UI extension that it's hard to justify the time investment necessary to build something polished.  A policy of "wait and see what the community builds" only makes sense if the community has the tools and incentives to explore the space of possible implementations.  (I don't mean this as a knock against IPython's architecture btw; it's just genuinely hard to build a UI that's both pleasant to use and extensible).

Maybe what's needed is support for something like [Tornado's UI Modules](http://tornado.readthedocs.org/en/latest/guide/templates.html?highlight=module), which would allow people to build UI extensions against a set API.

**Comment by takluyver** [comment]
I mean that notebook diffing should for now be a separate, user facing tool, not something integrated into the notebook. i.e. you would run `nbdiff foo.1.ipynb foo.2.ipynb`. This is useful anyway so it can be integrated with git hooks.

**Comment by Carreau** [comment]
Though I understand the point the UI integration is difficult, maintaining UI is a lot of work, and we don't have the bandwidth to work on that without more full time developper.

With more regular contributor we might probably accept, but right not this is completely against what we are doing, which is separating into many repo. 

Though it is a perfect use case for defining the right API to work with different backend. After skimming I think it works only with git for the time beeing. I guess it could be refactor to use different backend postgress ? mercurial ? Google drive ? 


At quick glance I see `Diff` with an lcs method (longuest common subsequence ?) is it a general difflib ?
If so I tried to do a generic pure python [diff package](https://github.com/Carreau/difflib2.py), it would be nice to work on that separately. and reblace the stupid broken difflib in python stdlib. 

Will get a deeper look later though, and really exited to see people working on that.

**Comment by smoskwa** [comment]
One of the reasons I asked Alex to modify IPython was that nbdiff did not meet the requirements of our organisation. It works well if you run it locally however our users connect to notebook servers that are running on remote shared hosts (e.g. login nodes for high performance computing clusters)

That means launching nbdiff requires a ssh or VNC session to the remote host, navigating to the underlying notebook, etc.. which I’ll admit is merely inconvenient. More importantly, nbdiff presents results to at http://localhost:5000 but what we really wanted is a secure per-user port so that it operates when there are many users on the same host.


I’ve proposed that he make some changes:

- all the git-specific code becomes part of his git multiple checkpoint implementation and that is provided as an extension (GitContentsManager)
- the file_diff is added to the default contents manager, a barebones NBDiff class provided, and the tree notebook diff button retained
- the full NBDiff class above can be an extension, and others could provide their own that implement different algorithms
- the diff dropdown menu is removed and instead an option is provided for diffing against checkpoints (similar to the existing revert to checkpoint). this would do very little in the default single-checkpoint environment but if the above GitContentsManager is loaded you basically get the full functionality

That said, I’m not wedded to a particular path forward, it just didn’t seem clear we could achieve what we wanted purely through extensions or as a standalone tool.

I’m keen to support further work on this as it would benefit our users but I’m also aware that Alex’s vacation scholarship ends tomorrow and there are no guarantees on his future availability.

**Comment by takluyver** [comment]
It is now possible to have server extensions - third party code which can add HTTP handlers to the notebook web application. See [an example in cite2c](https://github.com/takluyver/cite2c/blob/master/cite2c_handlers.py). This would make it possible to serve this on the same port as the notebook application.

We're really happy to see people building things like this, but please feel free to get in touch with us at an earlier stage in the project. It takes some time to work out what makes sense in IPython, what should be distributed separately, how to integrate things, and so on. We're not really ready to handle a thousand lines of new code out of the blue, especially a couple of days before the person working on it is due to move on.

**Comment by Carreau** [comment]
> One of the reasons I asked Alex to modify IPython was that nbdiff did not meet the requirements of our organisation. It works well if you run it locally however our users connect to notebook servers that are running on remote shared hosts (e.g. login nodes for high performance computing clusters)
> 
> That means launching nbdiff requires a ssh or VNC session to the remote host, navigating to the underlying notebook, etc.. which I’ll admit is merely inconvenient. More importantly, nbdiff presents results to at http://localhost:5000 but what we really wanted is a secure per-user port so that it operates when there are many users on the same host.

Sure the requirement make sens. I suppose you have seen [JupyterHub](github.com/jupyter/jupyterhub) which is here for multi-user.


> all the git-specific code becomes part of his git multiple checkpoint implementation and that is provided as an extension (GitContentsManager)

Sound great, ping us on the repo once you have it, or even before if you need some help.


> the file_diff is added to the default contents manager, a barebones NBDiff class provided, and the tree notebook diff button retained

I think I would rediscuss that on the PR, but a smaller PR will be easier to handle. I think that "filediff" might make sens on non-file backends like postgress. where you could still do diff betzeen 2 notebook versions, or even 2 notebooks. 

But that would definitively get the discussion started, and/or make us think of the needed API. 

> That said, I’m not wedded to a particular path forward, it just didn’t seem clear we could achieve what we wanted purely through extensions or as a standalone tool.

It might be difficult with extension if we don't have the right API, and we woudl gladely consider adding modifying API if needed. 

This is one of the reason we encourage People to ask first and open PR early, even when not complete, so that we can quickly iterate and review while things are developed. It is relatively hard to review a few thousand lines at once, but easier if you see the PR grow and get/give feedback all along.
Alex did a huge work and probably had to dig a lot into IPython to figure that out. We would have been happy to help you while you were doing it, and we don't bite. 

Even if this does not get merged now, and Alex does not come back, this is a starting point for future work, and we will give you credit for that.

I suppose this is also a good example at how bad we are at communicating how we work and what our future plan are. And we'll do our best to improve that in the future.

**Comment by Gruek** [comment]
> It is now possible to have server extensions - third party code which can add HTTP handlers to the notebook web application. See an example in cite2c. This would make it possible to serve this on the same port as the notebook application.

Looking at this example, I'm not sure how the load_jupyter_server_extension function gets called, where does nbapp come from?

I will try and package this up as a standalone extension with my remaining time.

**Comment by ssanderson** [comment]
@Gruek server extensions are set up from https://github.com/ipython/ipython/blob/master/IPython/html/notebookapp.py#L955 and passed an instance of `NotebookApp`.  From there you can get to the Tornado server via `nbapp.web_app`, which is a subclass of `tornado.web.Application`.  Among other things, you can use `web_app.add_handlers` to register new tornado handlers there.

**Comment by takluyver** [comment]
Thanks @ssanderson 

Server extensions are configured as a list of Python modules - e.g. in the `ipython_notebook_config.py` file, you could have something like this:

```
c.NotebookApp.server_extensions = ['myextensionmodule']
```

The notebook app imports those modules and calls `load_jupyter_server_extension()` from them.

**Comment by Gruek** [comment]
Ok, I've got the handlers working now, thanks for all the help.

My next problem is, I'm not sure how to load in the nbdiff template to the HTMLexporter from the module. Currently, I have the nbdiff.tpl in the same dir of the module as the file that's trying to set the template_file, but it says template file could not be found.

I found these examples here https://github.com/ipython/nbconvert-examples/tree/master/custom_template but not sure how to apply them in the context of a standalone module.

Sorry for all the noob questions.

**Comment by takluyver** [comment]
These aren't noob questions - server extensions are quite new, and we probably haven't worked out all the kinks yet.

I think where you're providing _template_name_default, you also need to provide _template_path_default, something like this:

```python
def _template_path_default(self):
    # The directory containing this module
    return os.path.dirname(os.path.abspath(__file__))
```

**Comment by Gruek** [comment]
Using that code, I get the following error

> IPython.utils.traitlets.TraitError: The 'template_path' trait of an Exporter instance must be a list or None, but a value of class 'str'

I changed it to 

```python
def _template_path_default(self):
    # The directory containing this module
    return [os.path.dirname(os.path.abspath(__file__))]
```

and got template file not found again

**Comment by takluyver** [comment]
The trait error was my mistake, and your fix should be exactly right. I don't know why you're getting template file not found again.

**Comment by takluyver** [comment]
The logic in TemplateExporter to find and load a template is pretty complex. I wouldn't be at all surprised if there was a bug lurking somewhere in there. It's going on my list of things to try to clean up.

**Comment by Gruek** [comment]
Wasn't a bug, just me not including the template in the module.

**Comment by smoskwa** [comment]
In case anyone comes across this - we did pull out most of the functionality into an extension
https://github.com/csiro-scientific-computing/NotebookDiff

(the tree base file diff was not included)

**Comment by takluyver** [comment]
Thanks @Gruek and @smoskwa !

**Comment by minrk** [comment]
Thanks, guys!

**Comment by Gruek** [comment]
Hi again,

So the standalone package now has the full functionality of the pull request, but the process for enabling is currently 5 steps,

First you have to pip install the module, then you have to change the contents manager class in the config then you have to enable the server extension to add the handlers, then you have to install the nbextension to add the git compare menu, and finally there's also a bit that goes into custom.js to add the Diff button to the notebook list

So I'm just wondering if there's a way to repackage this in a way so it is only a 2 step process, where you can install the module and then enable/disable it in the config or through a python script.

Any help would be appreciated.

**Comment by jasongrout** [comment]
If we move the Notebook UI to https://github.com/phosphorjs (which has a nice component architecture), and work on the packaging angle as well, it should be considerably simpler to install and make available a UI extension to the notebook.

**Pull request closed without merging**
