### PR TITLE
Warn about universal wheels in the docs.

### PR DESCRIPTION
**Pull request by Carreau**
cc @takluyver

### CODE REVIEW

**Comment by minrk** [comment]
We should also consider stopping the 2/3 suffix for ipython 6. Not necessarily do it, but at least consider it.

**Comment by Carreau** [comment]
Well... for sure the `2` suffix :-) I'm mainly concern about the 5.x LTS, and this is why I send a doc change.

**Comment by takluyver** [comment]
I've sent you a  small PR to tweak the wording a bit: Carreau/ipython#13 . With that, I think it's fine.

**Comment by Carreau** [comment]
> I've sent you a small PR to tweak the wording a bit: Carreau/ipython#13 . With that, I think it's fine.

Merged in.

**Comment by takluyver** [comment]
Likewise :)

**Pull request merged**
