### PR TITLE
Terminal emulator in the notebook

### PR DESCRIPTION
**Pull request by takluyver**
To try this out: `pip install terminado`, launch the notebook server, and go to [http://localhost:8888/terminals/new](http://localhost:8888/terminals/new) (or replace `new` with any alphanumeric name).

You have an arbitrary number of named terminals. Tabs open to the same URL share a terminal - this isn't always flawlessly visually, especially if you open a new tab with something like vim already running, because it just sends the output, as it arrives, to all connected tabs, but it works pretty well in my informal tests.

If it can't load terminado, e.g. because you're on Windows, these handlers don't get added at all.

For now, terminals are only shut down if you quit your shell inside them. It should be easy, however, to build a REST API which can kill terminal sessions, and a UI on top of that.

I've copied the relatively minimal JS from terminado into our JS tree, because that seemed simpler than working out how to handle serving JS from another Python package. The big chunk of JS code, term.js, is added to the components submodule in a branch.

nb terminal screenshot

### CODE REVIEW

**Comment by michelkaeser** [comment]
Great feature! Has anyone already got it sucessfully to work behind a reverse proxy?

I get 'Connection already closes or not ready' with this Nginx config:

```nginx
map $http_upgrade $connection_upgrade {
    default upgrade;
    ''      close;
}

location ~* /workspace/(\d+)/(.*) {
        proxy_http_version  1.1;
        proxy_set_header    Upgrade     $http_upgrade;
        proxy_set_header    Connection  $connection_upgrade;
        proxy_read_timeout  86400;
        proxy_set_header    Origin      "";

        proxy_set_header  Host                 $host:$1;
        proxy_set_header  X-Forwarded-For      $proxy_add_x_forwarded_for;
        proxy_set_header  X-Forwarded-Protocol $scheme;
        proxy_set_header  X-Real-IP            $remote_addr;

        proxy_pass  http://<backend>:$1;
    }
```

Regular API calls (which are also through websocket?) work correctly, just not the terminals.

Thanks!

**Comment by takluyver** [comment]
Regular rest API calls are plain http requests, not over a websocket.
However, the notebook also uses a websocket to talk to the kernel, so if
you can run code in the notebook, I'd expect terminals to work.

**Comment by michelkaeser** [comment]
@takluyver ok, thanks for the correction. Running code within the notebook works fine. I just attached a console to the Docker container and saw that the following exceptions are raised:

```python
[E 15:44:07.315 NotebookApp] Uncaught exception in /workspace/49152/terminals/websocket/1
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 369, in _run_callback
        callback(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/terminado/websocket.py", line 88, in open
        raise tornado.web.HTTPError(404, "Websocket origin mismatch")
    tornado.web.HTTPError: HTTP 404: Not Found (Websocket origin mismatch)
[E 15:44:07.321 NotebookApp] Uncaught exception GET /workspace/49152/terminals/websocket/1 (172.17.42.1)
    HTTPServerRequest(protocol='http', host='192.168.82.186:49152', method='GET', uri='/workspace/49152/terminals/websocket/1', version='HTTP/1.1', remote_ip='172.17.42.1', headers={'Host': '192.168.82.186:49152', 'Accept-Encoding': 'gzip, deflate, sdch', 'X-Forwarded-Protocol': 'http', 'X-Forwarded-For': '192.168.82.1', 'Sec-Websocket-Version': '13', 'Sec-Websocket-Extensions': 'permessage-deflate; client_max_window_bits', 'Connection': 'upgrade', 'Pragma': 'no-cache', 'User-Agent': 'Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/40.0.2214.94 Safari/537.36', 'Cookie': 'sessionid=6dosrfowu3hp992x112dectdrbq1c4el; username="mk:1YHZcg:mohwwAJLQef-nR9V2RrNEf31cio"; csrftoken=AAnq91L7S2aU78mGMRbIgIThO3sa8HKS', 'Sec-Websocket-Key': 'IpZ9nlabAFpuszD24G+s2A==', 'X-Real-Ip': '192.168.82.1', 'Accept-Language': 'de-DE,de;q=0.8,en-US;q=0.6,en;q=0.4', 'Cache-Control': 'no-cache', 'Upgrade': 'websocket'})
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1288, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 337, in on_connection_close
        self.on_close()
      File "/usr/local/lib/python3.4/dist-packages/terminado/websocket.py", line 131, in on_close
        self.terminal.clients.remove(self)
    AttributeError: 'TermSocket' object has no attribute 'terminal'
[E 15:44:07.323 NotebookApp] Uncaught exception, closing connection.
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1288, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 337, in on_connection_close
        self.on_close()
      File "/usr/local/lib/python3.4/dist-packages/terminado/websocket.py", line 131, in on_close
        self.terminal.clients.remove(self)
    AttributeError: 'TermSocket' object has no attribute 'terminal'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/iostream.py", line 508, in wrapper
        return callback(*args)
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 343, in wrapped
        raise_exc_info(exc)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 355, in _handle_exception
        if tail.exit(*exc):
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 186, in exit
        return self.exception_handler(type, value, traceback)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1290, in _stack_context_handle_exception
        self._handle_request_exception(value)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1387, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 345, in _disallow_for_websocket
        raise RuntimeError("Method not supported for Web Sockets")
    RuntimeError: Method not supported for Web Sockets
[E 15:44:07.325 NotebookApp] Exception in callback functools.partial(<function wrap.<locals>.null_wrapper at 0x7f3ecda97048>)
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1288, in _stack_context_handle_exception
        raise_exc_info((type, value, traceback))
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 314, in wrapped
        ret = fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 337, in on_connection_close
        self.on_close()
      File "/usr/local/lib/python3.4/dist-packages/terminado/websocket.py", line 131, in on_close
        self.terminal.clients.remove(self)
    AttributeError: 'TermSocket' object has no attribute 'terminal'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/usr/local/lib/python3.4/dist-packages/tornado/ioloop.py", line 565, in _run_callback
        ret = callback()
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 275, in null_wrapper
        return fn(*args, **kwargs)
      File "/usr/local/lib/python3.4/dist-packages/tornado/iostream.py", line 508, in wrapper
        return callback(*args)
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 343, in wrapped
        raise_exc_info(exc)
      File "<string>", line 3, in raise_exc_info
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 355, in _handle_exception
        if tail.exit(*exc):
      File "/usr/local/lib/python3.4/dist-packages/tornado/stack_context.py", line 186, in exit
        return self.exception_handler(type, value, traceback)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1290, in _stack_context_handle_exception
        self._handle_request_exception(value)
      File "/usr/local/lib/python3.4/dist-packages/tornado/web.py", line 1387, in _handle_request_exception
        self.send_error(500, exc_info=sys.exc_info())
      File "/usr/local/lib/python3.4/dist-packages/tornado/websocket.py", line 345, in _disallow_for_websocket
        raise RuntimeError("Method not supported for Web Sockets")
    RuntimeError: Method not supported for Web Sockets
```

with the main reason:

```python
raise tornado.web.HTTPError(404, "Websocket origin mismatch")
    tornado.web.HTTPError: HTTP 404: Not Found (Websocket origin mismatch)
```

I guess. Could `proxy_set_header    Origin      "";` be the reason for that?

Basically the IPython notebook is within a Docker container and port 8888 is exposed to a random port. The Nginx reverse proxy proxies to that one (port is extracted from URL).

**Comment by takluyver** [comment]
That makes some sense. We have a same origin check for the notebook
websockets too, but it must be implemented a bit differently.

**Comment by michelkaeser** [comment]
OK with the help of https://github.com/ipython/ipython/issues/5525#issuecomment-42597929 I was able to get it running. The 'Host' header was wrong and 'Origin' should not be set.

Sorry for misusing this PR for such a question/problem.

The fact that it worked for the NB is interesting though. Probably the check there should be revisited and be more strict? (because it allowed Origin: "")

**Comment by takluyver** [comment]
The origin check is actually in Tornado itself. I guess `Origin: ""` must have removed the Origin header entirely, in which case the check in Tornado is bypassed - a comment [in the source](https://github.com/tornadoweb/tornado/blob/master/tornado/websocket.py#L164) says "When the origin is None, we assume it did not come from a browser and that it can be passed on." So that might be a dangerous option to have set in the proxy.

**Comment by rgbkrk** [comment]
@michelkaeser In case you're interested, [this is the nginx setup](https://github.com/jupyter/tmpnb-deploy/blob/master/roles/proxy/templates/nginx.conf.j2#L54) we're using for tmpnb and the coming try.jupyter.org site.

**Pull request merged**
