### PR TITLE
Migrate IPython/core/shellapp.py to traitlets new API.

### PR DESCRIPTION
**Pull request by Carreau**
## 

Same as other PRs.

### CODE REVIEW

**Comment by Carreau** [comment]
(oh, just remove a `as e` that was unused)

**Comment by takluyver** [comment]
Several test failures like this:

```
======================================================================
ERROR: Test with only stdout results.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ipython/ipython/IPython/testing/tests/test_tools.py", line 99, in test_main_path
    tt.ipexec_validate(self.fname, out)
  File "/home/travis/build/ipython/ipython/IPython/testing/tools.py", line 278, in ipexec_validate
    (fname, err))
ValueError: Running file '/tmp/tmp7n2ou56z/tmp4nm25w34.py' produced error: '[TerminalIPythonApp] CRITICAL | Bad config encountered during initialization:\n[TerminalIPythonApp] CRITICAL | No default value found for pylab trait of <IPython.terminal.ipapp.TerminalIPythonApp object at 0x7f70dd604048>\n'
```

**Comment by Carreau** [comment]
Yeah investigating on traitlets side. Apparently it's because 'allow_none'
is not metadata, so should be passed in constructor.
On May 17, 2016 02:07, "Thomas Kluyver" <notifications@github.com> wrote:

Several test failures like this:

======================================================================
ERROR: Test with only stdout results.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/ipython/ipython/IPython/testing/tests/test_tools.py",
line 99, in test_main_path
    tt.ipexec_validate(self.fname, out)
  File "/home/travis/build/ipython/ipython/IPython/testing/tools.py",
line 278, in ipexec_validate
    (fname, err))
ValueError: Running file '/tmp/tmp7n2ou56z/tmp4nm25w34.py' produced
error: '[TerminalIPythonApp] CRITICAL | Bad config encountered during
initialization:\n[TerminalIPythonApp] CRITICAL | No default value
found for pylab trait of <IPython.terminal.ipapp.TerminalIPythonApp
object at 0x7f70dd604048>\n'

—
You are receiving this because you authored the thread.
Reply to this email directly or view it on GitHub
<https://github.com/ipython/ipython/pull/9467#issuecomment-219661172>

**Comment by takluyver** [comment]
That makes sense - `allow_none` affects what the traitlet actually does.

**Pull request closed without merging**
