### PR TITLE
Test on 3.5 beta 4 on Travis

### PR DESCRIPTION
**Pull request by takluyver**
A new beta just came out. Let's see if it's available on Travis yet.

### CODE REVIEW

**Comment by takluyver** [comment]
Seemingly it isn't. Will leave this open, we can try again in a few days.

**Comment by takluyver** [comment]
N.B. despite Travis passing, it's not yet actually succeeding on 3.4, so don't merge this yet. I'm in conversation with Travis people getting b4 available.

**Comment by takluyver** [comment]
Turns out my browser was somehow caching the Travis output, and the test run is actually succeeding now. So this should be ready to merge.

**Comment by damianavila** [comment]
LGTM

**Pull request merged**
