### PR TITLE
Use mock and testpath for test_paths

### PR DESCRIPTION
**Pull request by takluyver**
This removes our handcoded monkeypatching/restoring code in test_paths, replacing it with context managers from unittest.mock and testpath. `testpath.modified_env` has one advantage over `unittest.mock.patch.dict`: it can temporarily _unset_ specific environment variables as well as setting them.

I also switched a couple of tests to use `assert_isfile` and `assert_isdir` from testpath. These functions should be more informative when the assertion fails than simply asserting on the equivalent os.path functions.

If this is accepted, I'll move testpath to Jupyter maintenance, as we discussed.

### CODE REVIEW

**Comment by minrk** [comment]
I like this. testpath is pretty slick.

**Comment by takluyver** [comment]
Thanks!

**Comment by rgbkrk** [comment]
Oh my gosh, testpath is really handy. Thanks @takluyver. I'll be using this in other places.

**Comment by takluyver** [comment]
You're welcome :-)

**Pull request merged**
