### PR TITLE
Simplify _completer() constr. in core/completer.py

### PR DESCRIPTION
**Pull request by LucianaMarques**
Exclude the text field from the constructor and made modifications
accordingly to this new requirement.

This is part of #11622, still much more to do. I excluded the text field from the _complete() function and modified the class' constructor accordingly.

### CODE REVIEW

**Comment by LucianaMarques** [comment]
Hey guys, I'm sorry for the delay in replying to this, but I didn't run any tests before submitting this PR. I'll do this and I'll come back later with some improvements.

**Comment by Carreau** [comment]
Thanks for this ! I'll have a look; I was traveling for most of the week.

**Comment by LucianaMarques** [comment]
Hey guys!

I ran now `iptest` and no tests were passing because I forgot to update the files in which the function I'm modifying was called. 

I did the required modifications and all tests pass in my machine, but AppVeyor and Travis seem not to work. Are there any modifications that I need to be aware of or any required extra steps?

Thanks!

**Comment by Carreau** [comment]
Thanks I'll have a look; but I'm traveling for the next few days. 

> I ran now `iptest` and no tests were passing because I forgot to update the files in which the function I'm modifying was called.

That might happened if you have IPython miss-installed or installed twice. 

Try uninstalling IPython a couple of time, then re-do the `pip install -e .`  step.

**Comment by gpotter2** [comment]
Hey,
I have several questions about the completion API, I summarized them over https://github.com/ipython/ipython/pull/11737#issuecomment-493683869 (I'd be willing to help but I don't get where IPython is going with it).
I'd be grateful if you could have a look :-)

**Comment by LucianaMarques** [comment]
Hey guys,

I will propose some refactoring on the completer class, so I'm closing this for now, it's not of much use.

**Pull request closed without merging**
