### PR TITLE
Fix user interface tour

### LINKED ISSUE #7418: User interface tour broken.
Don't start at all;  raise as undefined not a function deep in bootstrap.

### PR DESCRIPTION
**Pull request by jhamrick**
This fixes #7418 
- updates the version of bootstrap tour
- removes usage of the backdrop, since it seems to be broken
- fix various element ids so the tour points to the right element

### CODE REVIEW

**Comment by jhamrick** [comment]
Ideally it would be nice to have tests to catch when the tour breaks, but I remember trying to write tests for it a while back and failing to properly get the keyboard events working (or something along those lines). Unfortunately, I don't think I'll have time to try to get them working now, though I might in a few weeks.

**Comment by jhamrick** [comment]
I think this also fixes #5570

**Comment by minrk** [comment]
I merged ipython/ipython-components#52, so you can update the components ref to master.

**Comment by jhamrick** [comment]
Cool, thanks.

**Comment by minrk** [comment]
Thanks!

**Pull request merged**
