### PR TITLE
Fix release date

### PR DESCRIPTION
**Pull request by Carreau**
cc @takluyver

### CODE REVIEW

**Comment by takluyver** [comment]
@meeseeksdev merge

**Comment by Carreau** [comment]
@meeseeksdev[bot] backport

**Comment by Carreau** [comment]
nop, branch inferring failed, let me fixed that.

**Comment by Carreau** [comment]
@meeseeksdev[bot] backport

**Comment by Carreau** [comment]
I'm going to get it right...

@meeseeksdev[bot]  backport

**Comment by Carreau** [comment]
drumroll....

**Pull request merged**
