### PR TITLE
Use pathlib in packaging.py, and gen_latex_symbols.py

### PR DESCRIPTION
**Pull request by jpavlav**
* Added pathlib in a few places where it makes sense to 
Related to #12515

### CODE REVIEW

**Comment by jpavlav** [comment]
Anything I need to do to trigger a new build?

**Comment by jpavlav** [comment]
Need to run darker on it. Plus, just realized I may have messed up the spirit of the `temp_pyfile()` function. Will check if any of its callers actually close the open file handle.

**Comment by jpavlav** [comment]
@Carreau Hey there! Sorry for all of the noise on this one. Had some issues with my local darker not catching some things that were caught on the Travis runs.

**Comment by Carreau** [comment]
No worries, thanks for everything, there are conflict right now, if you are inclined to rebase that would be appreciated, otherwise i'll do it later, and if darker is too strict we can disable it.

**Pull request merged**
