### PR TITLE
Readthedocs documentation is now on RTD.io not .com

### PR DESCRIPTION
**Pull request by Carreau**
ping @willingc

### CODE REVIEW

**Comment by takluyver** [comment]
Let's update the intersphinx mapping while we're at it:

https://github.com/ipython/ipython/blob/d58e930df4c4b091bcd0af81846d3d072d7500aa/docs/source/conf.py#L207

**Comment by Carreau** [comment]
> Let's update the intersphinx mapping while we're at it:
> 
> https://github.com/ipython/ipython/blob/d58e930df4c4b091bcd0af81846d3d072d7500aa/docs/source/conf.py#L207

Good point, I grepped only the .rst files. Done everywhere.

**Comment by takluyver** [comment]
Thanks :-)

**Comment by willingc** [comment]
Thanks @takluyver and @carreau. See https://github.com/jupyter/jupyter/issues/145. I've been immersed in PR https://github.com/jupyter/jupyter/pull/138. Migrating to .io is definitely on my radar. Help is appreciated. Ping me if you make changes in other repos and I'll update the checklist in  https://github.com/jupyter/jupyter/issues/145

**Pull request merged**
