### PR TITLE
fix: Allow pinfo magic command to work for dictionary access.

### PR DESCRIPTION
**Pull request by kgritesh**
Closes: #10469

### CODE REVIEW

**Comment by takluyver** [comment]
Hi, sorry it's taken us so long to look at this!

**Comment by takluyver** [comment]
I'm wary of this, not because I think it's wrong, but because it's extra complexity in part of the code that I suspect is already a bit wobbly.

I'm also not sure where it should stop. If we can get dictionary keys `d['foo']`, why not list elements `d[0]`? Literals `[1, 2].index`? Calling builtin methods `s.lower().count`? Builtin functions `str(x).lower`? This is one step towards a Python parser, and I don't think we want to build a Python parser.

**Comment by kgritesh** [comment]
@takluyver i think i get your concern why it may not be a good idea  to have this as its kind of a rabbit hole. In that case, it would make sense then to close the issue and PR right? Or you think there can be a better way to solve this issue?

**Comment by takluyver** [comment]
Yup, sorry, I am going to close it. I can't think of any way to do what you want without going down the parser rabbit hole.

**Pull request closed without merging**
