### PR TITLE
Fix virtualenv warning for Cygwin

### PR DESCRIPTION
**Pull request by Igonato**
Getting `Attempting to work in a virtualenv...` warnings when running in Cygwin and starting ipython in a virtualenv. (Also, using a virtualenvwrapper, not sure if it makes a difference)

Turns out `p_venv` looks like this `\cygdrive\c\users\igonato\envs\myenv` when `sys.executable` is like this `c:\users\igonato\envs\myenv\scripts\python.exe`.

This should make the check a bit more robust when running in Cygwin

Cheers!

### CODE REVIEW

**Comment by Carreau** [comment]
Thanks for the PR I'm unfortunately at conferences for the next 2 weeks, so may have issue having time to review it. 

One quick comment, can you deactivate the auto-trimming of whitespace on you editor? That screw up usage of git blame.

Thanks !

**Comment by Igonato** [comment]
> One quick comment, can you deactivate the auto-trimming of whitespace on you editor

For sure, I noticed only after the push. Should I revert the changes or just keep it in mind for the future? It's only affected empty lines, (except one at 716). I'm willing to take the blame for any of them if they cause any problems ;)

**Comment by Carreau** [comment]
> For sure, I noticed only after the push. Should I revert the changes or just keep it in mind for the future?

Yes, that would be great, it's ok if you don't I think that would be fine. We should probably have something more strict to avoid reintroducing space. But for now that's mostly historical reasons.

Thanks !

**Comment by Igonato** [comment]
>> For sure, I noticed only after the push. Should I revert the changes or just keep it in mind for the future?
>
> Yes, that would be great, ...

"Yes" as "Yes, revert", right? Anyway, done!

**Comment by Carreau** [comment]
Great thanks !

I'm going to guess that affects IPython 5.x as well, worth a backport ? (@takluyver?)

**Comment by Igonato** [comment]
I'm not using IPython under Cygwin very often, so this was the first time I saw the warning, but yeah, whenever this venv detection logic was added, you should be able to safely backport the patch. 

On the other hand, it's just a wrong warning, everything should work just fine. Personally, I wouldn't bother with a backport.

**Comment by Carreau** [comment]
Ok, tagging as 6.1 then. We can still change our minds.

**Comment by Carreau** [comment]
Thanks !

**Pull request merged**
