### PR TITLE
Updated autogen_magics.py to Pathlib Path

### PR DESCRIPTION
**Pull request by digitalvirtuoso**
Found a file (autogen_magics.py) where Pathlib Path could replace os entirely.  Made the changes!

#12515

### CODE REVIEW

**Comment by digitalvirtuoso** [comment]
Can a reviewer kindly review this for Hacktoberfest?  I'd love feedback and am happy to help! :)

**Comment by Carreau** [comment]
Apologies, we've been quite busy, i've marked as "hacktoberfest-accepted" so it should count toward your total even if not merged. Let me know if it's not the case. 

There are conflicts as other pull-request were merged; if you want to try to fix the conflict let me know otherwise I can do that myself – up to you and if you want to learn !

Looking forward to your next contribution.

**Comment by digitalvirtuoso** [comment]
No worries!  Thank you for the reply!  I'd be glad to work on resolving the conflicts.

**Comment by digitalvirtuoso** [comment]
@Carreau Everything should be good to go.  Please advise with anything else recommended, thanks!

**Comment by Carreau** [comment]
THanks !

**Pull request merged**
