### PR TITLE
Fix undefined labels in docs

### PR DESCRIPTION
**Pull request by klonuo**
Fixes for:

```
../ipython/docs/source/interactive/python-ipython-diff.rst:179: WARNING: undefined label: ipython slist (if the link has no caption the label must precede a section header)
../ipython/docs/source/overview.rst:21: WARNING: undefined label: htmlnotebook (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version0.12.rst:101: WARNING: undefined label: htmlnotebook (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version0.12.rst:175: WARNING: undefined label: ssh_tunnels (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version1.0.rst:169: WARNING: undefined label: nbconvert (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version2.0.rst:152: WARNING: undefined label: notebook_security (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version2.0.rst:156: WARNING: undefined label: signing_notebooks (if the link has no caption the label must precede a section header)
../ipython/docs/source/whatsnew/version3.rst:281: WARNING: undefined label: nbformat (if the link has no caption the label must precede a section header)
```

by simply removing non-existing reference labels.

### CODE REVIEW

**Comment by minrk** [comment]
This now conflicts with your other PR

**Comment by minrk** [comment]
If you do rebase this so we can merge it, it would be great if you could do so without including the whitespace changes.

**Comment by klonuo** [comment]
Ok

**Comment by klonuo** [comment]
Hm, I did rebase with master, but it seems there is still conflict with `python-ipython-diff.rst`.
Will check later...

**Comment by minrk** [comment]
Looks like you've added a commit to re-add the whitespace instead of rebasing to remove the deletions. A rebase on master squashing those two commits into one should do it.

**Comment by klonuo** [comment]
I'll close this PR and retry

**Pull request closed without merging**
