### PR TITLE
adapt DisplayHook.quiet() for multiline input

### LINKED ISSUE #4525: Output for semicolon-terminated lines with comments
cf https://github.com/JuliaLang/IJulia.jl/issues/109

The output of a semicolon-terminated line with comment is not suppressed in IPython.

```
b = 1
b; # foo
```
give `Out[13]: 1`
```
b = 1
b;
```
does not.

Havent found such and issue on our tracker.

 @takluyver you are the best with the input machinery and coroutines; Thoughts ?

(Because of the comment @stevengj in sus-cited issue, marking as prio-high, but won't  mind if priority decreased later, or not fixed)

### PR DESCRIPTION
**Pull request by xflr6**
Fixes #4525.

AFAICS [# inside strings](https://github.com/ipython/ipython/issues/4525#issuecomment-38192973) was already resolved by #8505 (and does not require a separate test?).

### CODE REVIEW

**Comment by Carreau** [comment]
Seem ok to me.

Side question: Why is you avatar not a red and white rocket ?

**Comment by xflr6** [comment]
So that only insiders recognize it.. :)

Can this go into 4.2?

**Comment by takluyver** [comment]
Thanks (from an outsider :-( :-P )

**Comment by takluyver** [comment]
And yeah, I see no problem with putting it in 4.2.

**Pull request merged**
