### PR TITLE
fire callbacks on all associated views

### LINKED ISSUE #6534: Same widget does not update all interact.
Cf [Stackoverflow](https://stackoverflow.com/questions/25945543/can-values-from-ipython-widgets-propagate-to-other-cells/25992790#25992790) 

having the same widget (say a Checkbox) shared by 2 interact, the value of the checkbox is updated across cell, but the interactived' function not call. Ex:

capture d ecran 2014-09-24 a 08 30 40

I clicked on first checkbox, second was highligted, but value did not changed from True to False.

### PR DESCRIPTION
**Pull request by minrk**
If a widget is displayed in multiple cells, any output it produces will appear in all cells with a view of the widget.

closes #6534

checkbox mov

ping @jdfreder @ellisonbg

### CODE REVIEW

**Comment by ellisonbg** [comment]
Pinging @jdfreder for review.

I have added a note about this on issue #6534 - the summary is that I am not sure this makes sense for widgets that are in different cells with different overall widget heirarchies. Also need to test how this interplays with the output widget.

**Comment by minrk** [comment]
Yup, this might be crazy. I would be totally okay with closing this *and* #6534, and revisiting it after the repo split.  My initial reaction to #6534 was that it requires an important change to the view/model/output abstraction, so isn't in scope for 3.0. If a simple-ish solution like this doesn't make sense, then I think #6534 shouldn't be addressed in 3.0.

**Comment by ellisonbg** [comment]
Yep, let's see what @jdfreder thinks before closing these - but your
proposal is reasonable.

On Thu, Jan 15, 2015 at 2:32 PM, Min RK <notifications@github.com> wrote:

> Yup, this might be crazy. I would be totally okay with closing this *and*
> #6534 <https://github.com/ipython/ipython/issues/6534>, and revisiting it
> after the repo split. My initial reaction to #6534
> <https://github.com/ipython/ipython/issues/6534> was that it requires an
> important change to the view/model/output abstraction, so isn't in scope
> for 3.0. If a simple-ish solution like this doesn't make sense, then I
> think #6534 <https://github.com/ipython/ipython/issues/6534> shouldn't be
> addressed in 3.0.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7482#issuecomment-70175309>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
Code-wise, looks fine.  I'm going to test to see what happens with output widgets...

**Comment by jdfreder** [comment]
Initial tests made me think it worked well with the output widget, but it looks like the output widget is broken (in master too)... Investigating...

**Comment by ellisonbg** [comment]
Also Jon, at some point we talked about making sure that the output widget
doesn't double-round trip send the output back and forth. Can you check
that while you are at it?

On Mon, Jan 19, 2015 at 1:54 PM, Jonathan Frederic <notifications@github.com
> wrote:

> Initial tests made me think it worked well with the output widget, but it
> looks like the output widget is broken (in master too)... Investigating...
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7482#issuecomment-70568098>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
> Can you check
> that while you are at it?

yup

**Comment by jdfreder** [comment]
Yikes, the Output widget stuff is a disaster...  The original implementation relied on the fact that the comm messages traveled in order with display messages.  Now that the widget messages are asynchronous, this is no longer an assumption that can be made.  I'll open an issue for this.

**Comment by minrk** [comment]
We could also hold OutputWidget for after 3.0, if it doesn't seem like an easy fix.

**Pull request closed without merging**
