### PR TITLE
Document that `%run` can execute notebooks and ipy scripts.

### PR DESCRIPTION
**Pull request by fperez**
This feature has been there for a long time but was not documented in the %run
docstring. This patch only adds documentation, without changing the
functionality.

cc @palewire - thanks for your work on jupyter/nbclient#165 and jupyter/nbclient#173, it motivated me to make my first IPython PR in ages! #13164

### CODE REVIEW

**Comment by palewire** [comment]
Back in the saddle!

**Comment by fperez** [comment]
> Back in the saddle!

We're coming onto the [20th anniversary of the original IPython public announcement](https://mail.python.org/pipermail/python-list/2001-December/093408.html), so might as well at least spin the rusty engine a bit ;)

**Comment by Carreau** [comment]
Thanks ! Marking for backport and restarting the test, failure can't be related, not sure what's happening.

**Comment by Carreau** [comment]
I guess you might not be aware that `$ ipython my_notebook.ipynb` executes the notebooks like a Python file, and that if you add `-i` it drops you in an IPython shell in the same namespace at the end of the execution ?

**Comment by fperez** [comment]
> I guess you might not be aware that `$ ipython my_notebook.ipynb` executes the notebooks like a Python file, and that if you add `-i` it drops you in an IPython shell in the same namespace at the end of the execution ?

Actually I'd totally forgotten this!! I do remember now that you mention it :)

**Comment by fperez** [comment]
And thanks for merging @Carreau :)

**Comment by Carreau** [comment]
No problem. It took some time to fix the issue that was due to python
3.9.8..

Also congrats on your first commit since 2018! I'll properly highlight it
in the release notes.

**Comment by fperez** [comment]
> Also congrats on your first commit since 2018! I'll properly highlight it in the release notes.

That's a pretty sad statement on the current state of my schedule, but I very much appreciate it :)

**Pull request merged**
