### PR TITLE
Fix #11309 (handle quotes in magics arguments)

### LINKED ISSUE #11309: %%writefile can't handle white space in file path/filename
It is as the title suggests. In ipython, I have tried

`%%writefile  "test out.txt"`
`%%writefile  'test out.txt'`
`%%writefile  test out.txt`
`%%writefile  test\ out.txt`

and none gives me the expected behavior. The first one leads to creating a file literally named "test out.txt"  (yes, with quotes). The third one just leads to 

>  unrecognized arguments: out.txt

Is this a bug or am I just missing something obvious? Using IPython 6.5.0 with Python 3.6.5.

### PR DESCRIPTION
**Pull request by hongshaoyang**
fixes #11309 - handles quotes in filename param

### CODE REVIEW

**Comment by mUtterberg** [comment]
@hongshaoyang have you had a chance to look into the CI check failures you're getting?

**Comment by minrk** [comment]
Awesome! Do you think you could write a test for this issue in core/tests/test_completion?

**Comment by hongshaoyang** [comment]
done

**Comment by Carreau** [comment]
Thanks, that looks good to me as well. 

Merging.

**Pull request merged**
