### PR TITLE
Ensure default highlighting is visible in light & dark backgrounds

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-9670

### CODE REVIEW

**Comment by Carreau** [comment]
Ping @fperez who really wanted a stronger coloring on dark background, as on his screen the dark theme + default is close to unreadable

**Comment by Carreau** [comment]
the 3rd option is to add a default 'color' which is "neutral" and make that the default, so that `color=linux` and `color=lightBg` both can **increase** the contrast.

**Comment by fperez** [comment]
Yes, my last comment on #9670 was pretty much what @Carreau said above, I agree with that idea.

**Comment by fperez** [comment]
`linux` and `ligthbg` are really user-optimized "forced dark" or "forced light" background choices and there for backwards compatibility. 

Given the impossibility of doing background detection, I agree with having the default be a reasonable compromise for both.

**Comment by Carreau** [comment]
See #9674 that would likely make everyone happy.

**Comment by takluyver** [comment]
Closing as we merged #9674 instead.

**Pull request closed without merging**
