### PR TITLE
Be more lenient when bytes are sent to stdout/stderr on Py2+Windows

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-9768

@Drekin @zhiyue : can you test this?

### CODE REVIEW

**Comment by Drekin** [comment]
I'm quite busy right now, I'll take a look in a few days.

**Comment by Carreau** [comment]
@Drekin did you had a chance to test that ? If not, @takluyver do you want to still get that in ?

**Comment by takluyver** [comment]
I would still like to get it in, but it needs testing on Windows. I'll reboot my laptop and try it.

**Comment by takluyver** [comment]
In my testing, this does print a replacement `?` instead of giving a big traceback.

**Comment by Carreau** [comment]
> In my testing, this does print a replacement ? instead of giving a big traceback.

Ok, let's merge then.

**Pull request merged**
