### PR TITLE
handle raw video data as input to Video

### PR DESCRIPTION
**Pull request by minrk**
Follow-up on #8326

### CODE REVIEW

**Comment by takluyver** [comment]
Looking at the code already in `Video`, I thought we were going to make it harder than that to embed video data, because that's going to make the notebook unwieldy really fast.

**Comment by minrk** [comment]
This just fixes bugs in the existing implementation. If we want to disable passing data directly, that would be fine, too.

**Comment by takluyver** [comment]
I think the compromise we had agreed was that embedding would require passing `embed=True` explicitly, so that it has to be at least somewhat deliberate.

**Comment by minrk** [comment]
That makes sense. I'll make sure it actually behaves that way (it certainly didn't before).

**Pull request merged**
