### PR TITLE
Replace CUnicodeIO references with StringIO from io package.

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by srinivasreddy** [comment]
@Carreau  Please merge

**Comment by takluyver** [comment]
@srinivasreddy I'm sure you don't intend it this way, but saying "please merge" comes across as a bit entitled. You can ask us to look at your changes (which is implicit when you open a pull request), but it's up to us to decide whether to merge it.

Also, why are you closing and reopening PRs? If the tests need re-running that much, that's a problem that we should try to address. If you're trying to draw attention to your PRs, please leave it out.

**Comment by srinivasreddy** [comment]
@takluyver  Point taken regarding "please merge".  I would write or mention if there is point to convey on PR. Otherwise, i will leave as is - empty. 

Closing and re-opening was done execute on  Appveyor. Anyway, i later realized it does not execute test cases yet.

**Comment by takluyver** [comment]
OK, thanks. I've got some time to do reviewing now.

**Pull request merged**
