### PR TITLE
handle unicode/str in pretty, str formatter

### LINKED ISSUE #7845: Objects with unicode-encoded repr failed to get formatter for printing in list with floats in it.
How to reproduce:

```
class UTest(object):                                                                                                                                                                                                                
    def __repr__(self):
        return unicode(self).encode('utf8')   # returns str object as it should
    def __unicode__(self):
        return u'тест'


In [61]: u = UTest()

In [62]: [u, 123]
Out[62]: [тест, 123]

In [63]: [u, 123.0]
Out[63]: ---------------------------------------------------------------------------
KeyError                                  Traceback (most recent call last)
<ipython-input-63-d76b6d0c9bea> in <module>()
----> 1 [u, 123.0]

/usr/lib64/python2.7/site-packages/IPython/core/displayhook.pyc in __call__(self, result)
    251             self.write_output_prompt()
    252             format_dict, md_dict = self.compute_format_data(result)
--> 253             self.write_format_data(format_dict, md_dict)
    254             self.update_user_ns(result)
    255             self.log_output(format_dict)

/usr/lib64/python2.7/site-packages/IPython/core/displayhook.pyc in write_format_data(self, format_dict, md_dict)
    172         # newline, even if all the prompt separators are ''. This is the
    173         # standard IPython behavior.
--> 174         result_repr = format_dict['text/plain']
    175         if '\n' in result_repr:
    176             # So that multi-line strings line up with the left column of

KeyError: 'text/plain'


## looks like we don't have 'text/plain' in format_dict, lets check it
In [64]: from IPython.core.formatters import DisplayFormatter

In [65]: d = DisplayFormatter()

In [66]: d.format([u, 123.0])
Out[66]: ({}, {})

In [67]: d.format([u, 123])
Out[67]: ({u'text/plain': '[\xd1\x82\xd0\xb5\xd1\x81\xd1\x82, 123]'}, {})

In [68]: d.format({123.0: u})                                                                                                                                                                                                          
Out[68]: ({}, {})

In [69]: d.format({123: u})
Out[69]: ({u'text/plain': '{123: \xd1\x82\xd0\xb5\xd1\x81\xd1\x82}'}, {})

```

Well, that's it, formatter returns empty format_dict specifically for object with unicode-encoded repr and float number in lists and dicts.
I tested this on 2.2.0, 2.3.0, 2.4.0, they all affected.

### PR DESCRIPTION
**Pull request by minrk**
by casting str to unicode on Python 2

need to do some more thorough testing to see if this doesn't bork anything.

closes #7845

### CODE REVIEW

**Comment by takluyver** [comment]
That looks reasonable, but I assume it's for 3.1 now.

**Comment by minrk** [comment]
definitely, or even 4.0

**Comment by Carreau** [comment]
Both are fine with me.

**Comment by takluyver** [comment]
What testing should we be doing with this. Do we want to aim it for 3.1 or 4.0?

**Comment by minrk** [comment]
I should at least add some tests that cover containers of mixed str/unicode, in case this affects any of the `''.join`-type calls inside.

**Comment by ellisonbg** [comment]
I will test this soon. Because multiple users are hitting this for fairly plain vanilla pandas work, I think getting this in 3.1 is pretty important. Is there any particular reason we would push back to 4.0?

**Comment by minrk** [comment]
Just because it's a relatively sensitive bit of code with potentially lots of mixed unicode and str on Python 2. It *shouldn't* cause any new encoding errors, but that doesn't mean it doesn't.

**Comment by ellisonbg** [comment]
Ahh, OK. When are we thinking for 3.1?

On Fri, Mar 6, 2015 at 3:38 PM, Min RK <notifications@github.com> wrote:

> Just because it's a relatively sensitive bit of code with potentially lots
> of mixed unicode and str on Python 2. It *shouldn't* cause any new
> encoding errors, but that doesn't mean it doesn't.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7853#issuecomment-77656296>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
We are thinking of 3.1 by the end of the month.

**Comment by parente** [comment]
The bug was biting me locally in a large dataframe with lots of non-ascii chars. I applied the patch and worked in that dataframe and others for a few hours today. I didn't see any problems. So, some evidence, at least, that the changes are OK.

**Pull request merged**
