### PR TITLE
Move to Github Actions

### PR DESCRIPTION
**Pull request by MrMino**
#12694

To do:
- [ ] nightly?
- [x] docs
- [x] `check-manifest`
- [x] `fixup_whats_new_pr.py`
- [x] OSx
- [x] ?deploy? stuff
- [x] `iptest`
- [x] `pytest`

### CODE REVIEW

**Comment by MrMino** [comment]
Aaand it failed on 

```
ERROR: IPython.core.tests.test_magic.test_script_out_err
...
subprocess.CalledProcessError: <unprintable CalledProcessError object>
```

Looks like the knownfail from earlier?

**Comment by takluyver** [comment]
The failure you mentioned seems to be #12692; I think I've fixed it (roughly).

**Comment by takluyver** [comment]
I think this is ready-ish now.

The one part definitely missing compared to the Travis setup is checking on Python 'nightly'. This is an allowed failure in Travis, but Github actions has no equivalent of that, and I've never really been convinced that allowed failures are useful anyway - my experience is that they're ignored.

There's some complication in the Travis config for OSX that I haven't copied (installing a Python framework with Homebrew). I'm guessing that that isn't necessary on GHA - it seems to work without it.

For now, I've put the creation of Github releases in a separate workflow from the tests. This keeps things simple, but it will make the release even if the tests fail, which may or may not be what you want. Hopefully by the point a tag is pushed, you're confident in it anyway, and if there's a rare random failure you don't necessarily want it to interrupt the automation. But obviously that can be rearranged if you prefer. [Here are the docs for the gh-release action](https://github.com/marketplace/actions/gh-release) which I used.

**Comment by takluyver** [comment]
(PS: I'll try to keep an eye out for comments, but anyone should feel free to take the branch over - especially in time zones where you can carry on while I'm asleep :-)

**Comment by minrk** [comment]
You're definitely right that the framework Python isn't needed because GHA's setup-Python works on mac, unlike Travis.

I also don't think we need nightly Python, at least not before merging.

**Review by minrk — APPROVED** [review]

**Comment by Carreau** [comment]
Thanks, all, let's get that in, and try if that backports cleanly on stable.

**Pull request merged**
