### PR TITLE
Fix the mode indicator width.

### LINKED ISSUE #7652: #modal_indicator constant width ?
the edit/command mode indicator, even if show "nothing" on command mode, should have the same width to avoid notification messages to move around.

### PR DESCRIPTION
**Pull request by jdfreder**
Use fa-fw to set the fixed width of the icon.

closes #7652 
alternative to #7663

@minrk who wanted an alternative.
@Carreau and @ellisonbg for design review.

### CODE REVIEW

**Comment by minrk** [comment]
I think this is better, thanks.

**Comment by minrk** [comment]
Confirmed this has the desired behavior, thanks. Did you mean to include the "Remove accident" commit?

**Comment by jdfreder** [comment]
Yeah, it just removes an added blank line which was accidental.  Since I commit `invoke css` separate to my other changes, I was unable to quickly `git commit --amend` to fix the first commit.

**Comment by minrk** [comment]
@jdfreder that's what the `fixup` command in `git rebase -i` is for! It's like `--amend` for commits other than the most recent.

**Comment by minrk** [comment]
In any case, :+1: to merge. You don't need to rewrite history.

**Comment by jdfreder** [comment]
> that's what the fixup command in git rebase -i is for!

I've never used that command before :P  Next time...

**Pull request merged**
