### PR TITLE
TEST: Move test_escape_root to TestFileContentsManager

### PR DESCRIPTION
**Pull request by ssanderson**
The tests for [pgcontents](https://github.com/quantopian/pgcontents) assume that `TestContentsManager` is written against only the public API of the ContentsManager base class. The `root_dir` attribute is specific to the FileContentsManager implementation.

### CODE REVIEW

**Comment by ssanderson** [comment]
ping @minrk.  I'm looking at upgrading pgcontents to be properly 3.0 compatible, and test_escape_root is  the only test I have left failing.

**Comment by Carreau** [comment]
Relaunched tests.

**Comment by Carreau** [comment]
+1

**Comment by minrk** [comment]
Yup, sorry about that.

**Pull request merged**
