### PR TITLE
How to install 1.x using pip

### PR DESCRIPTION
**Pull request by diimdeep**
It's possible, but not stated and obvious because old versions hidden in pypi listing

### CODE REVIEW

**Comment by takluyver** [comment]
Meh...I think our install page is already too long, and I don't think it's our job to explain how to use standard installation tools.

**Comment by Carreau** [comment]
Agreed with Thomas, technically I would just drop the note about the `archive.ipython.org` and just state that for python 2.6 you are limitted to 1.x series.

**Comment by diimdeep** [comment]
[Afaik](https://bitbucket.org/pypa/pypi/issue/52/website-should-list-all-versions-of-a#comment-5915082) there is way to individually unhide version, imho 1.2.1 should be visible as latest 1.x, then maybe no need to mention in doc.

**Comment by diimdeep** [comment]
Unhide here https://pypi.python.org/pypi/ipython

**Comment by Carreau** [comment]
The request to unhide 1.2.1 seem reasonable. I'm no owner on PyPi though.

**Comment by diimdeep** [comment]
@fperez @minrk @ellisonbg

**Comment by minrk** [comment]
1.2.1 is unhidden on PyPI

**Comment by takluyver** [comment]
Actually, I'm -1 on that as well. When only one version is visible (as is almost always the case, except when we're doing betas/RCs), https://pypi.python.org/pypi/ipython goes directly to the normal description and overview page for that version. When multiple versions are visible, that URL instead goes to the rather ugly 'Index of Packages' page that it currently shows.

**Comment by fperez** [comment]
Agree with @takluyver

**Comment by diimdeep** [comment]
Isn't ability to discover versions > ugly page ? Seems like next pypi will not have this problem, there is widget on right with versions https://warehouse.python.org/project/ipython/ https://github.com/pypa/warehouse

**Comment by takluyver** [comment]
I think the ugly page is worse until the new version of PyPI lands (anyone know when that's likely?).

We don't really want to encourage people to use 1.x, it's only if you are stuck on an old version of Python for some reason. And in that scenario, I think it's fine to expect you to know things like how to install an older version using pip.

**Comment by Carreau** [comment]
> (anyone know when that's likely?).

Not soon. Have proposed to contribute, but needed PG dump. Asked 2 month ago. Still no response. 

Feel free to revert showing 1.2.1 if you like.

**Comment by takluyver** [comment]
I'll leave it for now, since the 3.0 release candidate means the ugly page is shown anyway. When we release 3.0 final I'll hide 1.2.1 again unless we decide otherwise.

**Comment by fperez** [comment]
I'd suggest putting a link on the README to that Warehouse page, indicating that old versions can be found there. That lets anyone easily find the other ones, without uglifying the main page.

**Comment by minrk** [comment]
The install doc now mentions `pip install 'ipython<2'

**Pull request closed without merging**
