### PR TITLE
Sphinxify

### LINKED ISSUE #9513: Get the DocRepr functionality hidden behind a flag.
Ping @SylvainCorlay Marking as 5.0 to not forget.

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes #9513 : Putting the docrepr functionality behind a flag.

### CODE REVIEW

**Comment by Carreau** [comment]
Great thanks.

**Comment by SylvainCorlay** [comment]
Putting in the flag. 1 sec.

**Comment by Carreau** [comment]
No hurry.  we've got a few bug reports for the beta, so I have plenty to do today.

**Comment by Carreau** [comment]
`ip.sphinxify_docstring` seem  to have no effect, but I can't figure out why. 
```
ip = get_ipython()
ip.sphinxify_docstring, ip.enable_html_pager = False, True # or True, True give the same. 
import numpy as np
np.histogram??
```

Can't figure out why.

**Comment by Carreau** [comment]
> Can't figure out why.

My bad I was testing with `??` intead of `?`, and  then yes it works.

**Comment by SylvainCorlay** [comment]
Interestingly, in `??` the syntax coloring for the source works even when `enable_html_pager` is True.

**Comment by ccordoba12** [comment]
@SylvainCorlay, thanks for taking the time to keep working on this one. I'm glad to see that this could be added to 5.0 :-)

@Carreau, do you still need the PR you submitted to `docrepr`?

**Comment by Carreau** [comment]
> Interestingly, in ?? the syntax coloring for the source works even when enable_html_pager is True.

Yeah, thats because we color with Ansi escape sequence, and the frontend turn that to css-classes on the fly.

**Comment by Carreau** [comment]
> @Carreau, do you still need the PR you submitted to docrepr?

Not for now, no. thi works with the released version of docrepr.

**Comment by Carreau** [comment]
Will send PR with some documentation and a few additions.

**Comment by Carreau** [comment]
Made a PR against this: https://github.com/SylvainCorlay/ipython/pull/4

**Comment by SylvainCorlay** [comment]
The test failure seems legitimate.

**Comment by Carreau** [comment]
> The test failure seems legitimate.

Yep forgotten debug statement. New PR on your repo.

**Comment by Carreau** [comment]
Ok, I'm going to merge that, and get the flags in a separate PR.

**Comment by SylvainCorlay** [comment]
Thanks i am ok with the other change. Was just afk.

**Comment by minrk** [comment]
ipykernel tests found a couple of small regressions, fixed in #9576.

**Pull request merged**
