### PR TITLE
Refactor with Pathlib for setupbase.py

### PR DESCRIPTION
**Pull request by kevin1kevin1k**
Continued efforts for #12515 though it has been closed.

Validated to be okay by running the following.
- `pip install -e ".[all]"`
- `pytest`

Please note that there are also some syntactical modifications, and part of them are from the darker linter.

### CODE REVIEW

**Comment by kevin1kevin1k** [comment]
Now I see some failing checks. Fixing them.

**Comment by kevin1kevin1k** [comment]
The remaining failing check `test_run_concurrently_sequence` seems to be irrelevant to this change

**Comment by kevin1kevin1k** [comment]
@Carreau Please have a look, thanks. Also let me know if I should first squash the commits into one or it's okay to leave them as is.

**Comment by Carreau** [comment]
Thanks, it's ok to leave as is. I rebased as test were failing for a unrelated reason.

**Pull request merged**
