### PR TITLE
Don't install numpy to test on Python 3.3

### PR DESCRIPTION
**Pull request by takluyver**

### CODE REVIEW

**Comment by takluyver** [comment]
Looking at the Travis logs, it didn't try to install numpy on Python 3.3 or 3.4. Not sure why. But the tests are at least passing.

**Comment by takluyver** [comment]
A pip upgrade got it to try installing, but there aren't numpy wheels for Python 3.3, and I don't want it to compile numpy on every build. I will drop numpy from the test requirements on Python 3.3.

**Comment by takluyver** [comment]
That's passing on Travis. I'll merge this now to get the tests working again.

**Comment by Carreau** [comment]
@meeseeksdev backport to 5.x

**Pull request merged**
