### PR TITLE
[WIP] - Set up automatic release notes

### PR DESCRIPTION
**Pull request by augustogoulart**
@Carreau Recently I've got to know about automating release notes using GitHub actions.
Based on what we discussed a long ago, this is something you or someone else needs to take care of every month. 

Are you interested in automating that?

I'm playing around with this action specifically, but there are many other options:
https://github.com/marketplace/actions/release-notes-generator-action

### CODE REVIEW

**Comment by Carreau** [comment]
I'm happy to try that ! That would be nice. I'll have a look soon, I might do a release on Friday.

**Comment by Carreau** [comment]
Let's try.

**Comment by Carreau** [comment]
Failed with:

```
20:33:13.074 [main] ERROR org.springframework.boot.SpringApplication - Application run failed
java.lang.IllegalArgumentException: Invalid argument syntax: --releasenotes.github.password=
	at org.springframework.core.env.SimpleCommandLineArgsParser.parse(SimpleCommandLineArgsParser.java:75)
	at org.springframework.core.env.SimpleCommandLinePropertySource.<init>(SimpleCommandLinePropertySource.java:90)
	at org.springframework.boot.DefaultApplicationArguments$Source.<init>(DefaultApplicationArguments.java:76)
	at org.springframework.boot.DefaultApplicationArguments.<init>(DefaultApplicationArguments.java:42)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:304)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1260)
	at org.springframework.boot.SpringApplication.run(SpringApplication.java:1248)
	at io.spring.releasenotes.Application.main(Application.java:35)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.springframework.boot.loader.MainMethodRunner.run(MainMethodRunner.java:48)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:87)
	at org.springframework.boot.loader.Launcher.launch(Launcher.java:50)
	at org.springframework.boot.loader.JarLauncher.main(JarLauncher.java:51)
```

**Comment by augustogoulart** [comment]
It seems to be something within the action library. Maybe due to Yesterday's (27 Feb 2020) outage:
https://www.githubstatus.com/

I'll troubleshoot this over the weekend

**Pull request merged**
