### PR TITLE
Prevent popup windows during execution of latex_to_png_dvipng

### PR DESCRIPTION
**Pull request by eendebakpt**
The exectution of `latex_to_png_dvipng` causes popup windows. This PR prevents that by setting flags to the `subprocess.check_call`.

Idea was suggested in https://github.com/jupyter/qtconsole/issues/542#issuecomment-1136297850

### CODE REVIEW

**Review by ccordoba12 — APPROVED** [review]
Thanks @eendebakpt!

**Comment by MrMino** [comment]
@eendebakpt Can you add a whats-new entry describing the user-facing implications of this change?

**Comment by eendebakpt** [comment]
@

> @eendebakpt Can you add a whats-new entry describing the user-facing implications of this change?
> 
> See https://github.com/ipython/ipython/tree/master/docs/source/whatsnew/pr

@MrMino Done. 

One test is still failing. Perhaps not related to this PR. If it is, then I need some more information what is the problem

**Comment by eendebakpt** [comment]
@MrMino or @ccordoba12 You you review this PR once more please?

**Review by ccordoba12 — APPROVED** [review]
Looks good to me, thanks @eendebakpt!

Note: The failures in the test suite seem unrelated to this.

**Comment by eendebakpt** [comment]
@ccordoba12 Is there anything that needs to be done to merge this?

**Pull request merged**
