### PR TITLE
replace undefined by empty string to get aroung bug in ie

### LINKED ISSUE #8161: undefined windows
in IE, new/duplicate open undefined windows that refresh.

### PR DESCRIPTION
**Pull request by Carreau**
Could close #8161 ...need to test.

### CODE REVIEW

**Comment by Carreau** [comment]
Works locally.

**Comment by minrk** [comment]
Missing one in tree/js/notebooklist

**Comment by Carreau** [comment]
Done.

**Comment by minrk** [comment]
Verified fix with IE 11, and still fine on Chrome. Will merge once green light confirms.

**Comment by takluyver** [comment]
I thought we heard yesterday that it was fine on IE11 even without this fix, and it was IE 10 that was the problem. I'll see if I have IE10 on my Windows 7 VM.

**Comment by takluyver** [comment]
Nope, I have IE11 as well. I think it's fine to assume that this fix will work and merge away - it doesn't seem to break anything, at least.

**Comment by minrk** [comment]
I could see the 404 page on my IE in master and not in this PR, so it definitely fixes it for at least one version of IE.

**Pull request merged**
