### PR TITLE
Allow predictate to be used for comparison in selection widgets

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Meant to solve #7673. Let me know what you think.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
In the case of a numpy array, one can use `np.array_equal`.

**Comment by minrk** [comment]
Isn't there a much larger issue related to the trait change events and numpy arrays?

**Comment by SylvainCorlay** [comment]
@minrk done. I don't think that the failed test is related with my change.

**Comment by minrk** [comment]
@SylvainCorlay no, definitely not related. I'll wait for Travis to double check, then merge. Thanks!

**Comment by minrk** [comment]
Thanks

**Pull request merged**
