### PR TITLE
enable formatting by default

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by luzfcb** [comment]
How to disable this feature permanently, globally?

**Comment by adamchainz** [comment]
I've started a new issue for discussion, with PR: #13463

**Comment by ayhanfuat** [comment]
One other option might be making it easier to disable formatting (especially when used in education). Maýbe something like `%disable_black`?

**Comment by SimonBiggs** [comment]
I'd like to add in some encouragement. Thank you for all of your hard work @Carreau. We really appreciate IPython and everything you do to make it happen :slightly_smiling_face:. Thank you. I don't have a horse in this particular race... but... I thought it was important to say thank you, and counter some of the criticism that is going on around this.

Thanks @Carreau :slightly_smiling_face:.

**Pull request merged**
