### PR TITLE
Use Travis to upload to GitHub releases

### PR DESCRIPTION
**Pull request by takluyver**
See gh-10342

### CODE REVIEW

**Comment by takluyver** [comment]
Milestoned for 6.0 - because IPython doesn't use universal wheels, this gets more complicated if we try to backport it to use with 5.x, because two different versions of Python would need to upload files.

**Comment by Carreau** [comment]
Hum I thought we stopped uploading to GH since the submodules craziness
but +1..

**Comment by Carreau** [comment]
Well actually, will the travis and locally built sdist ~~have the same sha1~~ be identical

**Comment by takluyver** [comment]
I doubt they'll be identical. Even if we [use Travis to upload to PyPI](https://docs.travis-ci.com/user/deployment/pypi/) too, it looks like the PyPI deployment thing builds distributions itself, so I don't know if it would produce identical packages.

**Comment by Carreau** [comment]
> I doubt they'll be identical. Even if we use Travis to upload to PyPI too, it looks like the PyPI deployment thing builds distributions itself, so I don't know if it would produce identical packages.

hum, ok. Fair enough. I'm happy with this for now. Merging ?

**Comment by takluyver** [comment]
Let's see how it goes.

**Pull request merged**
