### PR TITLE
static message instead of function call to prevent shell slowdown

### PR DESCRIPTION
**Pull request by gerrit8143**
#11496

### CODE REVIEW

**Comment by Carreau** [comment]
Hum, unlike what I said in #11496 his actually breaks the prompt when using vi mode for example. 
Vi mode (`$ ipython --TerminalInteractiveShell.editing_mode=vi`) shows in the prompt wether we are in insert or normal mode. 

So we'll have to a be a bit smarter as to wether we compute this once, or regularly.

**Comment by Carreau** [comment]
I've push some changes on your brnach that shoudl fix the high number of call with the default mode, but keep the changing prompt when using vi keybinding. Let me know what you think.

**Comment by gerrit8143** [comment]
looks good to me, so let's do it that way.

**Comment by Carreau** [comment]
> looks good to me, so let's do it that way.

Thanks, I'll update the whats new note when I have time and then merge. 
Should be released by end of month.

**Pull request merged**
