### PR TITLE
Remove configure_inline_support function

### PR DESCRIPTION
**Pull request by martinRenou**
This removes a circular dependency between ipykernel and IPython.

This PR is coupled with another PR in ipykernel adding the function there: https://github.com/ipython/ipykernel/pull/590

It goes in the direction of cleaning the ipykernel/IPython/matplotlib relationship, see https://github.com/ipython/ipykernel/issues/588

### CODE REVIEW

**Comment by martinRenou** [comment]
This is backward incompatible for ipykernel.

**Comment by Carreau** [comment]
This conflict with master for whitespaces. 
what do you think the best approach is ? peek at the version number of ipykernel and not call this logic if it can't be imported / is recent enough ?

**Comment by martinRenou** [comment]
Yep I guess this could be good. I will apply this and rebase.

**Comment by martinRenou** [comment]
I am closing this PR. This cleanup is done in https://github.com/ipython/ipython/pull/12817.

**Pull request closed without merging**
