### PR TITLE
Fix completions for PTK 1.0

### PR DESCRIPTION
**Pull request by Carreau**
Hotfix for #9440, that we should look at in in more details. 

Congratulation @jonathanslenders on PTK 1.0.

### CODE REVIEW

**Comment by fperez** [comment]
I can confirm that this fixes the problem. Thanks for the quick turnaround!

**Comment by fperez** [comment]
I've merged it as-is, since the code looks clean and it does fix a problem that made some completions not work at all. If a more refined fix is required, further PRs welcome.

Thanks @Carreau!

**Comment by anntzer** [comment]
Attribute completions (`obj.<tab>`) seem to be broken for me.

**Comment by Carreau** [comment]
> Attribute completions (obj.<tab>) seem to be broken for me.

Can you give a more detailed example ?

screen shot 2016-05-09 at 12 04 06

Do you have Jedi installed ?

**Comment by anntzer** [comment]
Oh, I didn't realize that jedi was a dependency for object completion now (AFAICT it wasn't one until the update to PTK 1.0).  Sorry for the noise.

**Comment by takluyver** [comment]
The Jedi completion stuff happened to land around the same time as the PTK 1.0 update - they're not particularly related.

**Pull request merged**
