### PR TITLE
Add support for autoformatting using yapf

### PR DESCRIPTION
**Pull request by algmyr**
I have my personal ideological issues with Black's opinionated formatting, so I made the small necessary change to add support for yapf as a formatter. I'm all for having many options for this. :)

Thankfully the option was already general enough that the addition was very simple, so good design work there!

### CODE REVIEW

**Comment by algmyr** [comment]
I suspect the formatting check is a false positive? Using single quotes matches the existing code.

**Comment by bollwyvl** [comment]
> I suspect the formatting check is a false positive? 

`darken`'s is set up such that all new changes _do_ conform to this repo's target of conforming to a stock `black` configuration... in this case, double quotes.

ideally, we'd have a bot that just applied these changes, rather than breaking the build: i suppose.

**Comment by algmyr** [comment]
> > I suspect the formatting check is a false positive?
> 
> `darken`'s is set up such that all new changes _do_ conform to this repo's target of conforming to a stock `black` configuration... in this case, double quotes.
> 
> ideally, we'd have a bot that just applied these changes, rather than breaking the build: i suppose.

So what do you prefer? Make `darken` happy but be inconsistent or make `darken` sad but be consistent? My own 2c would be to keep it consistent and the quote style change can be done at a later stage in some larger scale refactoring.

**Comment by bollwyvl** [comment]
says right in the log:

```
 Changes need auto-formatting. Run:
    darker -r 60625f241f298b5039cb2debc365db38aa7bb522
then commit and push changes to fix.
```

**Comment by algmyr** [comment]
> darker -r 60625f241f298b5039cb2debc365db38aa7bb522

`darker` is broken locally for me https://github.com/akaihola/darker/issues/264 and I'm not so keen on setting up a venv just for this, I'll just manually fix the one line that it complains about.

**Comment by Carreau** [comment]
Thanks, sorry about the issue with formatting.

**Pull request merged**
