### PR TITLE
Add Handling of cursor_end in Console Completer

### LINKED ISSUE #6690: ipython console ignores cursor_start and cursor_end on complete_reply messages
Here is a minimal example using commit dbd30bf using Anaconda 3.4 64bit on Linux 17:

```python
from IPython.kernel.zmq.kernelbase import Kernel

__version__ = '1'


class TestKernel(Kernel):
    implementation = 'test_kernel'
    implementation_version = __version__
    language = 'test'
    language_version = __version__
    banner = ''

    def do_complete(self, code, cursor_pos):

        matches = [code[1:] + '_complete']

        return {'matches': matches, 'cursor_start': 1,
             'cursor_end': cursor_pos, 'metadata': dict(),
                'status': 'ok'}

    def do_execute(self, code, silent, store_history=True, user_expressions=None, allow_stdin=False):
        return {'status': 'ok', 'execution_count': self.execution_count,
                    'payload': [], 'user_expressions': {}}

if __name__ == '__main__':
    from IPython.kernel.zmq.kernelapp import IPKernelApp
    IPKernelApp.launch_instance(kernel_class=TestKernel)
```

In one terminal, launch this file as `python test_kernel.py`.  In another tab, run `ipython console --existing ...`.  At the prompt type `test<TAB>`.  We expect to get `test_complete`, but instead we get `est_complete`.

### PR DESCRIPTION
**Pull request by blink1073**
Closes #6690.  Extends #7497 and implements #6714.

### CODE REVIEW

**Comment by blink1073** [comment]
Any idea how to get rid of the change in `static.components`?  I tried a `git submodule update`.

**Comment by takluyver** [comment]
This appears to break all completions in `ipython console` for me.

**Comment by blink1073** [comment]
Ha, that will happen when you forget to return the matches.

**Comment by takluyver** [comment]
Pulled the branch again, still not getting any completions.

Not sure how the components change got in there - don't add that change when you commit, and it shouldn't show up in the PR.

**Comment by blink1073** [comment]
Okay, completions are working on my end now.  I still can't shake the submodules change.

**Comment by blink1073** [comment]
Note that the #7497 merge still suffers from part of the problem that stumped me in #6714, in that the whole line is shown for completions (at least its not the whole buffer anymore).

**Comment by takluyver** [comment]
I don't know that we can easily avoid that given the way readline works.

This seems to be working now, but you'll still need to rebase and remove the components change.

**Comment by blink1073** [comment]
Done!

**Comment by takluyver** [comment]
Thanks, I think this looks good now, but I'll let someone else have a look over it before merging.

**Comment by minrk** [comment]
@blink1073 can you provide an example this improves?

**Comment by minrk** [comment]
This makes sense to me, I just can't think of a case where cursor_end would be less than cursor_start. That would mean triggering a completion that changes some part of the line that doesn't involve the cursor, leaving the area where the completion was triggered unmodified. Maybe a non-Python kernel does this?

**Comment by Carreau** [comment]
> I just can't think of a case where cursor_end would be less than cursor_start

julia ? where `foo.method()` is `method(foo)` and you might want `foo<tab>` ?

**Comment by minrk** [comment]
@Carreau I don't think that's an example, unless I'm misunderstanding. cursor_end and cursor_start bound the part of the *current* cell that are to be replaced. So only if the cursor is *entirely outside* the replacement should this be the case.

**Comment by blink1073** [comment]
@minrk, I don't have a real world example, this was about implementing the full API and aligning with the behaviour of the QtConsole and the Notebook.   @dsblank, can you think of a good example where we'd want to set `cursor_end` to a value less than `cursor_pos`?

**Comment by minrk** [comment]
Makes sense, anyway. Merging away.

**Pull request merged**
