### PR TITLE
Correctly teardown test case, avoid filehandle leaking.

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by takluyver** [comment]
Nice one, those warnings have been bothering me for a while. Just not enough to actually do anything about them. ;-)

**Comment by Carreau** [comment]
> Nice one, those warnings have been bothering me for a while. Just not enough to actually do anything about them. ;-)

Yeah, I'm on fire this week. I tracked a few crazy bugs, where it was literally adding a print statement every 2 lines. 

I'm considering writing a tool that wrap every statement in the AST with a user provided function that stop in a debugger as soon as a specific assumption is false.

**Comment by takluyver** [comment]
Rather than doing it on the AST, I wonder if you could use [sys.settrace](https://docs.python.org/3/library/sys.html#sys.settrace), which is the same underlying API that debuggers plug into.

**Comment by Carreau** [comment]
Hummmmmmmm....
Maybe, though they say that trace function is invoked when a new local
scope is entered, seem to be a bit unclear when which function is called on
which line.

I'll investigate.

**Pull request merged**
