### PR TITLE
removed Ipython.utils.warn

### PR DESCRIPTION
**Pull request by ghost**
I have removed warn.py from Ipython.utils folder. 
Issue: Remove `IPython.utils.warn` #9248

### CODE REVIEW

**Comment by jasongrout** [comment]
Thanks! As mentioned in https://github.com/ipython/ipython/issues/9248#issuecomment-240842234, can you:

> add a file in docs/source/whatsnew/ [for the 6.0 what's new] that says something along the line of IPython.utils.warn was deprecated in IPython 4.0, and has now been removed.

**Comment by jasongrout** [comment]
(You could copy over the what's new file for 5.x, delete the content, and use it as a template for a new file for 6.x)

**Comment by thesageinpilani** [comment]
Thank you sir, for your feedback, i have added version6.rst , if there is anything wrong regarding version6.rst or if i have to add more information. please tell me.

**Comment by takluyver** [comment]
@jasongrout, for IPython we ask contributors to add a file in `docs/source/whatsnew/pr` with a snippet summarising what they've done, then we run a script in `tools` to assemble them before release. This avoids PRs conflicting just because of additions to a single whatsnew file. I think @Carreau forgot to mention this.

**Comment by thesageinpilani** [comment]
sir, i have created an .rst file documenting changes in docs/source/whatsnew/pr with a snippet summarising what i have done, thanks to @Carreau please comment about this.

**Comment by takluyver** [comment]
Thanks @thesageinpilani . This looks fine to me now, but I'll let @Carreau take a look.

**Comment by thesageinpilani** [comment]
Thankyou, sir

**Comment by Carreau** [comment]
Thanks you @thesageinpilani ! Sorry I have been away at [pybay](http://www.pybay.com/) until tonight and I am teahcing tomorrow, but that's looks good to me !

@takluyver ; How do you feel about merging all the 5.2 Prs, and start to for the 5.x branch ?

**Comment by takluyver** [comment]
> How do you feel about merging all the 5.2 Prs, and start to for the 5.x branch ?

Start to backport? Go ahead. Be aware that we have already merged some 6.0 PRs (mine specifying the Python 3 requirement), so we can't just re-branch 5.x again.

**Comment by Carreau** [comment]
> Start to backport? Go ahead. Be aware that we have already merged some 6.0 PRs (mine specifying the Python 3 requirement), so we can't just re-branch 5.x again.

Yeahhh I missed this one Thanks !

**Pull request merged**
