### PR TITLE
FIX: Typing annotations

### PR DESCRIPTION
**Pull request by farisachugthai**
Running `mypy -p IPython.sphinxext` raised a few errors. Fix them and strip some trailing whitespace from a few places.

### CODE REVIEW

**Comment by farisachugthai** [comment]
Sorry I got messed up by darker again. What is a good way of running and/or fixing this in advance? You won't know what the SHA for a commit is until after you do it, so running `darker -r <SHA>` like how it's run in the tests doesn't seem like it'd work.

**Comment by Carreau** [comment]
You can either run just `darker` before comiting or, run `darker -r 60625f241f298b5039cb2debc365db38aa7bb522` always with this hash for IPython, Otherwise don't worry I'll run it.

**Comment by farisachugthai** [comment]
Okay thank you! I'll make sure I do so because I've ran into this a few times and I don't wanna make extra work for you haha

**Comment by Carreau** [comment]
It took w while but thanks, merging.

**Pull request merged**
