### PR TITLE
remove notebook

### PR DESCRIPTION
**Pull request by minrk**
Testing IPython no longer requires installing any Jupyter packages.
The notebook-specific testing and setup code should also be removed.

I think there are still a few tests that need updating, but it's almost there.
The `jupyter_notebook` package is working, with js tests passing.

### CODE REVIEW

**Comment by minrk** [comment]
Tests passing, phase Ⅰ of the big split complete.

**Comment by rgbkrk** [comment]
:tada:

**Comment by jhamrick** [comment]
:cake:

**Comment by damianavila** [comment]
:+1:

**Pull request merged**
