### PR TITLE
terminal: Fix IndexError when attempting to elide paths with empty components

### PR DESCRIPTION
**Pull request by d3dave**
When attempting to elide a path string that contains empty components we get an error:

```console
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/ptutils.py", line 115, in get_completions
    cursor_position = document.cursor_position
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/ptutils.py", line 162, in _get_completions
    if c.type == 'function':
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/ptutils.py", line 77, in _elide
    _elide_point(string, min_elide=min_elide),
  File "/usr/local/lib/python3.10/site-packages/IPython/terminal/ptutils.py", line 57, in _elide_point
    return ('{}' + os.sep + '{}\N{HORIZONTAL ELLIPSIS}{}' + os.sep + '{}').format(file_parts[0], file_parts[1][0], file_parts[-2][-1], file_parts[-1])
IndexError: string index out of range
```

Example string: `//tmp/TemporaryDirectory.G90DrY/`. The `file_parts` for this string are: `['', '', 'tmp', 'TemporaryDirectory.G90DrY']`.

Solution: Don't attempt to elide if the middle components are empty.

### CODE REVIEW

**Comment by drorspei** [comment]
Hey! I was just hitting this bug.
For long strings it's still nice to elide.
I propose a different solution, to use slicing instead:
```
return '{}.{}\N{HORIZONTAL ELLIPSIS}{}.{}'.format(object_parts[0], object_parts[1][:1], object_parts[-2][-1:], object_parts[-1])
```
and similar for the file parts line.

**Comment by MrMino** [comment]
Hi @d3dave. Thanks for sending the PR!

Could you please provide an example of where you are hitting this bug? The codebase is quite large and without repro steps it is prohibitively expensive time-wise to review PRs, even ones with as little changes as yours.

Also, could you please comment on what @drorspei proposed?

**Comment by d3dave** [comment]
@MrMino:

> Could you please provide an example of where you are hitting this bug? 

When I type: `s = 'file:///var/log/<TAB>` to autocomplete a local path I hit the exception above.

@drorspei Thanks, done 👍

**Comment by MrMino** [comment]
Oh, I get it now.

Cool! Could you please also include a [what's-new](https://github.com/ipython/ipython/tree/master/docs/source/whatsnew/pr) entry for this PR, that explains what changed from the PoV of the user?

**Comment by d3dave** [comment]
@MrMino added.

**Pull request merged**
