### PR TITLE
Update backport instructions just to see if autobackport works.

### PR DESCRIPTION
**Pull request by Carreau**
@takluyer, want to merge to see if autobackport get triggerd ?

### CODE REVIEW

**Comment by takluyver** [comment]
Nice! Stand by for test in 3, 2, 1...

**Comment by takluyver** [comment]
Well, it tried ;-)

**Comment by Carreau** [comment]
Great ! let's just change the milestone, i'm lazy.

**Comment by Carreau** [comment]
There was actually a bug, it was not able to apply the Labels. But that should be fixed now.

**Pull request merged**
