### PR TITLE
Bugfix: when doing \dot completion. Compose unicode character from completion.

### PR DESCRIPTION
**Pull request by jonathanslenders**
See: https://github.com/ipython/ipython/issues/9376#issuecomment-206464016

### CODE REVIEW

**Comment by Carreau** [comment]
Works with `\dot`, but not with `\ddot` which is invisible...

**Comment by Carreau** [comment]
Ok.. there is no combined form for `F\ddot`. Still improvement. Merging.

**Comment by Carreau** [comment]
Thanks a lot for reactivity !

**Comment by jonathanslenders** [comment]
Apparently, there is no composed form for \\ddot... Currently not sure yet how to handle that.

**Comment by jonathanslenders** [comment]
Actually, many terminals don't even now how to handle that. lxterminal does, xterm doesn't at all, urxvt shows the dots too low.

**Comment by takluyver** [comment]
Gnome terminal can handle the decomposed double-dot OK.

**Pull request merged**
