### PR TITLE
Add an example notebook that demonstrates nbconvert supported features.

### LINKED ISSUE #7309: Create a notebook for testing nbconvert
We need to put together a notebook that illustrates the main things that we expect nbconvert to handle. The most important target is the HTML output. Some of these things include:

* At least one example of all output types.
* A good sample of Markdown.
* Links to files located on the web.
* Relative/absolute links to files co-located with the notebook
* Relative/aboslute links to other notebooks co-located with the notebook.

### PR DESCRIPTION
**Pull request by jdfreder**
closes #7309

### CODE REVIEW

**Comment by dsblank** [comment]
@jdfreder What is the purpose of the notebook? If it is to show people what it can do, I find it helpful to also have verbatim cells that show what was typed, like:

http://jupyter.cs.brynmawr.edu/hub/dblank/public/Jupyter%20Notebook%20Users%20Manual.ipynb#4.1.5-Lists

**Comment by Carreau** [comment]
> @jdfreder What is the purpose of the notebook? If it is to show people what it can do, I find it helpful to also have verbatim cells that show what was typed, like:

There is already a verbatim block. 

 - local file broken on nbviewer
 - This div's style will be removed by nbconvert. (broken)
 - exception is not stderr is it ? stderr shoudl be red background.
 - `display(HTML(`  not ssanitized.
 - `display(Image(url='./../images/IPython_logo.png'))` broken in nbviewer

Wanna add a raw cell ?
And a repr  with all png,svg, text, TeX, to be sure the correct one is picked ?

**Comment by dsblank** [comment]
@Carreau I meant that if you are also using this notebook to show humans how to create these items, it is useful to have, for each cell, a version that shows what to type to get the rendered results. Otherwise, the easiest way to figure it out is to download the notebook, open it, and then click the cell to unrender it. (Although this does suggest that it would be handy in nbviewer that one could mouse-over or click a cell to see the Markdown source). That would make a nice tool for beginners to see how to create Markdown and equations.

**Comment by Carreau** [comment]
It's not really for human consumption, it's to get a list of everything the converter should support (visually). Try to think it might be used to check visual regression like diffing screenshot of the webpage.

The location of the notebook might be bad though.

**Comment by ellisonbg** [comment]
I agree with @Carreau that the main examples directory isn't the place for this. It is misnamed because it is actually our user focused docs. I think we should put this in the nbconvert-examples repo instead.

**Comment by ellisonbg** [comment]
Other things missing:

* Link to a co-located image file.
* Link to a co-located notebook file.

**Comment by damianavila** [comment]
> I think we should put this in the nbconvert-examples repo instead

Yep, probably is a better place...

**Comment by jdfreder** [comment]
Moved to nbconvert-examples https://github.com/ipython/nbconvert-examples/pull/9 .

**Pull request closed without merging**
