### PR TITLE
JQuery dependency in widgets/manager.js and widgets/widget.js

### PR DESCRIPTION
**Pull request by SylvainCorlay**
- Removes the jquery dependency from the widget manager
- Removes jquery calls in widget.js.

(I am looking into backbone.nativeview for the base widget view)

### CODE REVIEW

**Comment by minrk** [comment]
I'm not sure this one is going to get in before the split

**Comment by SylvainCorlay** [comment]
Ok, I can reopen after *The Split*.
I am looking into making the widget views mixins of 
 - their own base backbone view (jquery, d3, native)
 - and the base widget stuff.
This can also be a different PR.

**Comment by SylvainCorlay** [comment]
Actually, it will also make it easier to use phosphor panels as layout widgets.

**Comment by minrk** [comment]
I'm ready to make the HTML split right now. Is this PR all done, or do you still have stuff to do here?

**Comment by minrk** [comment]
Hmm, I think the jQuery removal may need a bit of discussion. Is it okay to wait for this one until the split? We'll do that as quickly as we can.

**Comment by SylvainCorlay** [comment]
No problem, reopening after the split.

**Comment by minrk** [comment]
Great, thanks. I'll get that new repo up for you as quickly as I can.

**Pull request closed without merging**
