### PR TITLE
Attempt to build documentation with Travis-CI

### PR DESCRIPTION
**Pull request by olesyabar**
This is attempt to solve https://github.com/ipython/ipython/issues/10895:
- Added building documentation, using https://github.com/jupyter/notebook/pull/2808 as an example
- Dropped support for Python 3.3 because Travis CI had issues building it ("The command "if [[ $GROUP == docs ]]; then make -C docs/ html; fi" exited with 2.") + saw that Travis CI had issue with Python 3.3 in https://github.com/jupyter/notebook/commit/1ec12f7215b25f03f799effd9be1b1687d1b0a6e
- Tests now produce warnings like "/home/travis/build/olesyabar/ipython/IPython/core/debugger.py:docstring of IPython.core.debugger.Pdb.do_q:3: WARNING: Unexpected indentation." but fixing the warnings is outside of this PR

@syutbai actively contributed to this during PyCon Canada sprinting

### CODE REVIEW

**Comment by jzf2101** [comment]
@douglatornell can you confirm you also have these error?

**Comment by jzf2101** [comment]
[From what I can tell](http://openmdao.org/releases/0.0.9/docs/quick-ref/sphinx.html) it looks like this could asking for a line break?

**Comment by douglatornell** [comment]
@jzf2101 Confirmed. Output of a local docs build:
```
(ipython-dev) docs$ make html
python3 autogen_shortcuts.py
Created docs for shortcuts
mkdir -p build/html build/doctrees
sphinx-build -b html -d build/doctrees   source build/html
Running Sphinx v1.6.3
Initializing GitHub plugin
loading pickled environment... not yet created
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://rpy2.readthedocs.io/en/version_2.8.x/objects.inv...
loading intersphinx inventory from https://traitlets.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jupyter-client.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://ipyparallel.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://jupyter.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://jedi.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://ipykernel.readthedocs.io/en/latest/objects.inv...
loading intersphinx inventory from https://python-prompt-toolkit.readthedocs.io/en/stable/objects.inv...
loading intersphinx inventory from https://ipywidgets.readthedocs.io/en/stable/objects.inv...
building [mo]: targets for 0 po files that are out of date
building [html]: targets for 170 source files that are out of date
updating environment: 170 added, 0 changed, 0 removed
reading sources... [100%] whatsnew/version6                                                                                      
/home/doug/Documents/sprints/ipython/IPython/core/debugger.py:docstring of IPython.core.debugger.Pdb.do_q:3: WARNING: Unexpected indentation.
/home/doug/Documents/sprints/ipython/IPython/core/debugger.py:docstring of IPython.core.debugger.Pdb.do_quit:3: WARNING: Unexpected indentation.
/home/doug/Documents/sprints/ipython/docs/source/api/generated/IPython.core.interactiveshell.rst:66: WARNING: error while formatting arguments for IPython.core.interactiveshell.sphinxify: 'NoneType' object has no attribute '__mro__'
WARNING: /home/doug/Documents/sprints/ipython/IPython/utils/tokenize2.py:docstring of IPython.utils.tokenize2:15: (SEVERE/4) Missing matching underline for section title overline.

------------------------------------------------------------------------------
Tokenization help for Python programs.
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
preparing documents... done
writing output... [100%] whatsnew/version6                                                                                       
WARNING: dot command 'dot' cannot be run (needed for graphviz output), check the graphviz_dot setting
/home/doug/Documents/sprints/ipython/IPython/testing/tools.py:docstring of IPython.testing.tools.ipexec:: WARNING: more than one target found for cross-reference 'stdout': IPython.testing.iptestcontroller.TestController.stdout, IPython.utils.capture.CapturedIO.stdout
generating indices... genindex py-modindex
writing additional pages... interactive/htmlnotebook interactive/notebook interactive/nbconvert interactive/public_server search
copying images... [100%] whatsnew/../_images/jedi_type_inference_60.png                                                          
copying static files... done
copying extra files... done
dumping search index in English (code: en) ... done
dumping object inventory... done
build succeeded, 6 warnings.

Build finished. The HTML pages are in build/html.
```

**Comment by jzf2101** [comment]
My suspicion is that some of these issues come from https://github.com/ipython/ipython/blob/master/IPython/core/debugger.py#L312

**Comment by jzf2101** [comment]
According to @syutbai this is a pdb issue

**Comment by jzf2101** [comment]
@takluyver @Carreau @minrk could we have a second review?

**Comment by syutbai** [comment]
Regarding warning message: 
> /data/apps/ipython/IPython/core/debugger.py:docstring of IPython.core.debugger.Pdb.do_q:3: WARNING: Unexpected indentation.
> /data/apps/ipython/IPython/core/debugger.py:docstring of IPython.core.debugger.Pdb.do_quit:3: WARNING: Unexpected indentation.

Root cause:
Wrapping docstring from PDB that contains a '\n', Sphinx complains about indentation when it processes the '\n'.

Making changes in PDB:   
* PDB has Docstring formatting that drives help file formatting.  
* Docstring triggering the message below contains a '\n':   Q(uit)\nexit .  Pdb functions do_quit() and do_exit() is aliased so the resulting help file for this formats the "exit" word elegantly beneath the "Quit".  
* Making changes in PDB by removing the '\n' uglifies the Docstring, where the word "exit" starts on column 1. 

Making changes in IPython debugger.py:
* Escaping logic can be added to the docstring wrapping function to handle '\n'. This will likely make the code ugly.  

Making changes in Sphinx:
* Where "WARNING: Unexpected Indentation" is thrown, handle docstrings with '\n'.  Code needs to be investigated in more details.

**Comment by Carreau** [comment]
I think these two warnings messages are ok for now. Another possibility is to see how to ignore some warnings in sphinx. There might be a way to ignore warnings base on RegEx but this can be in a second PR. Appologies if you've spent a long time looking into this. I wouldn't bother trying to patch CPython itself I think the issue was already raise and the answer was "Won't fix".

I'll review the code now ! Thanks for sprinting on this, extra kudos for tackling documentation !

**Comment by Carreau** [comment]
I've re-enabled 3.3 (we definitively want to test the IPython **code** on 3.3. I think it is ok to build the docs only on the latest Python so at some point we might be able to simplify the `matrix/exclude` section into simply an `- include` section .

**Comment by jzf2101** [comment]
@Carreau the tests appear to pass, do you have other comments in your review before we pull?

**Comment by takluyver** [comment]
I think something's gone wrong with the Travis config - Matthias' change hasn't restored Python 3.3. I'm going to have a look now.

**Comment by takluyver** [comment]
OK, docs now only build on Python 3.6.

**Pull request merged**
