### PR TITLE
added namespace condition in IPcompleter

### PR DESCRIPTION
**Pull request by ghost**
added 

```
if self.use_main_ns:
           self.namespace = __main__.__dict__
```

in IPcompelter.py as suggested by Carreau sir,  in #9897

### CODE REVIEW

**Comment by Carreau** [comment]
Great thanks ! I will have a look; sorry I have been away for the last week.

**Comment by thesageinpilani** [comment]
its ok sir, thank you

**Comment by Carreau** [comment]
Great ! Work for me !

I'll let a day or so for any other dev to have a look, if I get no feedback I'll merge that tomorrow. 

Thanks ! I saw you wrote to me on gitter, I'll have a look.

**Comment by Carreau** [comment]
Merging ! Thanks !

**Pull request merged**
