### PR TITLE
Remove python2 code

### PR DESCRIPTION
**Pull request by srinivasreddy**
revert 147b245

### CODE REVIEW

**Comment by takluyver** [comment]
The issue describing why this code was added (http://bugs.python.org/issue10144 ) says that the problem wasn't seen on Python 3, but I don't understand it well enough to be totally confident that it can't come up on Python 3. There may be some corner case where it still comes up.

**Comment by srinivasreddy** [comment]
may be a test case to keep watch on that doesn't occur again makes this PR merged?

**Comment by takluyver** [comment]
I don't think it's easy to test, especially if it affects some corner case that a straightforward test is unlikely to exercise. We may just decide to merge it anyway, as the original problem discovered didn't affect Python 3.

**Comment by Carreau** [comment]
I think it's been long enough. Let's try it.

**Pull request merged**
