### PR TITLE
Revert 3.7 AST fix

### PR DESCRIPTION
**Pull request by Carreau**
3.7 ast modification were reverted. Remove our fix for now.

### CODE REVIEW

**Comment by takluyver** [comment]
From the Travis docs:

> Recent Python development branches require OpenSSL 1.0.2+. As this library is not available for Trusty, 3.7-dev, 3.8-dev, and nightly do not work (or use outdated archive).

https://docs.travis-ci.com/user/languages/python/#Development-releases-support

[This issue](https://github.com/travis-ci/travis-ci/issues/9069) suggests that they're working on getting an Ubuntu 16.04 image ready, but it's not quite there yet.

**Comment by michael-k** [comment]
> This issue suggests that they're working on getting an Ubuntu 16.04 image ready, but it's not quite there yet.

It's available via

```yaml
matrix:
  include:
    - python: 3.7
      dist: xenial
      sudo: true
    - python: nightly  # never tried that, but should work
      dist: xenial
      sudo: true
```
(and also remove `3.7`/`3.7-dev`/`nighly` from the top level `python` list)

**Comment by Carreau** [comment]
Oh, that would be great ! Do you want to send a PR ?

**Comment by michael-k** [comment]
sure

**Comment by Carreau** [comment]
Rebased and move docs to be built on 3.7. Also test on 3.7.dev just in case.

**Review by ivanov — APPROVED** [review]
Great! fewer workarounds! 🎊

**Pull request merged**
