### PR TITLE
Update actions.js

### PR DESCRIPTION
**Pull request by abalkin**
Use left/right instead of before/after.  See #7807.

### CODE REVIEW

**Comment by Carreau** [comment]
Seem legit.

**Comment by abalkin** [comment]
I have not tested this.  Give me a few minutes ...

**Comment by takluyver** [comment]
Go ahead. I'm fairly sure it will work ;-)

**Comment by Carreau** [comment]
> Go ahead. I'm fairly sure it will work ;-)

That was more a I'm fine with the change unless someone object. Not a "waiting for travis".

**Pull request merged**
