### PR TITLE
Sort and unique %config results

### LINKED ISSUE #10535: Sort and uniq available objects for config
```
In [1]: config
Available objects for config:
     TerminalInteractiveShell
     HistoryManager
     PrefilterManager
     IPCompleter
     DisplayFormatter
     MagicsManager
     ScriptMagics
     AliasManager
     TerminalIPythonApp
     StoreMagics
     StoreMagics
```

The result is not sorted, and StoreMagics shows up twice.

### PR DESCRIPTION
**Pull request by tomowind**
Fixes #10535

### CODE REVIEW

**Comment by tomowind** [comment]
I think this is a breaking change. I will close it and create another pull request.

**Comment by Carreau** [comment]
> I think this is a breaking change

Why do you think it is a breaking change ? Also if you are just unhappy with the implementation you can "just" force push  on this.

**Comment by tomowind** [comment]
My change fixes the print issue, but breaks the settings. Correct fix and more tests are coming in this pull request soon.

**Comment by tomowind** [comment]
Reopening it with correct fix and more test.

**Comment by tomowind** [comment]
@Carreau Sorry that I don't know the GitHub workflow well. I don't know how to re-open this pull request. If you have the permission, can you do it please? I force pushed already.

**Comment by takluyver** [comment]
Reopening is disabled - I guess maybe a force-push after closing a PR locks it closed?

Anyway, no matter, please open a new PR for the change.

**Comment by tomowind** [comment]
Ok. Thanks for the advice!

**Pull request closed without merging**
