### PR TITLE
use pathlib for utils.text.paths

### PR DESCRIPTION
**Pull request by minrk**
instead of path.py

For 4.2

cc @takluyver

### CODE REVIEW

**Comment by takluyver** [comment]
I'm generally in favour of this, but it is a user-facing change, because you will get a different type of object back when you do:

```
files = !ls
files.p
```

So maybe it should be 5.0 rather than 4.2?

**Comment by minrk** [comment]
Either that, or we need to make `path.py` an explicit dependency of IPython.

**Comment by takluyver** [comment]
I don't think it needs to be a dependency - it's only loaded if you do a specific operation that probably most people don't even know about, and even fewer use. We could make an error message that points people to `path.py`, but I'm inclined to just merge this without backporting.

**Comment by minrk** [comment]
Then we're removing a feature in 4.1 from 4.2, aren't we?

**Comment by takluyver** [comment]
No, I'd leave it in exactly as it is. With the change we made to pickleshare, users no longer get `path.py` installed automatically, but that's not changing with IPython versions,  and people who want that feature can still easily install `path.py`.

**Comment by minrk** [comment]
Seems a bit odd to let something break just because we forgot to express a dependency that we always had when we pulled pickleshare out to a standalone package, but I'll go with you.

**Pull request merged**
