### PR TITLE
provided more history examples in quick reference

### PR DESCRIPTION
**Pull request by nnathan**
This provides a few more concrete examples of using history and editing with an existing history. I struggled to find examples of editing the full history in an editor and [answers like these](http://stackoverflow.com/questions/16050463/how-to-open-ipython-command-history-on-a-text-editor) didn't really tell the full story. Similarly [trying to get the entire history](http://stackoverflow.com/questions/25124037/ipython-print-complete-history-not-just-current-session) is a tiny comment that is easy to miss.

As I was invited to submit a PR for #8074. Here is what I think the quick reference should include under History.

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks, that looks fine to me - I'll give others a day or so to look at it, and merge if there are no objections.

**Comment by Carreau** [comment]
Looks fine to me, if it can be helpful for someone;

**Comment by minrk** [comment]
:+1:

**Comment by takluyver** [comment]
Great, thanks.

**Pull request merged**
