### PR TITLE
keep autocomplete results stable in multi-thread access

### PR DESCRIPTION
**Pull request by richard-fung-db**
IPython can be used in a GUI where a notebook cell is running while autocomplete is getting invoked on another thread. The running cell can change the iterator of the namespace or global_namespace while the autocomplete invocation is enumerating over the dictionary of results. The resulting error message from autocomplete is `RuntimeError: dictionary size changed during iteration`.

This change proposes to get a copy of the keys() so that can be enumerated.

Example code that causes the issue:
```
import time

glbl = globals()
count = 0
time_limit = 50
start = time.time()
end = start + time_limit

while time.time() < end:
  glbl[f"global_var_{count}"] = None
  count += 1
```

### CODE REVIEW

**Comment by richard-fung-db** [comment]
You can fix this by running ``pip install black[jupyter]``

**Comment by jasongrout** [comment]
As well as:

```
Changes need auto-formatting. Run:
    darker -r 60625f241f298b5039cb2debc365db38aa7bb522
then commit and push changes to fix.
```

**Review by jasongrout — APPROVED** [review]
Thanks!

**Comment by jasongrout** [comment]
@Carreau - could we add this to the 8.5 milestone, or a bugfix release if that would be coming earlier than 8.5?

**Comment by Carreau** [comment]
Yeah, that seem reasonable, I'll merge that and make a release soon.

**Pull request merged**
