### PR TITLE
FIX: bare functions in callback registry on bogus unregister

### PR DESCRIPTION
**Pull request by tacaswell**
7de483b5fdaa99fa289b418ce0efc5102287ba64 added checking for the case
where the callback was wrapped by backcall, however if there are
un-wrapped functions registered and a non-registered function is
attempted to be unregistered then this fails by raise an uncaught
AttributeError.

Where should a test for this go?

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! Tests in `IPython.core.tests.test_events`, please.

**Comment by tacaswell** [comment]
I can drop the last commit if you want, just being a difficult busy body / making my editor less angry....

**Comment by takluyver** [comment]
The wrapping is fine, but can you fix the test? ;-)

**Comment by tacaswell** [comment]
cargo-culted how to test raising....

**Comment by takluyver** [comment]
Needs a bit more cargo ;-)

```python
import nose.tools as nt
```

**Comment by tacaswell** [comment]
3rd times the charm?

**Comment by takluyver** [comment]
Seems it is!

**Pull request merged**
