### PR TITLE
feat: remove deprecated code & files ⚰️

### PR DESCRIPTION
**Pull request by meysam81**
This will remove the dead code that is handled by the `load_extension` context manager and also removes the deprecated extension that is addressed elsewhere.

Fixes #13192

### CODE REVIEW

**Comment by meysam81** [comment]
@Carreau
Please let me know what I have to do in regard to "...add notes to whats new".

**Comment by Carreau** [comment]
> Please let me know what I have to do in regard to "...add notes to whats new".

You can add a file in `docs/source/whatsnew/pr/` (there are examples in there), when I do the release I'll merge all those files into the release notes.

**Comment by meysam81** [comment]
@Carreau

Done.

**Comment by Carreau** [comment]
I added couple lines to fix the errors, could you get a look and tell me if they looks ok to you ?

**Pull request merged**
