### PR TITLE
Change setupbase.py to use pathlib instead of os.

### PR DESCRIPTION
**Pull request by david8381**
Co-authored-by: Zachary Blackwood <zblackwo@gmail.com>
Co-authored-by: Nathan Lis <Nathan.L.2018@gmail.com>

### CODE REVIEW

**Review by Carreau — CHANGES_REQUESTED** [review]
Thanks a lot for your first contributions, 

I'm in general for simplification and update like this, unfortunately in this case it seem to create problems and IPython can't be build as some part of setuptools requires str and not path, so I think part of what you've done has to either be reverted, or wrapped in str(), to convert back into strings before returning from functions.

**Comment by blackary** [comment]
Are there any additional changes that should happen for this to be accepted?

**Comment by wxman22** [comment]
@Carreau Did our latest updates address your requested changes?

**Comment by Carreau** [comment]
Thanks for your patience and sending this; I was not able to keep up with everything and to keep the number of PRs small I'm going to close this one; If you believe this was a mistake, feel free to comment or re-send it; 

I can't guarantee I'll get to it as I do not have the bandwidth.

**Pull request closed without merging**
