### PR TITLE
Move dynamic buttons to the left and upload button to the right.

### LINKED ISSUE #7788: Move dashboard buttons to the L side of the table
Right now there can be a huge distance between the left of the notebook dashboard (where there are checkboxes) and the right, where there are the buttons. It might improve the usability to have the buttons on the left side (where the download text is).

### PR DESCRIPTION
**Pull request by jdfreder**
Requested by @ellisonbg .

Before:
old

After:
new

alternative to #7805
closes #7788

### CODE REVIEW

**Comment by minrk** [comment]
Getting rid of upload text?

**Comment by jdfreder** [comment]
> Getting rid of upload text?

That's what @ellisonbg suggested.  I don't think he prototyped it ahead of time though, it looks a little barren.

**Comment by mathieu1** [comment]
This is an alternative to #7805 (both are addressing #7788). I like having the Upload, New and Refresh on the right as you did.

**Comment by ellisonbg** [comment]
I am +1 on this version of these and would love to see this get into 3.1. A
few changes:

* Upload button should have a tooltip indicating that drag-n-drop also
works and that all file types work.
* There should be placeholder text where the transient buttons are
describing what the checkboxes enable a user to do.

On Tue, Mar 3, 2015 at 12:53 AM, Mathieu <notifications@github.com> wrote:

> This is an alternative to #7805
> <https://github.com/ipython/ipython/pull/7805> (both are addressing #7788
> <https://github.com/ipython/ipython/issues/7788>). I like having the
> Upload, New and Refresh on the right as you did.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7933#issuecomment-76908100>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by jdfreder** [comment]
@ellisonbg comments address in last commits.

**Comment by Carreau** [comment]
Need rebase.

**Comment by Carreau** [comment]
Still need rebase.

**Comment by Carreau** [comment]
ping @jdfreder for rebase.

**Comment by jdfreder** [comment]
@Carreau sorry, have been busy working on other jupyterhub/nbgrader things, didn't see your comment.  Should be rebased now.

**Comment by Carreau** [comment]
+1, merging.

**Pull request merged**
