### PR TITLE
Fixed typos

### PR DESCRIPTION
**Pull request by minho42**
This typo fix includes variable name in test_interactiveshell.py
self.sytem -> self.system
I'm not sure if the test still passes.

### CODE REVIEW

**Comment by Carreau** [comment]
Oh, thanks ! 

Test seem to be sporadic failure, I relaunch the offending one.

**Comment by Carreau** [comment]
I'm flabbergasted about the test failure. It also fails on my machine, and on master on my machine; but other PRs are passing. I'm trying to narrow down to a sqlite operational error, but I't super weird; Sorry for the delay.

**Comment by Carreau** [comment]
Well test are pasing now... let's get that in.

**Comment by minho42** [comment]
Thanks.

**Pull request merged**
