### PR TITLE
Backport PR #11401 on branch 5.x (Added skipif for sqlite3 version > 3.24.0)

### PR DESCRIPTION
**Pull request by ellert**
Backport PR #11401: Added skipif for sqlite3 version > 3.24.0

### CODE REVIEW

**Comment by ellert** [comment]
Are you blocking the PR due to unrelated issues with the travis CI testing?

**Comment by Carreau** [comment]
> Are you blocking the PR due to unrelated issues with the travis CI testing?

Blocking is a strong word, I'd like to get it fix, either by someone, or me, to make sure there is no other regressions.  But there is just so much hours in days, and I only working on IPython as volunteer. So I'll get to it when I have time. Getting this release will also take some time. I'll see if I can work on that this week-end. 

BTW, we have a bot to do backport if necessary, so usually you can either just as a commiter to mention the bot, or we can whitelist people to be able to mention the bot.

**Comment by Carreau** [comment]
>  from master required a manual merge conflict resolution...But maybe your bot uses some clever flags to overcome that.

Ah ok, so manual backport is fine. The bot does not do anything fancy. I was just mentioning it just in case. 

I've rebased as I should have fix the testing issue on master, to make sure the test are passing. 

Once it's green I can merge.

**Comment by Carreau** [comment]
Test green, getting that in. Thanks.

**Pull request merged**
