### PR TITLE
Document _repr_mimebundle_

### PR DESCRIPTION
**Pull request by Carreau**
Unfinished as display_* are broken with `_repr_mimebundle_`

### CODE REVIEW

**Comment by dhirschfeld** [comment]
`_repr_mimebundle_` seems very cool! Just wondering if there are any plans to have the displayed repr to be user-selectable in the frontend?

What I'm thinking of is the user being able to select between e.g. an html table repr or a chart for a DataFrame.

...or is that not something it's designed for and would be more appropriate for an extension?

**Comment by Carreau** [comment]
Yes it has been a long term plan, nobody bothered to implement it.

**Comment by Carreau** [comment]
Rebased and fixed, new section `Custom Mimetypes with _repr_mimebundle_` in teh notebook. Closes #https://github.com/ipython/ipython/issues/10586 once backported to 5.x

**Comment by rgbkrk** [comment]
> What I'm thinking of is the user being able to select between e.g. an html table repr or a chart for a DataFrame.

This is where I want to take the new data resource stuff with pandas. It won't be a toggle between mimetypes though -- it will be a component that allows switching views between the table and some light charting with vegalite (or otherwise).

**Comment by takluyver** [comment]
@meeseeksdev backport

**Pull request merged**
