### PR TITLE
Fix race condition in javascript kernel message processing

### PR DESCRIPTION
**Pull request by jasongrout**
Because the binary messages are now deserialized using the asynchronous FileReader API, we need to have some way to force the messages to still be processed in the order they are received.  This patch implements a simple processing queue using promises.

### CODE REVIEW

**Comment by jasongrout** [comment]
@minrk, @jdfreder - this is ready for comments.  I'll add a test for it on Monday.

**Comment by minrk** [comment]
This looks about as simple as I could have hoped. Thanks, @jasongrout!

**Comment by minrk** [comment]
A test would be awesome, but this looks great to me.

**Comment by jasongrout** [comment]
@minrk - I think this is ready for review.  When I tried testing it using `iptest js`, it just said `Can't test binary websockets on phantomjs.`, so I'm not sure if the test actually passes.

**Comment by rgbkrk** [comment]
Can slimer test the binary websockets?

**Comment by takluyver** [comment]
In principle, it should be able to. Last time I tried running the tests on
slimer there were other failures, though.

**Comment by jdfreder** [comment]
@jasongrout this looks very similar to the solution you devised for the widget, thanks!  +1 for 3.1 .

**Comment by minrk** [comment]
When I wrote the binary websocket test, I was using slimer. I've since uninstalled it, and it's been a little while since I used it, but I can try running it when I get back tomorrow.

**Comment by minrk** [comment]
@jasongrout I made jasongrout/ipython#7 (if you don't want to add the PR+PR merge commit, you can cherry pick  or rebase after merging), after which the tests pass. Your added tests pass fine, but the changes here and older msgspec changes caused the last segment of the test to fail.

**Comment by jasongrout** [comment]
@minrk: I merged your PR; thanks!

**Comment by minrk** [comment]
@jasongrout thanks!

**Pull request merged**
