### PR TITLE
Some extra info about tab completion in documentation.

### PR DESCRIPTION
**Pull request by Carreau**

### CODE REVIEW

**Comment by ivanov** [comment]
I added some minor edits, primarily to use the `:kbd:` directive for the key combinations. Thanks, @Carreau !

**Comment by Carreau** [comment]
<3

**Comment by ivanov** [comment]
Hmmm... the GitHub render for ```:kbd:`Ctrl-O`.``` seems to be unhappy... I wonder if it wants the `O` to be lower case...

**Comment by ivanov** [comment]
Oh, oops, it's not that picky, I had swapped `kdb` for `kbd` - that's why it wasn't rendering... - fixed and force pushed now...

**Comment by ivanov** [comment]
Oh, and by the way - should we  continue to write " if ``jedi`` is installed, "? Seems like [we install it unconditionally](https://github.com/ipython/ipython/blob/master/setup.py#L188)

**Pull request merged**
