### PR TITLE
ipython appconfig.py -h vs. python appconfig.py -h

### PR DESCRIPTION
**Pull request by grandadmiral-thrawn**
example of appconfig.py -h should be called using "ipython" rather than just "python."

### CODE REVIEW

**Comment by takluyver** [comment]
No, I think that example is supposed to be called with `python` - it's a separate sample application to illustrate how the config system works.

**Comment by dataRonin** [comment]
Interesting on the python/ipython. I suppose my configuration must be different than expected, because I was expecting python to work as a call as well, but only ipython did.  In any case, if this doesn't work for someone out there, that might be a simple troubleshoot.

**Comment by takluyver** [comment]
What error do you get calling it with `python`? It might be that that's not the same Python in which you have IPython installed - if so, you'll get an ImportError.

**Comment by dataRonin** [comment]
Hi Thomas, thanks for responding. I get a path error (errno2). I checked
and I have added iPython to my path.

On Sat, Jul 25, 2015 at 2:28 PM, Thomas Kluyver <notifications@github.com>
wrote:

> What error do you get calling it with python? It might be that that's not
> the same Python in which you have IPython installed - if so, you'll get an
> ImportError.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/8659#issuecomment-124898100>.
>



-- 
*Fox Peterson *


Currently: Faculty Research Assistant,
Oregon State University
PNW Forest Science Laboratory
Corvallis, Oregon

*Contact Information:*
Work: 541.758.8754 (M-F, 7:30-12:45/13:15-17:30 Pacific)
Personal/Cell: 404.580.5016, or call via iPhone <1-404-580-5016>
Email: fox@tinybike.net

*I am actively seeking career opportunities beginning in December of 2015.
I am based in Oregon. My background is in forestry, economics, and data
science. I have extensive experience in the field collecting data both
manually and with sensors; I am also skillful with statistics, using
databases, and developing front and back end solutions in several popular
computer languages. I enjoy QA/QC and do not seek to be a PI but simply to
solve problems and make our environment better by making its data cleaner
and more accessible for both scientists and "real humans". Please contact
me via email for a resume and/or references.*

*Curious about our climate? Check out my SUPER SIMPLE meteorological
threshold calculator:*
*isitpossibleonearth.com <http://isitpossibleonearth.com>*

**Comment by takluyver** [comment]
Hmm, odd, I don't know what would cause that.

**Comment by dataRonin** [comment]
Me neither. I thought I had just noticed some little type-o but it looks
like the problem is actually on my system. If I can replicate it on someone
else's machine I'll let you know, otherwise, sounds like it's probably
nothing.

On Sat, Jul 25, 2015 at 2:41 PM, Thomas Kluyver <notifications@github.com>
wrote:

> Hmm, odd, I don't know what would cause that.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/8659#issuecomment-124900250>.
>



-- 
*Fox Peterson *


Currently: Faculty Research Assistant,
Oregon State University
PNW Forest Science Laboratory
Corvallis, Oregon

*Contact Information:*
Work: 541.758.8754 (M-F, 7:30-12:45/13:15-17:30 Pacific)
Personal/Cell: 404.580.5016, or call via iPhone <1-404-580-5016>
Email: fox@tinybike.net

*I am actively seeking career opportunities beginning in December of 2015.
I am based in Oregon. My background is in forestry, economics, and data
science. I have extensive experience in the field collecting data both
manually and with sensors; I am also skillful with statistics, using
databases, and developing front and back end solutions in several popular
computer languages. I enjoy QA/QC and do not seek to be a PI but simply to
solve problems and make our environment better by making its data cleaner
and more accessible for both scientists and "real humans". Please contact
me via email for a resume and/or references.*

*Curious about our climate? Check out my SUPER SIMPLE meteorological
threshold calculator:*
*isitpossibleonearth.com <http://isitpossibleonearth.com>*

**Pull request closed without merging**
