### PR TITLE
Write tests for ipdb

### PR DESCRIPTION
**Pull request by Carreau**
Add test for up, down, list and longlist.
## 

I'm refactoring in this area and these things being not tested makes me unconfortable. 

I'm disappointed though that coverage don't work with doctests.

### CODE REVIEW

**Comment by minrk** [comment]
Is it possible to write this *not* as doctests? We are planning to remove all doctests from IPython, so I'd rather not add more.

**Comment by takluyver** [comment]
Ditto what Min said, I'd like to move away from doctests where possible.

**Comment by Carreau** [comment]
Ok, but I'm not quite sure how. 

CPython test suite of Pdb is using docstrings, and the only other option I can see is subprocess, with re-implementing custom matching for `<blankline>` and `...`. Which seem to me as bad as doctests.

**Comment by minrk** [comment]
Okay. We can merge here, and I'll take it upon my self to rip out the doctests the next time they make me angry.

**Comment by takluyver** [comment]
Tests failing in master on Travis, looks like it's because of this. In particular, it looks like `up` is printing more context than the tests expect.

**Comment by Carreau** [comment]
> Tests failing in master on Travis, looks like it's because of this. In particular, it looks like up is printing more context than the tests expect.

Hum, i'm not sure why they were not failing there, and fail on master. Thanks for fixing.

**Comment by Carreau** [comment]
> Okay. We can merge here, and I'll take it upon my self to rip out the doctests the next time they make me angry.

I would be happy to help you. I just don't see how to test not using strings.

**Comment by takluyver** [comment]
Yeah, I suspect that it may be very tricky for the debugger. Though if we ever add debugger messages to the protocol, I bet the refactoring involved will make testing a lot easier.

**Comment by takluyver** [comment]
Also, good moooooorning California! :sunrise_over_mountains:

**Pull request merged**
