### PR TITLE
Smooth notebook scrolling on pager closing.

### PR DESCRIPTION
**Pull request by Carreau**
avoid brutal jump of notebook on closing pager, when notebook is scroll
to max

### CODE REVIEW

**Comment by minrk** [comment]
@Carreau I'm not quite clear on what this fixes. I can't seem to make it misbehave. What does 'scroll to max' mean?

**Comment by Carreau** [comment]
Oh, it does not really "fix" anything. 

- Make many cells.
- `numpy?` (open pager)
- focus last cell
- scroll up as much as you can. 
- esc to close pager.

Notebook use to 'jump' back in place when end-space with go suddently from XXX->100px.
now it just slowly go from XX to 100 px

**Comment by takluyver** [comment]
in current master, when I try to follow your instructions, it doesn't scroll the focused cell back into view at all: the pager closes without causing a scroll.

**Comment by Carreau** [comment]
The framerate does not help, but here it is:
Master :
master

PR:

pr

**Pull request merged**
