### PR TITLE
Adding a very simple instance of _Bool widget

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Just a _green check_ / _red cross_ widget typically used for showing whether some input is valid or not.

### CODE REVIEW

**Comment by minrk** [comment]
ping @ellisonbg @jdfreder

**Comment by jdfreder** [comment]
I'm okay with this for 4.0

**Comment by SylvainCorlay** [comment]
Made a minor change for styling,

**Comment by SylvainCorlay** [comment]
Rebased. I am thinking of adding a readout for the invalid case.

**Comment by minrk** [comment]
@SylvainCorlay needs rebase, but ok to merge once there's a button for it.

**Comment by SylvainCorlay** [comment]
Rebased.

**Comment by jdfreder** [comment]
Thanks @SylvainCorlay !

**Pull request merged**
