### PR TITLE
Identify position after a newline as the start of the next line

### PR DESCRIPTION
**Pull request by takluyver**
Closes gh-10814

### CODE REVIEW

**Comment by ian-r-rose** [comment]
This fixes the IPython `ValueError`, but it breaks completion on the last line of a cell (due to not correctly identifying the right line).
If I have a cell with contents:
```python
pri
pri
```
invoking the completer on the first line successfully gives me `print`, but on the second line it does not.
(In case you missed it on #10814, you can test this in JLab 0.27, which was mistakenly invoking the completer at the start of lines).

**Comment by takluyver** [comment]
How about now?

**Comment by ian-r-rose** [comment]
Works great, thanks for chasing that down @takluyver !

**Review by ian-r-rose — APPROVED** [review]

**Comment by Carreau** [comment]
Thanks ! Awesome !

**Pull request merged**
