### PR TITLE
add border to rendered markdown with cell toolbar

### LINKED ISSUE #7238: Add cell border to rendered markdown when the CTB is visible
Right now, the celltoolbar (CTB) UI dangles in empty space when attached to a rendered markdown cell. This makes it difficult to see which cell everything goes with (no good visual hierarchy). Here is a screenshot:

screen shot 2014-12-15 at 4 43 16 pm

A simple solution is to add (through CSS classes) a cell border to rendered markdown cell when the CTB is visible. Here is my proposal:

screen shot 2014-12-15 at 4 48 12 pm

### PR DESCRIPTION
**Pull request by minrk**
matches unrendered markdown and code cells

screen shot 2015-01-20 at 12 36 10

ping @ellisonbg 

closes #7238

### CODE REVIEW

**Comment by minrk** [comment]
@ellisonbg do you want to check style on this one?

**Comment by ellisonbg** [comment]
@minrk when my computer died today during the G+ Hangout, that was it - it
really died for good. I got a new 13" Retina MBP late today, but it is
going to take a bit before I am back up and running and check this live..
The screenshot looks fine though, so I would merge and will do a live test
later.

On Thu, Jan 22, 2015 at 6:12 PM, Min RK <notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> do you want to check style on
> this one?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7514#issuecomment-71136818>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
That's a dramatic failure! This is simple enough, so I'll merge. Let us know if there's anything we can do to help you get back up and running.

**Comment by ellisonbg** [comment]
Thanks for the offer of help - at this point it is mostly just waiting for
everything to copy back onto the system/install. One (hopefully) easy
question - do you happen to know the list of brew package names related to
node that we currently use for ipython development?

On Thu, Jan 22, 2015 at 9:42 PM, Min RK <notifications@github.com> wrote:

> Merged #7514 <https://github.com/ipython/ipython/pull/7514>.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7514#event-223508448>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by minrk** [comment]
> the list of brew package names related to node that we currently use for ipython development?

I think it's just:

    brew install node
    npm install -g less bower

**Comment by ellisonbg** [comment]
node grabs npm or is that also needed?

On Thu, Jan 22, 2015 at 9:45 PM, Min RK <notifications@github.com> wrote:

> the list of brew package names related to node that we currently use for
> ipython development?
>
> I think it's just:
>
> brew install node
> npm install -g less bower
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7514#issuecomment-71150417>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Comment by Carreau** [comment]
> node grabs npm or is that also needed?

Node does grab npm.

**Comment by Carreau** [comment]
@ellisonbg  from the top of y head, you might want to brew also : 
- git
- zeromq
- python2/3
- phantomjs
- casperjs
- cask
- qt
- pyqt
- sqlite

gc4.8 take quite a bit of time too.

**Comment by ellisonbg** [comment]
Thanks!

On Fri, Jan 23, 2015 at 12:47 AM, Matthias Bussonnier <
notifications@github.com> wrote:

> @ellisonbg <https://github.com/ellisonbg> from the top of y head, you
> might want to brew also :
>
>    - git
>    - zeromq
>    - python2/3
>    - phantomjs
>    - casperjs
>    - cask
>    - qt
>    - pyqt
>    - sqlite
>
> gc4.8 take quite a bit of time too.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/ipython/ipython/pull/7514#issuecomment-71163497>.
>



-- 
Brian E. Granger
Cal Poly State University, San Luis Obispo
@ellisonbg on Twitter and GitHub
bgranger@calpoly.edu and ellisonbg@gmail.com

**Pull request merged**
