### PR TITLE
No default value creation for element traits of a List

### LINKED ISSUE #7760: Parameterized traitlets and default value validation
When using a List traitlet with validated elements, the default value of the elements is validated, like in this example:

```Python
from IPython.utils.traitlets import *

class Bar():
    pass

class Foo(HasTraits):
    bars = List(Instance(Bar, allow_none=False))

foo = Foo()
```
which yields a `TraitError` because the default value, None, is invalid. 

A fix would be to do `bars = List(Instance(Bar, tuple(), allow_none=False))`, i.e. to create a  default value. But somehow, I think that there should not be a need to instantiate a default value that is never going to be used!

@minrk should the default value be validated when the traitlet is to be used in a "template" trait like List?

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Fixes  #7760 . @minrk @ssanderson

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
Besides, I am now overloading the `_resolve_classes` of the element traits for `Tuple` as well.

**Comment by SylvainCorlay** [comment]
Now also resolving element trait names in `Tuple`, which was missing.

**Comment by minrk** [comment]
Nice, thanks. Want to add the test you described in #7760?

**Comment by minrk** [comment]
Excellent, thanks. Will merge once Travis confirms.

**Comment by SylvainCorlay** [comment]
Travis is happy.

**Pull request merged**
