### PR TITLE
JS: Unfreeze actions.

### PR DESCRIPTION
**Pull request by jdfreder**
You can't monkey patch the actions instance when frozen.

@Carreau

### CODE REVIEW

**Comment by Carreau** [comment]
Why do you want to monkeypatch ?

**Comment by jdfreder** [comment]
For me, logging, but you could imagine other use cases. I'd be okay with just adding an event if there's a reason you think we should keep the freeze.

**Comment by Carreau** [comment]
The reason of the freezing is to avoid adding attributes due to typo, which  in "use strict" will fail. I catched a few error and weird patching with that. I'm fine with removing it. 

If you need it you ca go ahead and merge.

**Comment by Carreau** [comment]
Seem with @jdfreder you can extend `init.prototype`  so no need to not-seal.

**Comment by jdfreder** [comment]
Yes, thanks @Carreau !

**Pull request closed without merging**
