### PR TITLE
Fix GUI integration for support for pyqt5 apps that import QtWebEngineWidgets 

### LINKED ISSUE #10877: QTC qt5 integration broken for pyqt5 apps that import QtWebEngineWidgets
The `%gui qt5` magic plugs the IPython QtConsole into the Qt/pyqt5 event loop, so that PyQt5 application can be run from within IPython without blocking the kernel.

QT5 include the new modules QtWebEngine/QtWebEngineWidgets for displaying web content.
Loading a PyQt5 application within IPython currently throws with:
```
QtWebEngineWidgets must be imported before a QCoreApplication instance is created 
```

It seems IPython QtC creates a `QCoreApplication` without first importing `QtWebEngineWidgets`, so by the time the user's code tries to import  `QtWebEngineWidgets`, it's too late.

Problem code to [here](https://github.com/ipython/ipython/blob/53c132361f3ba145f93b9836fa26d328e6f7136e/IPython/external/qt_loaders.py#L265).

### PR DESCRIPTION
**Pull request by JeremySikes73**
closes https://github.com/ipython/ipython/issues/10877

### CODE REVIEW

**Comment by takluyver** [comment]
It doesn't seem ideal to load it regardless of whether or not it's needed. @ccordoba12 , you use Qt more than most of us - it would be good to get your thoughts.

**Comment by JeremySikes73** [comment]
In terms of ease of use, it *is* ideal. The cost is about 100MB of memory (size of the DLL) iff qt5 integration is requested. QWebEngine is the qt5 replacement of QtWebkit, the "Qt web view" widget. I expect it's fairly common in modern Qt Applications.

There are two alternatives:
1. Change the `%gui` magic to take arguments. This would also require changes to to config file, so the change can be made permanent.
2. Use a hack like:
```python
IPYTHON=1

def ensure_QApp(*args,**kwargs):
    app=None
    app = QApplication.instance() or QApplication([''])

    if IPYTHON:
        try:
            import IPython.terminal.pt_inputhooks.qt as ipqt
            ipqt._appref = app
        except:
            pass
    return app

app = ensure_QApp([''])
window = None

def main():
    global app, window
    window = MyMainWindow() 
    window.show() 

if __name__ == '__main__':  
    main()  
    app.exec_()  
```

Then, in IPython:
```
>>> import myapp # create the QApplication and shove it into IPython internals
>>> %gui qt5 # activate integration, will use the event loop of OUR QApplication
>>> foo.main() # show the main window, doesn't block now
```

This is cumbersome, touches IP internals, requires IP-specific changes to the application and the little dance has to be redone on every kernel restart. It doesn't require changes to IP though.

**Comment by takluyver** [comment]
100 MB of memory is quite a lot, and I think plenty of Qt code doesn't need a web engine, e.g. matplotlib's Qt backend probably doesn't.

Maybe an easy if ugly workaround is to make a `%gui qt5-web` option that loads QWebEngine.

**Comment by Carreau** [comment]
Tagging as `closed-PR`, and closing as this is seem to have stalled a bit. 
This is just to keep the PR queue a bit shorter and focusing on what is actually worked on.
Feel free to reopen, (or ask for reopening if you don't have enough right to do so). 
If you were not the original author, and want to revive this, please feel free to do so. 

Also, we are doing our best to enable people to learn how to contribute to the project, and get commits in. If you are missing time or have any other issues that prevent you to work on that, please feel free to tell us, we can try to build on top of what you did. 

Thanks a lot and looking forward to see this moving forward again.

**Pull request closed without merging**
