### PR TITLE
blacklist jsonschema 2.5.0

### PR DESCRIPTION
**Pull request by Carreau**
ping @takluyver, @jhamrick

### CODE REVIEW

**Comment by rgbkrk** [comment]
Looking good, tests pass.

**Comment by takluyver** [comment]
jsonschema 2.5.1 is out now, so tests should be passing anyway.

**Comment by takluyver** [comment]
Closed on the grounds that this is no longer necessary, and if you have 2.5.0 already installed, we are compatible with it.

**Comment by rgbkrk** [comment]
That's true, since installation would fail anyway.

**Pull request closed without merging**
