### PR TITLE
add header_buttons block to page template

### PR DESCRIPTION
**Pull request by minrk**
allows easier access to adding buttons next to the logout button in custom templates.

### CODE REVIEW

**Comment by takluyver** [comment]
This is all before the headercontainer, where the save widget and kernel logo go. But I thought the logout button went to the right of that? :confused:

**Comment by minrk** [comment]
It's `float: right`, so the order actually doesn't matter. We can move it below, so the HTML more clearly matches the display, though.

**Comment by minrk** [comment]
Reordered the two blocks, so the order of elements more closely resembles their appearance. Due to the `float` behavior, it has no visual effects.

**Comment by minrk** [comment]
This puts the kernel logo to the right of logout, since the logo was in headercontainer. I guess it makes sense to keep headercontainer after header_buttons, since anything floated right in there should expect to stay to the right of header_buttons.

**Comment by minrk** [comment]
Removed the reordering of blocks, since it causes unexpected behavior for elements floated to the right in headercontaner.

**Pull request merged**
