### PR TITLE
fix #11082 - use dpaste.com, also remove py2 compatibility imports

### LINKED ISSUE #11082: pastebin magic does not work: github requires authentication to create gists
Github now [requires authentication](https://developer.github.com/v3/gists/#authentication) to create gists:

> You can read public gists anonymously, but you must be signed into GitHub to create gists.

`%pastebin` does not work anymore and returns 401:

    HTTPError: HTTP Error 401: Unauthorized

### PR DESCRIPTION
**Pull request by spookyvision**

### CODE REVIEW

**Comment by takluyver** [comment]
Thanks! I assume you've tested this locally?

You neatly got the PR number 100 greater than the issue you're fixing.

**Comment by spookyvision** [comment]
yup, I did do some tests, including output containing utf-8:
[http://dpaste.com/0A3XY3N](http://dpaste.com/0A3XY3N)

**Comment by spookyvision** [comment]
oops, wrong button I guess

**Comment by takluyver** [comment]
Thanks!

**Pull request merged**
