### PR TITLE
Fix upload feature for new dashboard UI

### LINKED ISSUE #7619: Notebook upload new notebook UI is wonky
Uploading a notebook in master doesn't work right... clicking on Upload button doesn't stop... clicking in edit name box gives 400 error, but then continues.

### PR DESCRIPTION
**Pull request by jdfreder**
closes #7619

### CODE REVIEW

**Comment by takluyver** [comment]
@dsblank - do you have time to test this?

**Comment by dsblank** [comment]
I'll try right now...

**Comment by dsblank** [comment]
Looks good! (Of course, the new notebook immediately is sorted into the list of preexisting notebooks, but that is another issue). Thanks!

**Comment by takluyver** [comment]
Great, thanks for testing. The code changes look OK, so I'm going to merge this.

**Pull request merged**
