### PR TITLE
Moving unpack_models to widget.js

### PR DESCRIPTION
**Pull request by SylvainCorlay**
Since every custom widget having child widgets will need the `unpack_model` function, introduced in #7757.
It could probably be in `widget.js` rather than in `widget_box.js`, especially since widget.js is already where ViewList is defined.

### CODE REVIEW

**Comment by SylvainCorlay** [comment]
@jasongrout

**Comment by jasongrout** [comment]
Makes sense to me.

**Comment by SylvainCorlay** [comment]
Just rebased and also moved the python side widget serialization to widget.py

**Comment by jdfreder** [comment]
Thanks @SylvainCorlay

**Pull request merged**
