### PR TITLE
Don't strip decorators before feeding into block_parser

### LINKED ISSUE #13531: Sphinx ipython directive greedily strips all decorators, including valid python ones!
A sphinx ipython code cell which contains a valid python decorator will currently have the line with the decorator completely stripped before the code is run!

In my case that meant that this code block

```python
.. ipython:: python
    from xgcm import as_grid_ufunc

    @as_grid_ufunc(signature="(ax1:center)->(ax1:left)")
    def diff_forward(a):
        return a - np.roll(a, -1, axis=-1)
```
got executed as this instead
```python
from xgcm import as_grid_ufunc

def diff_forward(a):
    return a - np.roll(a, -1, axis=-1)
```
(which caused an error for me later on). I even renders the html with the missing code gone

Screenshot from 2022-02-16 15-00-17

It's kind of difficult to make a minimum executable example of this bug because normally what happens is the removal of the decorator leads to code that is invalid in some less clear way, such as giving the error 

```
RuntimeError: Code input with no code at /home/tom/Documents/Work/Code/xgcm/doc/grid_ufuncs.rst, line None
```

That's what happened when I tried to make this MWE:

```python

..ipython:: python

    def decorator(func):
        print("Ran the decorator code")
    
    @decorator
    def f():
        print("Ran the undecorated function call")
    
    f()
```

---

Regardless, the problem can be traced back to this line

https://github.com/ipython/ipython/blob/6c44d22a240fc79eba76995c0a04f79cae868f8c/IPython/sphinxext/ipython_directive.py#L266

which implicitly assumes that ANY decorator in the code must be one of the sphinx ipython_directive extension's "pseudo-decorators", and removes it!

This greedy line also causes another bug (/missing feature) of not being able to chain multiple pseudo-decorators together, but the code author (@fperez) seems to have known about that bug.

---

I think the fix for the first bug should be relatively simple, we just need to only strip decorators which actually match those "pseudo-decorators" defined in the ipython_directive's API.

### PR DESCRIPTION
**Pull request by TomNicholas**
This should actually fix #13531 @Carreau (in conjunction with #13532).

### CODE REVIEW

**Comment by TomNicholas** [comment]
Can this please be merged? The failure seems to appear on a bunch of other PRs so isn't caused by this PR's changes.

**Comment by blsqr** [comment]
@TomNicholas @Carreau If I may jump in (as I'm also interested in this getting merged and released): Is there anything left to do here?

**Comment by TomNicholas** [comment]
As far as I know there isn't anything to do - I don't think the test failure has anything to do with me as it also happens on `main`.

**Comment by MrMino** [comment]
Please add a what's new entry that explains what changed from the PoV of the end user. See [documenting what's new](https://github.com/ipython/ipython/tree/master/docs/source/whatsnew/pr).

**Comment by TomNicholas** [comment]
I've added a whatsnew, though now somehow some of the tests appear to be failing...

**Comment by MrMino** [comment]
The failures are irrelevant. See #13695.

Comparing this to `master`, this does seem to fix the issue.

Thank you!

**Pull request merged**
