### PR TITLE
Force completion results to be unicode.

### PR DESCRIPTION
**Pull request by Carreau**
Should fix some of #9379

### CODE REVIEW

**Comment by Carreau** [comment]
note: mostly using `cast_unicode_py2`, but sometime was just a matter of adding a `u` prefix.

**Comment by minrk** [comment]
It says fixes "some of" #9379. Should it be closed now, or is there more to do?

**Comment by Carreau** [comment]
> or is there more to do

I tested most of it, but I would not be surprised to have missed a few branches that could generate `str`s.
So it "might" be completely fixed, you can still close, and reopen if we see people still complaining.

**Comment by minrk** [comment]
I'll go with close & reopen, since we'll just forget about it if it's fixed and doesn't come up again.

**Pull request merged**
