### PR TITLE
Add matplotlib cell magic

### PR DESCRIPTION
**Pull request by francisco-dlp**
In my workflow I often activate the matplotlib inline backend to execute one cell and I go back to the previous backend afterwards. I use the maplotlib line magic for that but I find that this could be done more conveniently if there was a matplotlib cell magic. This pull request modifies the matplotlib line magic to make it work also as a cell magic.

### CODE REVIEW

**Comment by takluyver** [comment]
From the dev meeting last week: we'd prefer this to be a context manager, perhaps even in matplotlib (see e.g. [switch_backend()](http://matplotlib.org/api/pyplot_api.html#matplotlib.pyplot.switch_backend)), but enabling and disabling the inline backend may require hooks after the cell's execution, in which case it couldn't be implemented as a context manager, and we'd consider this approach.

However, at this point, we'd like to leave it until after IPython 3.0, which we are trying to get ready for release. Setting the milestone to 4.0.

**Comment by ellisonbg** [comment]
This one has sat idle for a while with no activity. Any plans to work on this soon? If not, do you mind if we close this until work starts again - it may be the the work needs to be done in matplotlib as well. We are splitting our repo and all existing PRs are going to bit-rot quickly...

**Comment by Carreau** [comment]
I'm closing for inactivity, but did open an Issue reminding us that this was here.

**Comment by francisco-dlp** [comment]
Sorry to be slow to reply. This feature is important for us and we will be
happy to resume work on this in the close future.

2015-04-03 0:29 GMT+02:00 Matthias Bussonnier <notifications@github.com>:

**Pull request closed without merging**
