### PR TITLE
ENH: add support for Qt6 input hooks

### PR DESCRIPTION
**Pull request by tacaswell**
This is heavily cribbed from Matplotlib's Qt6 support.

### CODE REVIEW

**Comment by Carreau** [comment]
Let's see if that backports cleanly to 7.x

**Comment by pijyoi** [comment]
Tried briefly 7.27 with Qt6 on Windows. It works with PySide6 but not PyQt6.

```
(allqt) PS C:\work> $env:QT_API="pyqt6"
(allqt) PS C:\work> ipython
Python 3.8.10 (tags/v3.8.10:3d8993a, May  3 2021, 11:48:03) [MSC v.1928 64 bit (AMD64)]
Type 'copyright', 'credits' or 'license' for more information
IPython 7.27.0 -- An enhanced Interactive Python. Type '?' for help.

In [1]: %gui qt

In [2]: Traceback (most recent call last):
# snip
  File "c:\work\venv\allqt\lib\site-packages\IPython\terminal\pt_inputhooks\qt.py", line 67, in inputhook
    event_loop.exec_()
AttributeError: 'QEventLoop' object has no attribute 'exec_'
```

**Comment by tacaswell** [comment]
That is odd, I would have expected the traceback to be hitting around line 83 as https://github.com/ipython/ipython/blob/24512bd2988dd5eefc848736e8405ab02853ffba/IPython/terminal/pt_inputhooks/qt.py#L81 is the relevant line at the 7.27.0 tag.

**Comment by MrMino** [comment]
I guess this is a bug? @pijyoi or @tacaswell could one of you please put it up as a new issue?

**Comment by pijyoi** [comment]
Ok, I have created issue #13116

**Comment by MrMino** [comment]
@pijyoi thanks!

**Pull request merged**
