### PR TITLE
Remove the popup widget

### LINKED ISSUE #7299: Remove popup widget

### LINKED ISSUE #7348: Floating widgets should be created at the point of code execution, not atop the page
I tried running the example notebook `examples/Interactive Widgets/Variable Inspector.ipynb`, and the variable inspector is created atop the page, invisible to the user. You need to scroll back up to find it.

This makes for pretty poor usabilit/discoverability.  I think we should try to fix it before 3.0, if possible at all. But I don't know how much it would require a big overhaul of the scrolling model, which I know has been already the source of lots of grief. Perhaps @jdfreder has some thoughts here?

### PR DESCRIPTION
**Pull request by jdfreder**
Drops support for the popup widget.

closes #7281
closes #7299 
closes #7348

Pinging @jasongrout who I know is using this.  I didn't remove any of the functionality required to implement and maintain it independent of IPython.

### CODE REVIEW

**Comment by damianavila** [comment]
Seems good to me...

**Comment by Carreau** [comment]
+1

**Comment by rossant** [comment]
Why did you remove this?

**Comment by theengineear** [comment]
@jdfreder , I was planning on using the popup widget with a default state of being cemented in the page. What is the *right* way to give this functionality given this removal? Just trying not to require code changes when the next version of IPython is released.

Should this be handled outside of the widgets framework? I.e., some extra custom JS?

**Comment by jasongrout** [comment]
Reasoning behind moving this: https://github.com/ipython/ipython/pull/7281#issuecomment-68276486

**Pull request merged**
