### PR TITLE
Only enable "resume hinting" with right arrow if at the EOL

### LINKED ISSUE #14051: Right arrow broken in 8.12.1
The -> arrow doesn't work. When I press the <- arrow to go back and edit the current command, Ipython ignores it.

I don't think my explanation is very clear, so here is an example. If I type:

```
In [1]: print(A
```
And realise I forgot to open the quotes, I go back,

```
In [1]: print("|A
```
Now I am stuck, and cannot "hop" over A. I can keep moving backwards, though. Pressing `end` does work.
 
I have replicated it in an empty virtualenv under both Python 3.9 and 3.10.  The problem disappears downgrading to Ipython 8.12.0.
I am using Fedora Linux, with Qterminal 1.1.0.

### PR DESCRIPTION
**Pull request by krassowski**
Fixes #14051

### CODE REVIEW

**Comment by 2sn** [comment]
@krassowski How can I disable this new hinting and right-arrow feature?  My apologies, whereas it may look nice, I find it rather unsuitable for practical work.

**Comment by krassowski** [comment]
What specifically do you find unsuitable for practical work? If this is about https://github.com/ipython/ipython/issues/14051 issue, this PR fixes it and I believe @Carreau will look at releasing a bug fix soon. I apologise but there is not much I can do here.

**Review by sebcampos — COMMENTED** [review]
sweet

**Comment by krassowski** [comment]
Every shortcut can be changed to your liking since https://github.com/ipython/ipython/pull/13928, with documented [`TerminalInteractiveShell.shortcuts`](https://ipython.readthedocs.io/en/stable/config/options/terminal.html#configtrait-TerminalInteractiveShell.shortcuts) traitlet, [list of shortcuts](https://ipython.readthedocs.io/en/stable/config/shortcuts/index.html#terminal-shortcuts-list).

**Pull request merged**
