### PR TITLE
BUG: Make behavior of -i and -n independent.

### LINKED ISSUE #10303: BUG: (Unintended?) Interaction between -n and -i arguments to %run
The documentation states that `-i` would run the script in the present notebook's namespace while `-n` would prevent the `__name__` in the script from being set to `__main__`, thereby preventing execution of code hidden behind the `if __name__ == '__main__':` check.

However, [the code](https://github.com/ipython/ipython/blob/master/IPython/core/magics/execution.py#L665) only takes the `-n` into account only if `-i` is NOT passed to the `%run` (i.e. in the `else` branch).

Shouldn't it be handled before checking for `-i`?

Or is it necessary to change the `__name__` of the program set to `__main__` to run it in the namespace of the notebook?

### PR DESCRIPTION
**Pull request by musically-ut**
Fixes #10303.

### CODE REVIEW

**Comment by takluyver** [comment]
This seems reasonable. I've marked it for 6.0 because `%run` is quite delicate code, so I'd rather not change it in a 5.x release.

**Comment by musically-ut** [comment]
Umm ... so this change is going to be in the next release?

Should I make a CHANGELOG entry somewhere?

**Comment by takluyver** [comment]
Oh yeah, that's a good idea. If you want to make a new PR for it, put a rst snippet in `docs/source/whatsnew/pr/` - we have a script that later merges them into a changelog file.

**Comment by musically-ut** [comment]
Okay, will do.
And any regression tests?

**Comment by takluyver** [comment]
%run can be a bit awkward to test, which is why I didn't ask for one before, but if you're keen, please have a look at the existing tests in `IPython.core.tests.test_run`. Actually, this is probably easier than I thought - have a look at `test_run__name__` in that file.

**Pull request merged**
