### PR TITLE
Update documentation dependencies

### PR DESCRIPTION
**Pull request by astrojuanlu**
Attempt to fix the CSS weirdness described in https://github.com/readthedocs/readthedocs.org/issues/8638.

### CODE REVIEW

**Comment by astrojuanlu** [comment]
@Carreau Would you like to [enable the pull request builder for IPython](https://docs.readthedocs.io/en/stable/pull-requests.html) so we can see the effect of this before merging?

**Comment by astrojuanlu** [comment]
Also, I see that RTD is using `docs/environment.yml`:

https://github.com/ipython/ipython/blob/1a57d41f6b58b41a7f78468ce1044e8a090a9000/readthedocs.yml#L1-L2

But there's also `docs/requirements.txt`, used by the CI:

https://github.com/ipython/ipython/blob/1a57d41f6b58b41a7f78468ce1044e8a090a9000/.github/workflows/docs.yml#L19-L22

On one hand, we could make RTD use `docs/requirements.txt` and avoid the use of conda (unless there's a good reason for it), and on the other hand, the GH Actions workflow for building the docs would become redundant if the RTD PR Builder is enabled.

**Comment by Carreau** [comment]
> @Carreau Would you like to [enable the pull request builder for IPython](https://docs.readthedocs.io/en/stable/pull-requests.html) so we can see the effect of this before merging?

Done.

**Comment by Carreau** [comment]
> On one hand, we could make RTD use `docs/requirements.txt` and avoid the use of conda (unless there's a good reason for it), and on the other hand, the GH Actions workflow for building the docs would become redundant if the RTD PR Builder is enabled.

Yeah, I need to cleanup a lot of the CI stuff.

**Comment by astrojuanlu** [comment]
I think the PR builder is not running 🤔

**Comment by Carreau** [comment]
I've set up the webhook again but I got a "Webhook activation failed. Make sure you have the necessary permissions.", red message on top.

**Comment by Carreau** [comment]
I had to re connect my account. Even if it was connected, I guess the requested permissions are broader than before, and it was thus not working. Maybe something need to be added in https://docs.readthedocs.io/en/latest/connected-accounts.html

**Comment by Carreau** [comment]
It's being triggered now.

**Comment by astrojuanlu** [comment]
Build is passing and, looking at https://ipython--13261.org.readthedocs.build/en/13261/whatsnew/version7.html#ipython-7-29 vs https://ipython.readthedocs.io/en/latest/whatsnew/version7.html#ipython-7-29, the CSS got fixed 👍🏽

**Pull request merged**
