### PR TITLE
Mpl magics

### PR DESCRIPTION
**Pull request by tacaswell**
The first commit is (I think) non-controversial

The second is something I would like, but may be too aggressive.

### CODE REVIEW

**Comment by Carreau** [comment]
+1 to both.

**Review by Carreau — APPROVED** [review]

**Comment by tacaswell** [comment]
Can I also request that these be backported as far as is practical?

**Comment by minrk** [comment]
@meeseeksdev backport to 5.x

**Comment by Carreau** [comment]
@meeseeksdev backport

**Pull request merged**
