### PR TITLE
Break up convert_notebooks so that it is easier to subclass

### PR DESCRIPTION
**Pull request by Carreau**
Backport of #8073 requested by @ellisonbg to run nbgrader for his class. 
Cf: https://github.com/jupyter/nbgrader/pull/184#issuecomment-88561891

### CODE REVIEW

**Comment by Carreau** [comment]
This is a PR agains 3.x, ping @jhamrick also.

**Comment by minrk** [comment]
Weird, I thought we did backport that one. :+1:, in any case.

**Comment by Carreau** [comment]
> Weird, I thought we did backport that one. , in any case.

No it was marked on one of the first to be 4.0, and was considered not necessary for 3.x until @ellisonbg decided to use 3.x for his class.

**Comment by jhamrick** [comment]
Great, thanks!

**Pull request merged**
