### PR TITLE
Disable stdin in ExecutePreprocessor

### LINKED ISSUE #7880: Making stdin optional when creating new kernels
It would be useful for the `ExecutePreprocessor` (and other things that want to automatically run notebooks on the fly) to be able to easily disable `stdin` -- otherwise, if there is something like a call to `input`, it causes the preprocessor to just hang and eventually time out. I think this would just involve adding a new kwarg to this function: https://github.com/ipython/ipython/blob/master/IPython/kernel/manager.py#L417 and then calling `kc.start_channels(stdin=stdin)`, where `stdin` is whatever value that was passed in (True by default).

Questions:
1. Is there some other way to do this that I missed?
2. If not, does this change sound ok? If so, I'll go ahead and make a PR for it and add an option to disable stdin to the `ExecutePreprocessor` as well.

### PR DESCRIPTION
**Pull request by jhamrick**
Fixes #7880 

I made `allow_stdin` be false by default, because it seems to me that for executing a notebook on the command line, that makes the most sense.

### CODE REVIEW

**Comment by Carreau** [comment]
Oh, you already made it non configurable :-)  You are fast.

**Comment by Carreau** [comment]
+1, let's wait for travis.

**Comment by Carreau** [comment]
Marking as 3.1, but I'm ok for 3.0

**Comment by takluyver** [comment]
I marked the other PR 3.1, but I'm also happy if we want to put this in 3.0. We should be careful, not paranoid.

**Pull request merged**
