### PR TITLE
[WIP] Real Time for text editor

### PR DESCRIPTION
**Pull request by Carreau**
Changes I needed to get real-time working on codemirror with google drive. 

I'll use that as a meta issues for the things I'm concerned about, and that would have to be done in implementations.
- Codemirror use from/to with line/char index, while collaborative string is purely an index in the string. 
  - Not convince about the conversion from one to the other, especially if chars have been inserted/ deleted  while the changes where propagated. The collaborative string cannot (as far as I understand) be the real string backend in codemirror, so you actually have to store one more model of the cell text and sync codemirror/this model. You cannot do codemirror.setValue(text) on changes as it looses the cursor position. The alternative would be to sync codemirror with a (list of string) I guess.
  - check effect of unicode \cat \dog, and other chars that have a "lenght" of 2.
- document name/title need to be collaborative. 
- save state (dirty) make no sens. 
  - Clicking saving might make no sens.
    - At least with google drive you could though separate the RT model from the "on disk" so save could make sens to update copy "on disk" but thats feel like a weird model, but might make sens if you are actually editting a library code. The "state" of the editor is synced, but the code you want to execute by your kernel need to be "saved".
- Codemiror change generation might also interfere.
- not sure about highlight mode, should it be synced ?. It is set through file name by default.
- Need position of others cursor ?

(i havent push my changes to Jupyterdrive yet)

### CODE REVIEW

**Comment by Carreau** [comment]
From @ellisonbg break on `backtick, enter` as that backtick auto close by another backtick on pressing enter as on french keyboard, backtick is a combining chars.

**Comment by Carreau** [comment]
Javascript hates me. The RT api refuse all my connexion today. `500 (OK)`

**Comment by ellisonbg** [comment]
@Carreau do you want to re-issue this against the 3.x branch so folks can play with it while the Big Split happens?

**Comment by Carreau** [comment]
Notebook has not been splitted yet so that would be identical, but sure...

**Comment by Carreau** [comment]
cc @ian-r-rose

**Pull request closed without merging**
