### PR TITLE
Fix several DeprecationWarning: invalid escape sequence

### PR DESCRIPTION
**Pull request by BoboTiG**
Hello,

This is a little patch to fix all `DeprecationWarning: invalid escape sequence`.

Signed-off-by: Mickaël Schoentgen <contact@tiger-222.fr>

### CODE REVIEW

**Comment by Carreau** [comment]
Thanks, that was likely painful to track.  I know there was a few left :-)

**Comment by Carreau** [comment]
(assuming it returns non-0 if error,  and 0 otherwise)

**Comment by BoboTiG** [comment]
Yes, using `PYTHONWARNINGS=all python -Werror -m compileall *` will return `1` on error. Note that I change the dot for a joker to not include hidden folders like `.git` and `.tox` (this one would almost always return an error as it contains a lot of modules).

**Comment by BoboTiG** [comment]
Something like that could work?
```diff
diff --git a/.travis.yml b/.travis.yml
index 9ad7b9b..174f000 100644
--- a/.travis.yml
+++ b/.travis.yml
@@ -47,6 +47,8 @@ script:
     if [[ "$TRAVIS_PYTHON_VERSION" == "nightly" ]]; then
        # on nightly fake parso known the grammar
        cp /home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/parso/python/grammar37.txt /home/travis/virtualenv/python3.8-dev/lib/python3.8/site-packages/parso/python/grammar38.txt
+       # ensure no syntax depreciation
+       PYTHONWARNINGS=all python -Werror -m compileall *
     fi
   - cd /tmp && iptest --coverage xml && cd -
   # On the latest Python (on Linux) only, make sure that the docs build.
```

**Pull request merged**
