### PR TITLE
add ipython_genutils

### PR DESCRIPTION
**Pull request by minrk**
copies of shared dependencies, that can't feasibly be detangled.

This package will only exist as long as it has to,
and will be killed as soon possible.

From the dev meeting, since IPython Prime will likely preserve the need for the relocated functionality, these are _copies_ of existing files, leaving the originals in IPython. The only one I'm not sure about on that front is py3compat - should py3compat be a copy, or should we use genutils, even in IPython Prime?
- ipstruct, tempdir, py3compat (+encoding) are whole
- path, text are reduced to remove some IPython-only bits
- testing.decorators removes the dependencies on knownfailure,
  since only IPython projects use those at this point.

### CODE REVIEW

**Comment by Carreau** [comment]
If this is 100% a new package, why not make a new repo **now**, and release it on PyPi ? It's not like we are moving things around and need to keep it working , or is it for nexts PRs ?

**Comment by minrk** [comment]
@Carreau all of the splits are new packages. We are doing the split in this repo because the history of these files will be preserved, even though they are copies.

**Comment by Carreau** [comment]
Ah, true. 

+1 then

**Comment by minrk** [comment]
I realize that since IPython won't use these, genutils will only be used by Jupyter, so maybe jupyter_genutils makes more sense. It is 'genutils from IPython', so I could go either way. Anyone care?

**Comment by Carreau** [comment]
Don't really care as it's meant to disapear, but feel free to rename.

**Pull request merged**
