### PR TITLE
Deprecation and removal for 8.17

### PR DESCRIPTION
**Pull request by Carreau**
See #14186

I think for each of those warning we should:

1) Open an issue for removal, and update the corresponding warnings text to point to the corresponding issue.

### CODE REVIEW

**Comment by bollwyvl** [comment]
I like what pyodide does:

https://pyodide.org/en/stable/project/deprecation-timeline.html#pyodide-deprecation-timeline

Maybe such a thing can be gathered with some plugin like:\

https://deprecation.readthedocs.io/en/latest/

**Comment by bollwyvl** [comment]
There are also some fun tools that can consume/profile such decorators:

https://github.com/QuantStack/memestra

**Comment by Carreau** [comment]
Or likely something like @takluyver https://pypi.org/project/astsearch/ to find functions with `warnings.warn(??, DeprecationWarning)` inside...

**Comment by Carreau** [comment]
In general I find like `@deprecated` decorator make things more complicated than just emitting a warning. You need to learn them and they force you in a framework that always need to more options. Like sometime deprecated mean the function/argument already does nothing and it is already safe to not use it. Sometime you need to describe the replacement... etc.

**Comment by bollwyvl** [comment]
Sure, that works too... end of the day, having a clear, statically-verified collection of _What Will Break In IPython X.Y_ in the docs is win. A sphinx directive that could collect them via `ast` or whatever would be win.

**Pull request merged**
