### PR TITLE
Allow specifying the name of the root element of a JSON display object

### PR DESCRIPTION
**Pull request by dhirschfeld**

### CODE REVIEW

**Comment by dhirschfeld** [comment]
PR as suggested by @gnestor in https://github.com/jupyterlab/jupyterlab/pull/4436#issuecomment-384466742

I guess the benefit of of this is in explicitly documenting this capability (for frontends which support it)

**Review by gnestor — CHANGES_REQUESTED** [review]
Looks good to me but it looks like the `test_json` tests are failing because they're not expecting a `root` arg: https://github.com/ipython/ipython/blob/master/IPython/core/tests/test_display.py#L213-L240

**Comment by dhirschfeld** [comment]
^^^will look into that.

**Review by gnestor — APPROVED** [review]
Looks good!

**Comment by Carreau** [comment]
Thanks !

**Pull request merged**
