### PR TITLE
Another attempt at blacklisting collections for dreload

### PR DESCRIPTION
**Pull request by takluyver**
Making a PR to see what Travis thinks. #8528 didn't go very well.

### CODE REVIEW

**Comment by takluyver** [comment]
This passes on Travis, and on [Python 3.4 + Windows](https://jenkins.jupyter.org/job/windows-py3.4-prtest/8/) on Jenkins. Ping @Carreau

**Comment by takluyver** [comment]
The failure on 3.5 on Travis is the same on master, not something this introduces.

**Comment by Carreau** [comment]
Travis is happy. Let's make Jenkins and Thomas Happy By pressing TBGB (the big green button)

**Comment by takluyver** [comment]
Hooray! Now lunch, which also makes me happy.

**Pull request merged**
