### PR TITLE
use pathlib in test_extension, test_logger, test_application, test_oinspect, and test_profile

### PR DESCRIPTION
**Pull request by Creonalia**
replaces path strings with pathlib.Path objects as per [this issue](https://github.com/ipython/ipython/issues/12515)

### CODE REVIEW

**Comment by Creonalia** [comment]
I think the tests failed because I missed a string conversion; I'll fix that.

**Comment by Carreau** [comment]
Thanks, you've done many files and this currently unfortunatly conflict with some tings that have already been merged in master, there are thus conflicts. Would you be able to solve them, or do you need me the fix those for you ?

**Comment by Creonalia** [comment]
Conflicts should be fixed now, looks like it was just some different syntax.

**Comment by Carreau** [comment]
Thanks for your work I was not able to keep up with PRs, I'm going to close as this now conflict, and I'm trying to reduce the numbers of PRs.

**Pull request closed without merging**
