### PR TITLE
Remove image resizer

### PR DESCRIPTION
**Pull request by ghost**
This PR removes the image resizer for images. Removing the resizer helps a lot to solve the image overflow issue in #7701. Related PR: #8062.

Before:
screenshot from 2015-03-20 10 48 02

After:

screenshot from 2015-03-20 10 49 48

### CODE REVIEW

**Comment by jdfreder** [comment]
-1 because I like this feature.

**Comment by rsmith31415** [comment]
I don't have anything against this feature but it is causing significant issues and preventing us from implementing solutions that are trivial CSS fixes (e.g. something like [this](https://github.com/ipython/ipython/compare/master...rsmith31415:css-fix-width-images)  as a fix to #7701).

Furthermore, the current jquery-ui `.resizer` is not responsive-friendly, so we can't have a fully responsive (or even fluid) layout. That is by far the more important consideration in terms of user experience and as a foundation to prevent more related issues.

Finally, the resizer (I think) is not widely used or even easily recognized. Its removal is not likely to disrupt the workflow of users. Actually, I would worry about excessively using the resizer to obtain larger images instead of doing it programmatically.

**Comment by minrk** [comment]
We are going to merge all the things - remove resize, add simpler 'expand to original' from #8062, *and* scroll the output_subarea on overflow.

**Comment by cancan101** [comment]
Given that the resize handle is now gone, how do I make the image render larger? I am trying this and it does not seem to work:
```
current = %config InlineBackend.rc
current['figure.figsize'] = (9,6)
%config InlineBackend.rc = current
```

**Comment by rsmith31415** [comment]
@cancan101 

I think this is a question related to matplotlib. You can simply use:

```
import matplotlib
%matplotlib inline

matplotlib.rcParams['figure.figsize'] = (12,9)
```

**Comment by cancan101** [comment]
That seems to work. What then does `InlineBackend.rc['figure.figsize']` even mean?

**Comment by Carreau** [comment]
that tells the default size for the figure when using inline figures with
matplotlib.

**Comment by cancan101** [comment]
I have `%matplotlib inline` set and am plotting using:
```
    import matplotlib.pyplot as plt
    plt.imshow(img)
```
and `InlineBackend.rc['figure.figsize']` does not seem to do anything.

**Comment by Carreau** [comment]
you can try :

   import matplotlib
  matplotlib.rcParams['figure.figsize'] = [sizex, sizey]

but anyway the better way to do it is to learn the OO way of matplotlib.

**Comment by cancan101** [comment]
OO way?

**Comment by Carreau** [comment]
Object oriented. Create figure and axis references and manipute them. 

```
%matplotlib inline
import matplotlib.pyplot as plt
fig, ax = plt.subplots(1,1)
fig.set_figwidth(7)
fig.set_figheight(11)
ax.plot(range(10))
```

**Comment by rsmith31415** [comment]
If I understood @cancan101 's question correctly, I think he wants to set the image size for all figures in the notebook. Otherwise, there is no need to be manipulating global variables.

By the way, it is easier to do this:

```
fig, ax = plt.subplots(figsize=(7,11))
ax.plot(range(10))
```

**Comment by robcross** [comment]
I really really miss the resizer!!!

Changing the figsize is NOT alternative to the resize handle. 

```python
fig, ax = plt.subplots(figsize=(8,10))
ax.plot(range(10))
plt.show()

fig, ax = plt.subplots(figsize=(4,5))
ax.plot(range(10))
plt.show()
```

The font size and line widths are the same, but the plot is twice as big. When I'm trying to make publication ready figures, it is nice so set the figsize that will put the text in proportion with the plot, and use the resize handle to get a closer look.

Is there another solution to quickly and easily scale figures? Like actually scale everything? Or do I have to output to a file and view it from there now?

**Pull request merged**
