### PR TITLE
remove deprecated variable - default_gui_banner

### PR DESCRIPTION
**Pull request by srinivasreddy**

### CODE REVIEW

**Comment by srinivasreddy** [comment]
issue https://github.com/ipython/ipython/issues/9259

**Comment by srinivasreddy** [comment]
deprecated PR https://github.com/ipython/ipython/pull/9257

**Comment by takluyver** [comment]
I've marked this for 7.0 like #9259. We're still making 6.x releases of master at the moment, so this will need to wait.

**Comment by Carreau** [comment]
Master is now on the way to be 7.0 ! Thanks for your patience ! Merging !

**Pull request merged**
