### PR TITLE
use promises to wait for kernelspecs on notebook load

### LINKED ISSUE #7328: Error loading notebook
Using Firefox I get an error with the following message when loading some notebooks:
`TypeError: ks is undefined`

The javascript log output is:
```
TypeError: ks is undefined
var new_mode_url = 'kernelspecs/'+ks.name+'/kernel';
``` 
in Lines 2093 and also 2100 of `notebook.js`.

This is with current master using Anaconda and Firefox (tested with Linux and Windows).
Example notebook: https://gist.github.com/juhasch/67e38a443ce220d7247c

### PR DESCRIPTION
**Pull request by minrk**
should avoid race condition that causes attempt to load kernelspec prior to loading the kernelspec list

should close #7328

@juhasch, @twiecki can you check if this actually fixes the problem?

### CODE REVIEW

**Comment by Carreau** [comment]
+1 once travis happy.

**Comment by juhasch** [comment]
Sorry, doesn't look like it helps.

**Comment by juhasch** [comment]
It's this line no. 1773 in notebook.js that makes the trouble:
`this.kernel_selector.change_kernel(this.metadata.kernelspec.name);`

**Comment by minrk** [comment]
This now cleans up the kernelselector logic more substantially. I'll write up a description of the various event sequences, so we can be sure everything's correct.

**Comment by juhasch** [comment]
Hey, what did you do with that nice error message ?
It's gone. Thanks guys.

**Comment by minrk** [comment]
@juhasch thanks for checking

**Comment by takluyver** [comment]
This looks good to my eyes. Merging.

**Pull request merged**
